### ISSUE TITLE
`/run/keys` permission prevents reading keys for normal users

### ISSUE THREAD

**Issue by MartinPotier** [NixOS/nixops#1012]
I'm storing the secret part of the mopidy configuration as a key in `/run/keys`. But, as this dir has permission mode `0750` and is set to belong to `root:keys`, my key (which is set to be available to the mopidy user) cannot be *accessed*. Running `chmod o+x /run/keys` fixes the problem, but it's not a long time solution.

https://github.com/NixOS/nixops/blob/master/nix/keys.nix#L189

Storing keys in another directory won't fix the problem, since it would be set up the same way if it doesn't exist (and I'd want it to be created if missing).

How should I proceed?

**Comment by eqyiel** [comment]
@MartinPotier you can just add your mopidy user to the keys group like this:

https://github.com/eqyiel/dotfiles/blob/dff548627e65fd06a318de4d38f892768eaec1b0/nix/.config/nixpkgs/nixops/realms/maher.fyi/config/nextcloud.nix#L70-L77

**Comment by MartinPotier** [comment]
I see.

Thanks for the pointer. I think this should be in the manual for beginners like me.

**Comment by MartinPotier** [comment]
@jpotier you may be interested in this as well.
