### ISSUE TITLE
network.enableRollback = true does not create profile

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixops#1030]
According to https://github.com/NixOS/nixops/issues/272#issuecomment-77019812 and https://github.com/NixOS/nixops/issues/53, a profile should be created in ```/nix/var/nix/profiles/per-user/<username>/nixops/<uuid>``` but that doesn't seem to be the case. Having used multiple versions of nixops over the last year, at no point have I seen a ```nixops``` directory in there.

**Comment by aanderse** [comment]
@peterhoeg odd... I see all my nixops generations in that directory. And you have `network.enableRollback` set, right?  :thinking:

**Comment by peterhoeg** [comment]
Most of the deployments here have ```enableRollback = true;``` but I don't even have the ```/nix/var/nix/profiles/per-user/<username>/nixops``` directory.

**Comment by peterhoeg** [comment]
I had written ```network.enableRollBack``` and not ```network.enableRollback``` on the very first deployment and that was simply copied around to subsequent deployments. Sorry about that. Works perfectly fine with the proper casing.
