### ISSUE TITLE
Proposal: use custom images to create digital ocean machines

### ISSUE THREAD

**Issue by eamsden** [NixOS/nixops#1051]
Digital Ocean supports [custom images](https://developers.digitalocean.com/documentation/v2/#images) which can be added and updated via its API. This seems like a smoother way for NixOps to create NixOS droplets than by booting an Ubuntu droplet and using NIXOS_LUSTRATE. Further, already-running machines should be updated in place via SSH.

I would be willing to hack on this, but I am fairly new to Nix and would need mentoring. I see some Nix code already in place in NixOps to create qcow2 images, so the trickiest bit may already be done.

**Comment by wmertens** [comment]
Duplicate of #1017…

**Comment by eamsden** [comment]
Closing because duplicate as mentioned above.
