### ISSUE TITLE
SSH port in ~/.ssh/config is ignored

### ISSUE THREAD

**Issue by kwohlfahrt** [NixOS/nixops#1053]
I have a machine available on my local network  as `foo.home`, with SSH on port 22. So I can do `deployment = { targetHost = "foo.home"; targetEnv = "none"; }`. This works as expected.

If I add this section to `~/.ssh/config`:

```
Host foo.home
  HostName foo.example.org
  Port 10022
```

`nixops deploy` no longer works, even though I can still `ssh foo.home` as I normally would. NixOps is ignoring the port set in my SSH config, which is annoying as I now have to maintain this port in two places. Ideally it should take the default port used by the SSH client if not configured otherwise.

**Comment by Assassinkin** [comment]
I think you can use targetPort and specify the prot you want to run ssh on: 

```
deployment.targetPort = mkOption {
      type = types.int;
      description = ''
        This option specifies the SSH port to be used by
        NixOps to execute remote deployment operations.
      '';
    };
```

**Comment by kwohlfahrt** [comment]
I know, the problem is when I don't specify this option, it ignores my `~/.ssh/config`.

Currently I'm experimenting with NixOps to manage my home network. Running it from inside my home network, I use one hostname (`foo.home`) and port (`22`). Now if I want to run the same thing from say my work computer, I need to use a different hostname (`foo.example.org`) and port (`10022`) due to port forwarding and stuff.

Currently, I have to edit my deployment on my work computer, instead of just having a different `~/.ssh/config` files on each computer. It works fine for the hostname, so it should behave similarly for the port.

**Comment by Assassinkin** [comment]
I think it is not currently possible for nixops to read the port from the config file. ssh_port is set by this  `ssh_port = nixops.util.attr_property("targetPort", 22, int)`  in this file: https://github.com/NixOS/nixops/blob/master/nixops/backends/__init__.py
So it tries to find targetPort if it is not set then it use 22 by default.

**Comment by kwohlfahrt** [comment]
Yes, and then it seems to be used [here](https://github.com/NixOS/nixops/blob/28231a177d751e800af3223a8763ea75b0ef9dd9/nixops/backends/__init__.py#L277). However, if no `-p` flag is passed, the port set in `~/.ssh/config` should be used right?

So if the attribute defaults to `None`, this function can then check and conditionally not add the flag at all. Unfortunately, `ssh_port` is also used in a few other locations when checking to see if a host is up (e.g. [here](https://github.com/NixOS/nixops/blob/28231a177d751e800af3223a8763ea75b0ef9dd9/nixops/backends/__init__.py#L193)), and I'm not sure what should be done there.

**Comment by Assassinkin** [comment]
@kwohlfahrt  Should be fixed by this [PR](https://github.com/NixOS/nixops/pull/1024/files)

**Comment by wmertens** [comment]
Would this not be simply solved by not passing `-p` if port is `None`? And not assigning 22 by default?

**Comment by wmertens** [comment]
Indeed, with #1382 it's fixed.
