### ISSUE TITLE
Add support for S3 Object Lifecycle Management

### ISSUE THREAD

**Issue by alexeiskachykhin** [NixOS/nixops#1082]
Feature request:

Having NixOps support S3 Object Lifecycle Management rules would allow to turn some administrative tasks into code. For projects with multiple environments it would help reduce configuration drift.

**Comment by PsyanticY** [comment]
PR for this: https://github.com/NixOS/nixops/pull/1083

**Comment by AmineChikhaoui** [comment]
Closing as https://github.com/NixOS/nixops/pull/1083 is merged now.
