### ISSUE TITLE
nixops broken with master nixpkgs

### ISSUE THREAD

**Issue by delroth** [NixOS/nixops#1086]
nixos/nixpkgs@27982b408e465554b8831f492362bc87ed0ec02a seems to have broken nixops:

    error: 'mkOption' at /home/delroth/work/nixpkgs/lib/options.nix:30:5 called with unexpected argument 'options', at /nix/store/pslrp15wfmma1aj9m2f6vy6m6s12xp7v-nixops-1.6.1pre0_abcdef/share/nix/nixops/gce.nix:382:19

Looks like "options" support in mkOption got removed.

**Comment by gchinis** [comment]
Is this really fixed?
I am coding thought the NixOps manual and I am getting this error exactly.

Command
`nixops deploy -d trivial`

System:
macOs Mojave 10.14.2
NixOps 1.6.1

**Comment by charukiewicz** [comment]
As I posted in #1107:

For time time being, you can build the `nixopsUnstable` version of by switching to an older `nixpkgs` channel (and there might be a better way to do this):

```bash
# Add the nixpkgs-18.09 channel
nix-channel --add https://nixos.org/channels/nixos-18.09 nixpkgs1809
# Download the Nix expressions of all subscribed channels
nix-channel --update
# Install the nixopsUnstable package from the newly added nixpkgs-18.09 channel
nix-env -iA nixpkgs1809.nixopsUnstable
```

This should install `nixops-1.6.1pre2706_d5ad09c`, as opposed to `nixops-1.6.1pre2728_8ed39f9`, which currently has a broken dependency.
