### ISSUE TITLE
nixops can't recover a machine with stopped ssh

### ISSUE THREAD

**Issue by davidak** [NixOS/nixops#1098]
I have stopped sshd on one machine:

```
[davidak@ethmoid:~/code/nixops]$ nixops ssh -d load-balancer proxy
[root@proxy:~]# systemctl stop sshd
```

Then i deployed again. I would assume that sshd will get restarted. But the machine seems to be lost forever. (i havn't set a root password. you would have to recover it)

```
[davidak@ethmoid:~/code/nixops]$ nixops deploy -d load-balancer
backend2> VBoxManage: error: Could not find a registered machine named 'nixops-1d068130-3522-11e9-89f9-024246453e35-backend2'
backend2> VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
backend2> VBoxManage: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2834 of file VBoxManageInfo.cpp
ssh: connect to host 192.168.56.108 port 22: Connection refused
proxy...> VBoxManage: error: The machine 'nixops-1d068130-3522-11e9-89f9-024246453e35-proxy' is already locked for a session (or being unlocked)
proxy...> VBoxManage: error: Details: code VBOX_E_INVALID_OBJECT_STATE (0x80bb0007), component MachineWrap, interface IMachine, callee nsISupports
proxy...> VBoxManage: error: Context: "LockMachine(a->session, LockType_Write)" at line 525 of file VBoxManageModifyVM.cpp
error: Multiple exceptions (2): 
  * backend2: unable to get info on VirtualBox VM ‘backend2’
  * proxy: command ‘['VBoxManage', 'modifyvm', u'nixops-1d068130-3522-11e9-89f9-024246453e35-proxy', '--memory', '512', '--vram', '10', '--nictype1', 'virtio', '--nictype2', 'virtio', '--nic2', 'hostonly', '--hostonlyadapter2', 'vboxnet0', '--nestedpaging', 'off', '--paravirtprovider', 'kvm']’ failed on machine ‘proxy’ (exit code 1)
```
---
nix (Nix) 2.1.3
NixOS 18.09.2203.9bd45dddf81 (Jellyfish)
NixOps 1.6.1

**Comment by AmineChikhaoui** [comment]
I'm not sure if it's an unexpected behavior in this case. Stopping sshd won't make it auto-restart afaik as it's not a crash so ssh is just supposed to not work imo.

**Comment by davidak** [comment]
There might be reasons for a ssh connection to fail, for example the machines firewall. Do you think it would make sense to have another method to recover it?

Or should the manual warn you to set a root password to always be able to login on console?

**Comment by AmineChikhaoui** [comment]
I think that if there is an issue with the sshd service or ssh not working then it's an image issue that should be fixed as it's meant to work out of the box. Other use cases are special cases in which the user can decide to set a root password for console access.
Crashes of sshd should be recoverable as the systemd unit has restart=always.

**Comment by davidak** [comment]
OK
