### ISSUE TITLE
How to Install/Improve the Manual

### ISSUE THREAD

**Issue by gallexme** [NixOS/nixops#1114]
> nix-env -q 
> nixops-1.6.1

> nixops deploy -d server
> vbox> connecting...
> building all machine configurations...
> error: 'mkOption' at /nix/var/nix/profiles/per-user/root/channels/nixos/lib/options.nix:30:5 called with unexpected argument 'options', at /nix/store/iymm3rm8d73mnzqnqas3isxxlj53cl2l-nixops-1.6.1/share/nix/nixops/gce.nix:382:19
> (use '--show-trace' to show detailed location information)
> Traceback (most recent call last):
>   File "/nix/store/iymm3rm8d73mnzqnqas3isxxlj53cl2l-nixops-1.6.1/bin/..nixops-wrapped-wrapped", line 990, in <module>
>     args.op()
>   File "/nix/store/iymm3rm8d73mnzqnqas3isxxlj53cl2l-nixops-1.6.1/bin/..nixops-wrapped-wrapped", line 411, in op_deploy
>     max_concurrent_activate=args.max_concurrent_activate)
>   File "/nix/store/iymm3rm8d73mnzqnqas3isxxlj53cl2l-nixops-1.6.1/lib/python2.7/site-packages/nixops/deployment.py", line 1056, in deploy
>     self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
>   File "/nix/store/iymm3rm8d73mnzqnqas3isxxlj53cl2l-nixops-1.6.1/lib/python2.7/site-packages/nixops/deployment.py", line 1045, in run_with_notify
>     f()
>   File "/nix/store/iymm3rm8d73mnzqnqas3isxxlj53cl2l-nixops-1.6.1/lib/python2.7/site-packages/nixops/deployment.py", line 1056, in <lambda>
>     self.run_with_notify('deploy', lambda: self._deploy(**kwargs))
>   File "/nix/store/iymm3rm8d73mnzqnqas3isxxlj53cl2l-nixops-1.6.1/lib/python2.7/site-packages/nixops/deployment.py", line 996, in _deploy
>     self.configs_path = self.build_configs(dry_run=dry_run, repair=repair, include=include, exclude=exclude)
>   File "/nix/store/iymm3rm8d73mnzqnqas3isxxlj53cl2l-nixops-1.6.1/lib/python2.7/site-packages/nixops/deployment.py", line 664, in build_configs
>     raise Exception("unable to build all machine configurations")
> Exception: unable to build all machine configurations

mind updating the install manual so that people don't have to google for hours to find the right solution for such problems?

also tried cloning it and running ./dev-shell

but then I get

> ./dev-shell
> these derivations will be built:
>   /nix/store/g025adh3adpm5zxmnflkg1lqlzc9zhf7-python2.7-azure-mgmt-resource-2.1.0.drv
>   /nix/store/g29m9zh3njpmsic4pi7vnsjdpi7nqh4x-python2.7-azure-mgmt-network-2.5.1.drv
>   /nix/store/ni38fwhybbj8j8mc4f7gpvxg96hxay63-python2.7-azure-mgmt-storage-3.1.1.drv
>   /nix/store/wbvwarpgp5wjfcl4jrfbabc3jc7r7xa7-python2.7-azure-mgmt-compute-4.4.0.drv
> these paths will be fetched (10.76 MiB download, 36.97 MiB unpacked):
>   /nix/store/0d3y29xjhplqc9bsq10j3ka20k0qyl61-azure-mgmt-network-2.5.1.zip
>   /nix/store/110nnm7p0gaw7wzdf0q5dqf2ac8h6q2q-nss-cacert-3.42.1
>   /nix/store/1p80n4k8wvr3z3gqgh95vn1yfc124p9v-python3.7-psutil-5.5.1
>   /nix/store/59g39l0hp98b0hvicad16fgx2rjfpcax-azure-mgmt-storage-3.1.1.zip
>   /nix/store/63karsgdg7fm3q0if4zfd7apbd8ac1ci-stdenv-linux
>   /nix/store/6l0g7fz85a3h6wnxygk0i0k7zx535g61-python2.7-coverage-4.5.2
>   /nix/store/8n7v99ii7cg694pz0cfch422zvkdqfv4-gnumake-4.2.1
>   /nix/store/9z1b1ldrhxh7brsi6fxnyjm7gk8kiynv-bash-interactive-4.4-p23-dev
>   /nix/store/al5rwfkaz0c9hzz8mh3a3pkfggavrl05-azure-mgmt-resource-2.1.0.zip
>   /nix/store/b45fim626lhlvgf1cq4wnxwbvvk9yg35-python2.7-azure-mgmt-nspkg-3.0.2
>   /nix/store/bfj49dqkd77b2w6ail3zs4yig62pchlj-python3.7-mypy_extensions-0.4.1
>   /nix/store/bl1cy3wni09zif764s948mdpsaqp0xqf-hook
>   /nix/store/cf5r9m4nagdcw16vfbiyxv6x1cl27ds6-python2.7-bootstrapped-pip-19.0.3
>   /nix/store/cwgx66v3r37i1r5kj50867klj7ixcsk2-python3.7-lxml-4.3.1
>   /nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670
>   /nix/store/jmzfljmwzv5q29zhrxb7ikf7m0zggv4i-hook
>   /nix/store/k3wg0mgv4mlshh36zdrp0qkp6631psmn-python2.7-nose-1.3.7
>   /nix/store/napl81rcsmv62f7gidmmjbfr7lpi6fq3-python2.7-azure-mgmt-common-0.20.0
>   /nix/store/pzw6m3q8j85a711k4kkwd6yzrgfwj3lx-hook
>   /nix/store/qny0p3ngd0iskpzw4vnl3hcal54bj0fl-hook
>   /nix/store/s7p0wfbdfbq307zgifhnh6w8sfjvy64y-patchelf-0.9
>   /nix/store/v7prxp9wzi5y03lqhyszq9wmm6gb9ml8-python3.7-typed-ast-1.3.1
>   /nix/store/wkdqf3zhihbw0idmnhkm0irmap4laxy7-azure-mgmt-compute-4.4.0.zip
> copying path '/nix/store/110nnm7p0gaw7wzdf0q5dqf2ac8h6q2q-nss-cacert-3.42.1' from 'https://cache.nixos.org'...
> copying path '/nix/store/9z1b1ldrhxh7brsi6fxnyjm7gk8kiynv-bash-interactive-4.4-p23-dev' from 'https://cache.nixos.org'...
> copying path '/nix/store/bl1cy3wni09zif764s948mdpsaqp0xqf-hook' from 'https://cache.nixos.org'...
> copying path '/nix/store/jmzfljmwzv5q29zhrxb7ikf7m0zggv4i-hook' from 'https://cache.nixos.org'...
> copying path '/nix/store/cf5r9m4nagdcw16vfbiyxv6x1cl27ds6-python2.7-bootstrapped-pip-19.0.3' from 'https://cache.nixos.org'...
> copying path '/nix/store/6l0g7fz85a3h6wnxygk0i0k7zx535g61-python2.7-coverage-4.5.2' from 'https://cache.nixos.org'...
> copying path '/nix/store/wkdqf3zhihbw0idmnhkm0irmap4laxy7-azure-mgmt-compute-4.4.0.zip' from 'https://cache.nixos.org'...
> copying path '/nix/store/0d3y29xjhplqc9bsq10j3ka20k0qyl61-azure-mgmt-network-2.5.1.zip' from 'https://cache.nixos.org'...
> copying path '/nix/store/8n7v99ii7cg694pz0cfch422zvkdqfv4-gnumake-4.2.1' from 'https://cache.nixos.org'...
> copying path '/nix/store/59g39l0hp98b0hvicad16fgx2rjfpcax-azure-mgmt-storage-3.1.1.zip' from 'https://cache.nixos.org'...
> copying path '/nix/store/s7p0wfbdfbq307zgifhnh6w8sfjvy64y-patchelf-0.9' from 'https://cache.nixos.org'...
> copying path '/nix/store/al5rwfkaz0c9hzz8mh3a3pkfggavrl05-azure-mgmt-resource-2.1.0.zip' from 'https://cache.nixos.org'...
> copying path '/nix/store/cwgx66v3r37i1r5kj50867klj7ixcsk2-python3.7-lxml-4.3.1' from 'https://cache.nixos.org'...
> copying path '/nix/store/bfj49dqkd77b2w6ail3zs4yig62pchlj-python3.7-mypy_extensions-0.4.1' from 'https://cache.nixos.org'...
> copying path '/nix/store/v7prxp9wzi5y03lqhyszq9wmm6gb9ml8-python3.7-typed-ast-1.3.1' from 'https://cache.nixos.org'...
> copying path '/nix/store/1p80n4k8wvr3z3gqgh95vn1yfc124p9v-python3.7-psutil-5.5.1' from 'https://cache.nixos.org'...
> copying path '/nix/store/b45fim626lhlvgf1cq4wnxwbvvk9yg35-python2.7-azure-mgmt-nspkg-3.0.2' from 'https://cache.nixos.org'...
> copying path '/nix/store/pzw6m3q8j85a711k4kkwd6yzrgfwj3lx-hook' from 'https://cache.nixos.org'...
> copying path '/nix/store/qny0p3ngd0iskpzw4vnl3hcal54bj0fl-hook' from 'https://cache.nixos.org'...
> copying path '/nix/store/k3wg0mgv4mlshh36zdrp0qkp6631psmn-python2.7-nose-1.3.7' from 'https://cache.nixos.org'...
> copying path '/nix/store/napl81rcsmv62f7gidmmjbfr7lpi6fq3-python2.7-azure-mgmt-common-0.20.0' from 'https://cache.nixos.org'...
> copying path '/nix/store/63karsgdg7fm3q0if4zfd7apbd8ac1ci-stdenv-linux' from 'https://cache.nixos.org'...
> building '/nix/store/wbvwarpgp5wjfcl4jrfbabc3jc7r7xa7-python2.7-azure-mgmt-compute-4.4.0.drv'...
> building '/nix/store/g025adh3adpm5zxmnflkg1lqlzc9zhf7-python2.7-azure-mgmt-resource-2.1.0.drv'...
> unpacking sources
> unpacking source archive /nix/store/wkdqf3zhihbw0idmnhkm0irmap4laxy7-azure-mgmt-compute-4.4.0.zip
> unpacking sources
> unpacking source archive /nix/store/al5rwfkaz0c9hzz8mh3a3pkfggavrl05-azure-mgmt-resource-2.1.0.zip
> building '/nix/store/g29m9zh3njpmsic4pi7vnsjdpi7nqh4x-python2.7-azure-mgmt-network-2.5.1.drv'...
> copying path '/nix/store/g0yjxwqx1m4x0fp2gzr00hjpcaip56lq-python3.7-mypy-0.670' from 'https://cache.nixos.org'...
> source root is azure-mgmt-resource-2.1.0
> building '/nix/store/ni38fwhybbj8j8mc4f7gpvxg96hxay63-python2.7-azure-mgmt-storage-3.1.1.drv'...
> setting SOURCE_DATE_EPOCH to timestamp 1546458756 of file azure-mgmt-resource-2.1.0/setup.cfg
> patching sources
> configuring
> sed: can't read azure/mgmt/resource/resourcemanagement.py: No such file or directory
> builder for '/nix/store/g025adh3adpm5zxmnflkg1lqlzc9zhf7-python2.7-azure-mgmt-resource-2.1.0.drv' failed with exit code 2
> error: build of '/nix/store/6qbphcj9bqzyzn9f6qw2aakrb50lmigi-python3.7-mypy-0.670.drv', '/nix/store/g025adh3adpm5zxmnflkg1lqlzc9zhf7-python2.7-azure-mgmt-resource-2.1.0.drv', '/nix/store/g29m9zh3njpmsic4pi7vnsjdpi7nqh4x-python2.7-azure-mgmt-network-2.5.1.drv', '/nix/store/ni38fwhybbj8j8mc4f7gpvxg96hxay63-python2.7-azure-mgmt-storage-3.1.1.drv', '/nix/store/wbvwarpgp5wjfcl4jrfbabc3jc7r7xa7-python2.7-azure-mgmt-compute-4.4.0.drv' failed

**Comment by AmineChikhaoui** [comment]
The last release (1.7) should fix the first issue.
The manual is still not easy to play with in a nix-shell environment, I just build it `nix-build -A tarball` personally after doing my changes and check the output.
