### ISSUE TITLE
Bastion/Jump host support

### ISSUE THREAD

**Issue by Nekroze** [NixOS/nixops#1150]
Hi, when trying to deploy best practices infrastructure to the cloud, using a small jump/bastion machine being the only machine exposed to the internet is a common pattern. However tooling needs to know how to reach machines behind the jump host, SSH supports this natively these days (`ssh -J`) and so should NixOps.

Personally I want to use this on aws resources however it should be an option for all deployments over SSH.

**Comment by aij** [comment]
Does it still work if you configure it in `~/.ssh/config`? That worked when I needed it last, but things may have changed since then.

(And I realize that's probably not very convenient in general.)

**Comment by Nekroze** [comment]
I'll have to give that a go, it is this week I will be needing to use this so i will have some time to test various work around for suitability throughout the week. However, that does not really help if nixops is the one creating the jumpbox so there is no ahead of time information (without creating resources I would rather not like a route53 just for this) to configure with.

If there is not a suitable work around I will look at how the python code handles the ssh connection and see if I can make PR for this feature my self... time permitting.
