### ISSUE TITLE
why data.nix has this many conventions ?

### ISSUE THREAD

**Issue by teto** [NixOS/nixops#1196]
trying to run the new version with nixops-libvirtd. I can't run update-all because I need to pass a github token :s 
so I edited the data.nix manually, first tried to fetch from https://github.com/nix-community/nixops-libvirtd based on revision but seems like it works only on tags ? so I forked it, pushed a tag and finally it worked. Why make it so complex instead of using the traditional fetchurl/fetchFromGithub ?

NB: and I forgot that the tags must start with a "v"

**Comment by grahamc** [comment]
nixops doesn't use data.nix for plugins anymore
