### ISSUE TITLE
Reload nginx configuration

### ISSUE THREAD

**Issue by joakimgo** [NixOS/nixops#1205]
Currently when the configuration file for nginx is changed it will trigger a restart of nginx. This is not always desired in production system. A better approach would be to gracefully change to the new configuration by sending `SIGHUP` signal to the process as describe in http://nginx.org/en/docs/control.html. 

How would one go about preventing nixops from restarting the service and instead send the `SIGHUP` signal when configuration file has changed?

**Comment by Infinisil** [comment]
Since https://github.com/NixOS/nixpkgs/pull/57429 you should be able to do `services.nginx.enableReload = true` to get that
