### ISSUE TITLE
Security groups on AWS

### ISSUE THREAD

**Issue by tbenst** [NixOS/nixops#1209]
I see on the [NixOps manual](https://nixos.org/nixops/manual/#sec-deploying-to-ec2) that we need to explicitly allow ssh access, and as I read the manual this means adding `deployment.ec2.securityGroups = [ "allow-ssh" "allow-http" ];`. However this gives:

```
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidGroup.NotFound</Code><Message>The security groups 'allow-http', 'allow-ssh' do not exist</Message></Error></Errors><RequestID>022dfc6c-0969-4b68-8a49-208ba6ed85ba</RequestID></Response>
```

Am I missing something for creating the security groups? Also, I'm confused as to why I cannot find the source code for `3.3. Deploying to Amazon EC2` in the nixops github repo--where is this located?

Thanks!

**Comment by tewfik-ghariani** [comment]
Hello,

Using the `securityGroups` attribute that way means that you will be using already existing security groups.

However, if you would like to create a new SG resource as part of the nixops _deploy_ operation, you'll have to define your own rules, name, description similarly to this

```
      resources.ec2SecurityGroups.mygroup = {
        accessKeyId = "myaccesskeyid";
        region = "eu-central-1";
        name = "mygroup";
        description = "mygroup";
        rules = [
          { fromPort = 22; toPort = 22; sourceIp = "0.0.0.0/0"; }
          { fromPort = 80; toPort = 80; sourceIp = "0.0.0.0/0"; }
        ];
      };
```


Regarding he AWS source code, it has been separated into its own 'plugin' github repo as a result of the recent plugins re-structuring : https://github.com/NixOS/nixops/pull/1179

The repo used is : https://github.com/NixOS/nixops-aws

**Comment by tbenst** [comment]
Ah, Thanks @tewfik-ghariani!
