### ISSUE TITLE
Unable to resolve breaking changes in ACME

### ISSUE THREAD

**Issue by turboMaCk** [NixOS/nixops#1231]
After [ACME changes in nixpkgs](https://github.com/NixOS/nixpkgs/pull/77578) I get these errors in nixops deployment:

```
- You must define `security.acme.certs.<name>.email` or
`security.acme.email` to register with the CA.

- You must accept the CA's terms of service before using
the ACME module by setting `security.acme.acceptTerms`
to `true`. For Let's Encrypt's ToS see https://letsencrypt.org/repository/
```

This can be fixed by adding following to configuration:

```
  security.acme = {
    acceptTerms = true;
    email = "foo@bar.baz";
  };
```
However if I do so I get `could not connect to ‘root@security’` log after which retries time outs and deployment fails.

I'm using digital ocean backend. Deployment to VB which doesn't use ACME works.

What is the upgrade path for this issue?

**Comment by bhipple** [comment]
I just went through this today, and the two options you used just worked for me.  I have a fresh cert from certbot issued today.

I'm using the 20.03 beta on AWS.

**Comment by turboMaCk** [comment]
I just tried with updated system from nixos-unstable and I still get the same issue. I think I might need to go with fresh deployment unless there will be some better suggestion.

**Comment by turboMaCk** [comment]
This issue persists even when I attempt to deploy new machine. All I get is loop of these errors until the it timeouts when deploying with `security.acme`.

```
security.....> could not connect to ‘root@security’, retrying in 2 seconds...
ssh: Could not resolve hostname security: Name or service not known
```

**Comment by turboMaCk** [comment]
This seems to be outdated at this point. I've solved it by waiting for updates and pinning known version of nixpkgs to use with nixops.
