### ISSUE TITLE
Plugin instructions do not build if plugin is not python3 compatible

### ISSUE THREAD

**Issue by bhipple** [NixOS/nixops#1258]
`nixops` on the master branch has moved to python3, which means a command like this will fail if the selected plugins have not all moved to python3:

```
$ ./dev-shell --arg p "(p: [ p.aws (p.callPackage ../nixops-gce/release.nix {})])"
```

WORKAROUNDS:

A. In `nixops` and all local plugins you're using, checkout the `pre-python3` branch, then build as normal.

B. Port the plugin to python3.  All plugins should be ported before the next release, so help is appreciated here!  For inspiration/tips/tools, see the sequence of PRs for [porting the nixops-aws plugin](https://github.com/NixOS/nixops-aws/issues/29).

**Comment by tewfik-ghariani** [comment]
Same for dev-shell :/

`$ pushd /home/deploy-ops/src/nixops_new; ./dev-shell --arg p "(p: [ p.aws (p.callPackage ../nixops-gce/release.nix {})])" -I nixpkgs=channel:nixos-19.09 
~/src/nixops_new ~/src
trace: Using plugins: []
Sourcing python-catch-conflicts-hook.sh
Sourcing python-remove-bin-bytecode-hook.sh
Sourcing setuptools-build-hook
Using setuptoolsBuildPhase
Sourcing pip-install-hook
Using pipInstallPhase
Sourcing python-imports-check-hook.sh
Using pythonImportsCheckPhase
Sourcing setuptools-check-hook
Using setuptoolsCheckPhase

[nix-shell:~/src/nixops_new]$ nixops list
skipping deployment ‘02a561e1-c007-11e8-b864-0a29f7962a18’: unknown resource type ‘ec2-security-group’
skipping deployment ‘dea6519e-c0c9-11e8-a681-0a29f7962a18’: unknown resource type ‘ec2-security-group’
skipping deployment ‘53925c97-c27a-11e8-aeed-0a29f7962a18’: unknown resource type ‘ec2-security-group’
skipping deployment ‘b0c9d414-d87a-11e8-9635-0a29f7962a18’: unknown resource type ‘gce’
skipping deployment ‘a1eca7c7-9283-11e9-934f-0a29f7962a18’: unknown resource type ‘ec2’
`

Can someone take a look at this please?

**Comment by tewfik-ghariani** [comment]
@bhipple  Actually @AmineChikhaoui pointed out that this is due to the migration of "nixops" codebase to python3 while the plugins are still behind.

To work around that, it is possible to switch to "[pre-python3](https://github.com/NixOS/nixops/tree/pre-python3)" branch.

```
$ git checkout pre-python3
Branch pre-python3 set up to track remote branch pre-python3 from origin.
Switched to a new branch 'pre-python3'
```
```
$ ./dev-shell --arg p "(p: [ p.aws (p.callPackage ../nixops-gce/release.nix {})])" -I nixpkgs=channel:nixos-19.09
trace: Using plugins: ["/nix/store/3jvdd81nv8a8hirhs7avnxnq6vbbcbm3-nixops-aws-1.7pre0_abcdef","/nix/store/d3lkr871mpdqvcpcj1h6mmw4ms4g5x5k-nixops-gce"]

```

**Comment by bhipple** [comment]
I have updated the PR description to accurately describe what is actually going on here, and also added workarounds.

Related to this, we now have a working python3 version of nixops-aws as of https://github.com/NixOS/nixops-aws/pull/37. If you use nixops-aws, please give it a try!

**Comment by domenkozar** [comment]
I managed to build aws on 20.03:

```
nix-build release.nix -A build.x86_64-linux --arg p "p: [ (p.callPackage ../nixops-aws/release.nix {}) ]"
```

**Comment by tewfik-ghariani** [comment]
All plugins have been upgraded to python3 now ^^

Can this be closed?

**Comment by bhipple** [comment]
It looks like all plugins with their instructions have been deleted and the control for how to do this is flipped?  This particular issue is resolved though, so we can close in favor of https://github.com/NixOS/nixops/issues/1324
