### ISSUE TITLE
Specify NIX_PATH / nixpkgs from within a network's expression itself

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixops#1291]
For now, unclear if we should be able to specify it per-machine, or just within the network.nix. The important part is to support `nix`-style dependency pinning and also patched versions of nixpkgs.

**Comment by lovesegfault** [comment]
Semi-related: what's the correct way to specify the the architecture, "system," of each machine? Thinking about networks with both AArch64 and x86_64.

**Comment by adisbladis** [comment]
Fixed by the addition of flake support & it's non-flake counterpart in https://github.com/NixOS/nixops/pull/1369.
