### ISSUE TITLE
Drop `encryptedLinksTo` support.

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixops#1293]
`encryptedLinksTo` is implemented with SSH tunnels. It would be preferable to make this behavior pluggable so users could make it work with wireguard or whatever instead. Implemented by #1271.

**Comment by adisbladis** [comment]
It would be valuable to bring back support for encrypted links via a plugin.

**Comment by grahamc** [comment]
See #1294

**Comment by pvgoran** [comment]
So it was just removed without a replacement, and those who rely on this feature will now have unusable systems?

**Comment by grahamc** [comment]
Right. NixOps 2 will probably not be out for a bit, and 1.7 should stay available for a good while. If you could help with #1294, that would be really helpful!

**Comment by grahamc** [comment]
Thank you @pvgoran, that is good to know. I've marked #1294 as a blocker to make sure we do it before 2.0 becomes a thing.
