### ISSUE TITLE
Create a plugin version of `encryptedLinksTo`

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixops#1294]
This plugin should probably replicate the original behavior, but will hopefully provide the hooks and primitives for users to implement a similar plugin with wireguard.

**Comment by adisbladis** [comment]
https://github.com/adisbladis/nixops-encrypted-links 
It requires this branch of NixOps: https://github.com/adisbladis/nixops/tree/plugin-hooks

**Comment by adisbladis** [comment]
This PR adds the hooks required for the plugin: https://github.com/NixOS/nixops/pull/1318.

**Comment by adisbladis** [comment]
The encrypted links plugin is now living at https://github.com/nix-community/nixops-encrypted-links and all required hooks are on master.
