### ISSUE TITLE
The README needs some improvements

### ISSUE THREAD

**Issue by gilligan** [NixOS/nixops#1304]
I think the current state of the README is not ideal. Here are some thoughts on that:

- Whom is the README for? If you land on the nixops page as someone who hasn't already used nixops it doesn't provide a lot of useful information to understand what nixops even is.
- The README links to external resources but it would be great to have some more actual content in the README itself. In fact I think it would be great if the documentation was fully self-contained in this repository
- I don't think the _Issue Tracker_ is helping anyone. Anyone who has used GitHub before is able to locate the _Issues_ tab
- The mailing list link is not valid anymore.
- Building from source has broken markdown syntax (missing closing `)
- The snippet about adding nixops as buildInput seems completely arbitrary and out of place in the README

**Comment by grahamc** [comment]
Ithink this is solved by #1308.
