### ISSUE TITLE
Last manual lacking plugins documentation ?

### ISSUE THREAD

**Issue by JosephLucas** [NixOS/nixops#1315]
Last manual version
https://nixos.org/nixops/manual/ 
points to 
https://hydra.nixos.org/build/115931128/download/1/manual/manual.html
This Version 1.8pre seems to lack all NixOps documentation of plugins.

Previous documentation version (1.7) had more info
https://releases.nixos.org/nixops/nixops-1.7/manual/manual.html

**Comment by grahamc** [comment]
Right. NixOps 2.0 (called 1.8 in the code -- oops) is changing a good bit about the plugin infrastructure. Best bet for now is to stick to 1.7 for production use. There is also some info in docs/plugins about authoring plugins. For release, we'll have each plugin document themselves. Sound okay?

**Comment by JosephLucas** [comment]
Are they manual pages generated for the plugins elsewhere ?
I haven't seen visible enough links or warnings about the moving parts of the documentation.
Right now a newcomer like me might be misled about available nixops functionalities.
Removing the last generated manual, for the main nixops functions is an option IMO. Thus newcomers will go straight to github documentations.
