### ISSUE TITLE
Where can I find documentation for 1.7

### ISSUE THREAD

**Issue by turboMaCk** [NixOS/nixops#1357]
Is there any way to find a documentation for nixops 1.7 (shipped with nixos) other than manpages?
The link https://nixos.org/nixops redirects to github repository, readme doesn't have much of any information and master is already 2.x.

**Comment by jhillyerd** [comment]
https://releases.nixos.org/nixops/nixops-1.7/manual/manual.html

**Comment by turboMaCk** [comment]
thanks @jhillyerd
