### ISSUE TITLE
NixOps machines can no longer use `nixpkgs` options or specify overlays after #1369

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixops#1389]
After #1369 overlays are ignored, and also user overlays are always loaded impurely:

See:
* https://github.com/NixOS/nixops/pull/1369/files#diff-7f8400a57a1b63ade4fe16a6154cc092R89
* https://github.com/adisbladis/nixops/blob/9294637ea838d2d9fc27035cadbe0b257ca2ddfb/nix/eval-machine-info.nix#L51

**Comment by cleverca22** [comment]
by default, the `pkgs` in `evalConfig` is null: https://github.com/NixOS/nixpkgs/blob/master/nixos/lib/eval-config.nix

that causes `_module.args.pkgs = lib.mkIf (pkgs_ != null) (lib.mkForce pkgs_);` to NOT `mkForce` the main `pkgs` used by everything
https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/misc/nixpkgs.nix#L58-L64
and if `nixpkgs.pkgs` is also undefined, line 58 will import pkgs, and pass it `nixpkgs.config` + `nixpkgs.overlays`

by passing a `pkgs` to `evalConfig`, you `mkForce` every module to use that exact pkgs tree, ignoring all per-machine overays

but if you instead set `nixpkgs.pkgs` inside a nixos module, line 62 will append `nixpkgs.overlays` to it, so you can get per-machine overlays (but not per-machine config)

and then the purity part: https://github.com/adisbladis/nixops/blob/9294637ea838d2d9fc27035cadbe0b257ca2ddfb/nix/eval-machine-info.nix#L51
the `overlays` and `config` where not set on that master `pkgs` tree, so it will default to loading them from `$HOME`, which will then leak things into whatever you deploy

**Comment by cole-h** [comment]
Slight clarification: It is possible to specify overlays, but not through `nixpkgs.overlays` -- my overlays in `~/.config/nixpkgs/overlays/default.nix` work perfectly fine (maybe what was meant by "user overlays are always loaded impurely").
