### ISSUE TITLE
_destroy_resources method doesn't destroy devices in proper order

### ISSUE THREAD

**Issue by johnalotoski** [NixOS/nixops#1397]
Commit https://github.com/NixOS/nixops/commit/2f757f024906d3a437fc75852dd91912aabe677d reportedly fixes a hanging destroy operation based on commit title (I don't see an issue associated with this, so don't know the details), but it does so by killing the ability of the `_destroy_resources` method to properly order its resource destroy events with `wait()`.

Destroying resources now have no event ordering capability based on dependency, so we have destroy dependency errors we'd expect from this.  See a downstream plugin example of the problem from this commit here: https://github.com/input-output-hk/nixops-packet/issues/22.

This commit should probably be reverted since it breaks what the `_destroy_resource` method is intended to do, and a fix for the original problem should be found in a different way.

I can PR a commit reversion if we agree that's the best way to proceed.  I have verified that reverting the commit resolves the dep ordering destroy errors.

cc: @adisbladis @tewfik-ghariani

**Comment by tewfik-ghariani** [comment]
Reverting that doesn't cause the 'destroy' operation to hang? @johnalotoski

**Comment by johnalotoski** [comment]
Hi @tewfik-ghariani, no, not for the tests I'm doing with nixops packet plugin -- it works properly when reverted, but otherwise throws an error, as expected, the way it is now.  When reverted, it properly recognizes the keyPair resource has machine dependencies and adds a `wait()` to the keyPair destroy resource event so the machines are deleted first, then the keyPair last.

This commit breaks the ability for the `_destroy_resources` method to add a `wait()` to any resources because of the `if dep._created_event:` statement, which will never be true as destroy events are keyed off of `dep._destroyed_event`, and so the ability to add a `wait()` to appropriate resources becomes a no-op.

It looks like another fairly recent commit in the code solved resource destruction deadlock, which was maybe the root cause of the hang you experienced: "Fix deadlock in resource destruction" https://github.com/NixOS/nixops/commit/ffd2712caae642d0ceb3713a51ac5e5334c32c63.

Can you re-test and see if you have the same destroy hang problem with a revert of 2f757f0 and making sure you have a recent enough version to include ffd2712 (probably master of nixops and whatever plugin you are using would be best)?

**Comment by johnalotoski** [comment]
I could see how prior to ffd2712, commit 2f757f0 would have resolved the hang issue at the expense of introducing the ordering/wait() problem which may or may not be visible to an end user depending on what resources are being destroyed and what their dependencies are.

**Comment by tewfik-ghariani** [comment]
@johnalotoski  that makes a lot of sense! I just tested that in nixops-gcp plugin and I confirm your findings

Please feel free to submit a PR upstream

cc @adisbladis

**Comment by johnalotoski** [comment]
Great!  I'll get a PR submitted and linked here probably by later today.  Thanks!
