### ISSUE TITLE
How do I cap the NixOS version?

### ISSUE THREAD

**Issue by hbjydev** [NixOS/nixops#1417]
So I have some servers deployed using NixOps, but I realised I forgot to specify the `system.stateVersion`, so now they've automatically bumped themselves to `21.03`, but I want them to come back down to `20.09`. Can I just add `system.stateVersion` to have them drop that back, or would it be easier to just pin `nixpkgs` and have NixOps use that instead of upstream it?

**Comment by cole-h** [comment]
`stateVersion` does not control the system version, FYI. Your only recourse may be to pin your channel to 20.09.

**Comment by adisbladis** [comment]
Nixops loads nixpkgs from the environment variable `NIX_PATH`, which means that you can pin nixpkgs by setting that env variable before deploying.
