### ISSUE TITLE
NixOps can't deploy to a different system type anymore

### ISSUE THREAD

**Issue by regnat** [NixOS/nixops#1418]
I have a NixOps deployment with several `x86_64-linux` machines and a `aarch64-linux`.
With NixOps 1.7 I could just set `nixpkgs.localSystem` for the aarch64 machine and everything was working fine.

This doesn't work anymore with NixOps 2.0 (I guess for the same reasons than https://github.com/NixOS/nixops/issues/1389), and there's (I think) no way anymore to specify that a machine should have a different `system` than the local one.

The system is set to `builtins.localSystem` in https://github.com/NixOS/nixops/blob/c9fdc936ba7066564993b6b34557c2f0f77f43ab/nix/eval-machine-info.nix#L1 and there's no way to override it (neither per-machine nor globally)

**Comment by maksar** [comment]
There is a trick (thanks to https://github.com/NixOS/nixops/blob/master/nix/eval-machine-info.nix#L51) to deploy from, lets say x86_64-darwin to x86_64-linux:
```
{
  network = {
    description = "...";
    enableRollback = true;
    nixpkgs = (builtins.getFlake "github:NixOS/nixpkgs/release-20.09").legacyPackages."x86_64-linux";
  };
...
```
Or, if you don't want to pin your nixpkgs:
```
{
  network = {
    description = "...";
    enableRollback = true;
    nixpkgs = import <nixpkgs> { system = "x86_64-linux"; };
  };
...
```

**Comment by regnat** [comment]
Thanks for the nice trix @maksar. Unfortunately I don't think that can work for mixing different system tyes in the same deployment :(

**Comment by aaronjanse** [comment]
Sadly that workaround also doesn't work for nixops flakes

**Comment by roberth** [comment]
I'd like to re-wire the network expression using the module system, so we can have proper network-wide options. If I do that, solving this issue is a matter of paying attention.
Using freeform modules I'm confident that we can even retain compatibility with the current format that mixes machines and other options.
Any objections @adisbladis @grahamc @AmineChikhaoui ?

**Comment by regnat** [comment]
I didn't notice that gh didn't mention it there, but this specific issue should actually be closed by https://github.com/NixOS/nixops/pull/1422 that got merged a couple weeks ago

**Comment by adisbladis** [comment]
@roberth I've wanted to do the same so absolutely no objections from me :)
