### ISSUE TITLE
Digital Ocean backend no longer supported?

### ISSUE THREAD

**Issue by livnev** [NixOS/nixops#1442]
When attempting a deployment that had worked on earlier versions of `nixops`, I got:
```
nixops.deployment.UnknownBackend: unknown resource type ‘digitalOcean’
```

Was the `digitalOcean` backend deprecated? I couldn't find mention of it in the release notes or documentation. Also, I couldn't really find any description of using backends [in the new documentation](https://nixops.readthedocs.io/en/latest/index.html).

**Comment by adisbladis** [comment]
The backends have been turned into plugins and live under separate repositories.
The digitalocean one has a new home here https://github.com/nix-community/nixops-digitalocean.

**Comment by livnev** [comment]
@adisbladis Ah thanks, I had no idea.
