### ISSUE TITLE
Libvirtd backend fails to assign IPv4 addr using `macvtap@iface`, throws "waiting for an IP address to appear in DHCP leases"

### ISSUE THREAD

**Issue by sar** [NixOS/nixops#1455]
Libvirtd backend fails to get an IP address after creating `macvtap@eth0` interface, which prevents host direct networking from functioning when using ``<network type="direct">``.

**Error**
```bash
test1 > uploading disk image...
test1 > starting ...
test1 > waiting for IP address to appear in DHCP leases 
................................................................................................................................
.................................................................................................................................
.............................................................................
```

```bash
$ ip addr
eth0....
macvtap0@eth0 
```

**Steps to Reproduce**

Call the commands ``$ nixops create -d test1 test1.nix`` and ``$ nixops deploy -d test1`` using an example configuration adapted from the NixOps [manual](https://releases.nixos.org/nixops/nixops-1.7/manual/manual.html#idm140737322394336).

```nix
{
  network = {
    enableRollback = true;
  };
  test1 = {
    imports = [ configuration.nix ];
    deployments.targetEnv = "libvirtd";
    deployments.libvirtd.headless = true;

    deployments.libvirtd.extraDevicesXML = ''
      <interface type="direct">
        <source dev='eth0' mode='vepa' />
        <model type='virtio' />
      </interface>
    '';
  };
}
```
```nix
# define relevant flags in configuration.nix section of vm

networking.useDHCP = true;
```

**Workarounds**

Deploy a KVM manually using the `virsh` command creates and attaches a `macvtap@iface` with IP address assigned automatically to the dependent KVM.

```bash
$ sudo virsh define test1.xml
$ sudo virsh start test1
Domain 'test1' started
```

**System Information**
```
$ nixops --version
NixOps @version@  # pkgs.nixopsUnstable on nixos 21.05
```

**Notify Maintainers**

NixOps libvirtd backend - @AmineChikhaoui [repo](https://github.com/nix-community/nixops-libvirtd)

**Related Issues**

Related to #500 (no IPv4 address, closed without conclusion) and #929 (using NetworkManager on KVM Host)

**Comment by adisbladis** [comment]
Please report this to the libvirtd backend repo.
