### ISSUE TITLE
extraArgs is deprecated in nixpkgs

### ISSUE THREAD

**Issue by abbradar** [NixOS/nixops#1496]
During any operations with nixops using recent nixpkgs I get:

```
trace: warning: The extraArgs argument to eval-config.nix is deprecated. Please set config._module.args instead.
```

I'm not sure if just moving to `config._module.args` will be compatible with older nixpkgs; we may need to somehow find out which method to use.

**Comment by roberth** [comment]
The possibility of using `config._module.args` has been semi-documented since 2014, https://github.com/NixOS/nixpkgs/commit/0a0a29fd0bb8329b33a0b2bb25627d3b3d9b7368

**Comment by abbradar** [comment]
Indeed, we can just use `_module.args` then. I submitted a PR.
