### ISSUE TITLE
nixops create ... unrecognized arguments

### ISSUE THREAD

**Issue by YuMingLiao** [NixOS/nixops#1540]
nixops create trivial.nix
usage: nixops [-h] [--version] [--pdb] operation ...
nixops: error: unrecognized arguments: trivial.nix

I use nixopsUnstable
nixops --version
NixOps 2.0.0-pre-7220cbd

nix-channel --list
nixos https://nixos.org/channels/nixos-22.05

**Comment by YuMingLiao** [comment]
change back to nixops and it works.

**Comment by rschardt** [comment]
The unstable version looks for a flake.nix or nixops.nix file in the current directory.
Just rename 'trivial.nix' and you should be able to use it.
