### ISSUE TITLE
error: function 'mkPackageOption' called with unexpected argument 'nullable'

### ISSUE THREAD

**Issue by n8henrie** [NixOS/nixops#1561]
After updating to 23.05 (unsure if that's related or just coincidental) I'm no longer able to deploy a configuration due to this error:

```
error: function 'mkPackageOption' called with unexpected argument 'nullable'
error: evaluation of the deployment specification failed
```

The configuration builds locally, so I think it's a nixops error, though hard to be sure.

```
$ nixops --version
NixOps 2.0.0-pre-5013072
```

**Comment by roberth** [comment]
Doesn't seem like a coincidence as `nullable` is a recently added parameter. It appears that NixOS gets evaluated with an old `lib`. What's in your `NIX_PATH`, and what's in your network's `nixpkgs` attribute?

**Comment by n8henrie** [comment]
Arch Linux, no channels configured, (flake based).

All inputs (including `nixpkgs` below) are tied to `release-23.05` -- is that considered an old lib?

Pretty simple config:

```
  nixopsConfigurations.default = {
          inherit nixpkgs;
          network.storage.legacy = {};
          n8remote = {
            imports = [self.nixosModules.n8remote];
            deployment = {
              targetHost = "my.domain.com";
              targetPort = 42;
            };
          };
        };
```

```
$ env | grep NIX_PATH
$
$ nix-channel --list
$ sudo -i nix-channel --list
$ nix run nixpkgs#nix-info -- -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.32-1-lts, Arch Linux, noversion, rolling`
 - multi-user?: `no`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.15.0`
 - channels(root): `""`
 - channels(n8henrie): `"nixpkgs-22.11"`
 - nixpkgs: `not found`
```

**Comment by n8henrie** [comment]
Evaluation succeeds. Now I'm back to being stuck at `copying closure` (https://github.com/NixOS/nixops/issues/1557)
