### ISSUE TITLE
Rackspace support

### ISSUE THREAD

**Issue by thoughtpolice** [NixOS/nixops#168]
I'm currently managing Haskell.org servers (on a Hetzner dedicated server, with servers running inside KVM), and at the moment we're thinking of moving some of our servers to Rackspace since they've provided us with free hosting.*

I would absolutely _kill_ for Rackspace support in NixOps, so we could evaluate moving some of our services over to NixOS as well (in particular, user management on a particular machine would be _greatly_ simplified with NixOS, and will allow us to deploy hardened security infrastructure).

Rackspace runs on OpenStack, and most distros are just run in a traditional VirtIO based setup. They _do_ have an API for disk images, I think, but I don't think you can upload images - only create 'custom images' from 'base' images. But they also have a rescue mode with SSH support, which I believe should be usable as well - similar to the way the Hetzner backend works.

I'm currently looking into how feasible this is using their `pyrax` API, but first I need to get the NixOS virtualisation configuration for Rackspace in place as well.

---
- BTW, I'll entice others: Rackspace offers a special program for open source projects which offers tons of free credit a month to the project - covering all their products, from server resources to their CDN/object storage - only asking for some small public recognition in return, like a public thanks or logo somewhere (I won't give $$$ specifics, but I'm not talking about their monthly $50 dev discount - it is a _lot_ of free money per month, more than enough for dozens of machines for Hydra for example, and test instances for NixOps, should I finish this ticket.)
  
  If anyone who's officially associated with nixos.org is interested in this, please contact me (email on my GitHub page) - I'll put you in direct contact with the individual who represents me and haskell.org, and he's a super awesome and swell guy who'll get you up and running in minutes. (Then you can dogfood with me to get this working...)

**Comment by domenkozar** [comment]
@thoughtpolice I hear based on your podcast that this is the major blocker for porting haskell infrastructure to nixos? @Phreedom what's your level of effort estimate?

**Comment by Phreedom** [comment]
Based purely on the other backends, 2.5 weeks. ~1 week to create a polished 
bootable nixos image with agents, config options and such. And roughly 1-1.5 
week to implement basic machine, disks and networking support.

This kind of work is most likely going to be dominated not by coding, but by 
reading docs, packaging stuff, working around quirks and looking for ways to 
get (usually quite ugly) stuff interoperating with nixos in a way that's more 
or less seamless to the user.

**Comment by domenkozar** [comment]
I have packaged OpenStack for NixOS and the best thing I can say is: it's terrible.

I'd suggest using libcloud if we can get that rolling since we're already using it.

**Comment by Phreedom** [comment]
You can never tell in advance if that's a good idea. libcloud could be quite broken and incomplete or could use older API version or or or... Everytime I added support for something, I ended up patching both the agent and the client lib :)

**Comment by domenkozar** [comment]
@thoughtpolice I think rackspace since abandoned open source sponsoring program?

**Comment by grahamc** [comment]
NixOps supports backends as plugins, so closing this. A plugin could be made :)
