### ISSUE TITLE
Route53 options should allow for multiple DNS entries for a single machine

### ISSUE THREAD

**Issue by ocharles** [NixOS/nixops#174]
We would like to use nginx with a few different virtual hosts on a single EC2 instance, but we have to manage these DNS entries outside of NixOps. It would be better if we could simply provide a list of DNS entries for a machine.

**Comment by domenkozar** [comment]
Relevant to https://github.com/NixOS/nixops/issues/527

**Comment by ocharles** [comment]
I think this has been fixed by https://github.com/NixOS/nixops/pull/832
