### ISSUE TITLE
Add support for nixos-install backend

### ISSUE THREAD

**Issue by offlinehacker** [NixOS/nixops#175]
So idea is:
- you put in install cd into your phyisical server
- you boot and get it's ip/hostname
- you run nixops and server gets deployed

I know i can make custom cd with post boot commands that would do exactly the same, but this requires having custom cd.

NOTE: This is somehow related to nixos-assimilate idea from @aszlig

**Comment by domenkozar** [comment]
Following method allows to parition drives: https://github.com/cleverca22/nix-tests/tree/master/kexec

**Comment by grahamc** [comment]
NixOps supports backends as plugins, so closing this. A plugin could be made :)
