### ISSUE TITLE
Cannot deploy virtuablox headless nodes

### ISSUE THREAD

**Issue by maggesi** [NixOS/nixops#176]
Hi, there seems to be again a problem with nixops with virtualbox headless nodes.

$ nixops deploy -d minicloud
webserver> creating VirtualBox VM...
webserver> Virtual machine 'nixops-24856f59-ba5b-11e3-a2e6-2d15dd5fa0ff-webserver' is created and registered.
webserver> UUID: d6ea884c-3173-4e12-bada-aeff1112c39c
webserver> Settings file: '/home/maggesi/VirtualBox VMs/nixops-24856f59-ba5b-11e3-a2e6-2d15dd5fa0ff-webserver/nixops-24856f59-ba5b-11e3-a2e6-2d15dd5fa0ff-webserver.vbox'

webserver> creating disk ‘disk1’...
webserver> 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
webserver> Clone hard disk created in format 'VDI'. UUID: ad027933-92f8-4655-8f63-a3bf582122b8

webserver> attaching disk ‘disk1’...
webserver> VBoxManage: error: The virtual machine 'nixops-24856f59-ba5b-11e3-a2e6-2d15dd5fa0ff-webserver' has terminated unexpectedly during startup with exit code 1

webserver> VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component Machine, interface IMachine
webserver> Waiting for VM "nixops-24856f59-ba5b-11e3-a2e6-2d15dd5fa0ff-webserver" to power on...

webserver> waiting for IP address...........

Can you test and confirm the problem.

My setup:
# nix-channel --list

nixops http://hydra.nixos.org/project/nixops/channel/latest
nixos http://nixos.org/channels/nixos-unstable

**Comment by necrophcodr** [comment]
I have this issue on Ubuntu 14.04.3 running Nix using `proot` as described here: https://nixos.org/wiki/How_to_install_nix_in_home_%28on_another_distribution%29#PRoot_Installation

I've then added the latest Nixops channel: http://hydra.nixos.org/project/nixops/channel/latest

Then I've created two .nix files following this: http://nixos.org/nixops/manual/#idm140737319351408

Attempting to deploy, the following error follows:

    sandbox@sandbox:~/tmp$ nixops deploy -d web
    webserver> creating VirtualBox VM...
    webserver> Virtual machine 'nixops-33a811a6-9770-11e5-96d8-56847afe9799-webserver' is created and registered.
    webserver> UUID: e07097c1-7906-42f6-8d2a-1f468d800274
    webserver> Settings file: '/home/sandbox/VirtualBox VMs/nixops-33a811a6-9770-11e5-96d8-56847afe9799-webserver/nixops-33a811a6-9770-11e5-96d8-56847afe9799-webserver.vbox'
    webserver> creating disk ‘disk1’...
    webserver> 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
    webserver> Clone hard disk created in format 'VDI'. UUID: 917738ae-d886-4b51-ae44-a8e769eb93f7
    webserver> attaching disk ‘disk1’...
    webserver> Waiting for VM "nixops-33a811a6-9770-11e5-96d8-56847afe9799-webserver" to power on...
    webserver> VM "nixops-33a811a6-9770-11e5-96d8-56847afe9799-webserver" has been successfully started.
    error: command ‘['VBoxManage', 'startvm', u'nixops-33a811a6-9770-11e5-96d8-56847afe9799-webserver']’ failed on machine ‘webserver’ (exit code 1)

**Comment by necrophcodr** [comment]
Some further output:

    sandbox@sandbox:~/tmp$ nix-env --version
    nix-env (Nix) 1.10

    sandbox@sandbox:~/tmp$ nixops --version
    NixOps 1.3.1pre1657_8f61177

**Comment by rbvermaa** [comment]
What VirtualBox version? Can you start up VM's in VirtualBox outside of nixops?

**Comment by necrophcodr** [comment]
I'll install vagrant in a moment and have a look.

    sandbox@sandbox:~/tmp$ VBoxManage --version
    4.3.34_Ubuntur104062

**Comment by rbvermaa** [comment]
According to 1.3 release notes: VirtualBox 5.0 is required for the VirtualBox backend.

**Comment by necrophcodr** [comment]
After a long hurdle of hoops, it turns out I've probably been wrong. Now I'll have to nag Oracle and the VBox community, due to being unable to start virtual machines. Appologies for almost reviving this issue entirely.

**Comment by necrophcodr** [comment]
I've gotten vagrant to work just fine, but NixOps still doesn't deploy the VM with the previously mentioned error.

It would seem, that it would be required to pass `--type headless` to the virtual machine for it to start in a headless session. Note that this is a standalone server with no VGA-like interface connected.

**Comment by rbvermaa** [comment]
Are you using VirtualBox 5.x now?

**Comment by necrophcodr** [comment]
> sandbox@sandbox:~/tmp$ nixops --version
> NixOps 1.3.1pre1657_8f61177
> sandbox@sandbox:~/tmp$ nix-env --version
> nix-env (Nix) 1.10
> sandbox@sandbox:~/tmp$ VBoxManage --version
> 5.0.10r104061

There we go. That is the current versions of everything.

Running the following works:

> vagrant init ubuntu/trusty64
> vagrant up
> vagrant ssh

But doing the same as specified before with NixOps, does not.

**Comment by necrophcodr** [comment]
I did also stop, delete, and destroy the NixOps instances.

**Comment by rbvermaa** [comment]
Could you run

    $  VBoxManage startvm nixops-33a811a6-9770-11e5-96d8-56847afe9799-webserver

and post the output here?

**Comment by necrophcodr** [comment]
> sandbox@sandbox:~/tmp$ nixops list
> +--------------------------------------+------+-------------+------------+------------+
> | UUID                                 | Name | Description | # Machines |    Type    |
> +--------------------------------------+------+-------------+------------+------------+
> | 8091502b-9830-11e5-bdce-0242d6d54c48 | web  | Web server  |          1 | virtualbox |
> +--------------------------------------+------+-------------+------------+------------+
> sandbox@sandbox:~/tmp$ VBoxManage startvm nixops-33a811a6-9770-11e5-96d8-56847afe9799-webserver
> VBoxManage: error: Could not find a registered machine named 'nixops-33a811a6-9770-11e5-96d8-56847afe9799-webserver'
> VBoxManage: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBoxWrap, interface IVirtualBox, callee nsISupports
> VBoxManage: error: Context: "FindMachine(Bstr(pszVM).raw(), machine.asOutParam())" at line 572 of file VBoxManageMisc.cpp

Some output for you here.

**Comment by rbvermaa** [comment]
Ah you deleted and recreated the deployment, which changed the uuid. Can you run:

     $ VBoxManage startvm nixops-8091502b-9830-11e5-bdce-0242d6d54c48-webserver

**Comment by necrophcodr** [comment]
sandbox@sandbox:~/tmp$ VBoxManage startvm nixops-8091502b-9830-11e5-bdce-0242d6d54c48-webserver
    Waiting for VM "nixops-8091502b-9830-11e5-bdce-0242d6d54c48-webserver" to power on...
    VM "nixops-8091502b-9830-11e5-bdce-0242d6d54c48-webserver" has been successfully started.
    sandbox@sandbox:~/tmp$ VBoxManage list vms
    "tmp_default_1448895032567_66009" {3b5948c3-2e67-4e35-a048-840d618f22a8}
    "nixops-8091502b-9830-11e5-bdce-0242d6d54c48-webserver" {11e4939b-b9c5-44e9-a255-27ad8d1f97f7}
    sandbox@sandbox:~/tmp$ VBoxManage list runningvms

That's all the output. The last command doesn't output anything.

**Comment by rbvermaa** [comment]
Could you check the exit code of the first command (startvm). This seems really weird...

**Comment by necrophcodr** [comment]
sandbox@sandbox:~/tmp$ VBoxManage startvm nixops-8091502b-9830-11e5-bdce-0242d6d54c48-webserver; echo $?
    Waiting for VM "nixops-8091502b-9830-11e5-bdce-0242d6d54c48-webserver" to power on...
    VM "nixops-8091502b-9830-11e5-bdce-0242d6d54c48-webserver" has been successfully started.
    1

It is pretty odd too.

**Comment by domenkozar** [comment]
I'm seeing the same on a server running `15.09.753.18f1e6a (Dingo)`

**Comment by IreneKnapp** [comment]
I am also seeing this, with a NixOS host.

```
$ nixos-version
16.03pre73316.93d8671 (Emu)

$ nix-env --version
nix-env (Nix) 1.10

$ nixops --version
NixOps 1.3

$ VBoxManage --version
5.0.10_OSEr104061

$ nixops deploy -d virtualbox
frontend> Waiting for VM "nixops-c91c246b-ad09-11e5-af21-fcaa14de5f08-frontend" to power on...
frontend> VM "nixops-c91c246b-ad09-11e5-af21-fcaa14de5f08-frontend" has been successfully started.
error: command â['VBoxManage', 'startvm', u'nixops-c91c246b-ad09-11e5-af21-fcaa14de5f08-frontend', '--type', 'headless']â failed on machine âfrontendâ (exit code 1)

$ VBoxManage startvm nixops-c91c246b-ad09-11e5-af21-fcaa14de5f08-frontend --type headless
Waiting for VM "nixops-c91c246b-ad09-11e5-af21-fcaa14de5f08-frontend" to power on...
VM "nixops-c91c246b-ad09-11e5-af21-fcaa14de5f08-frontend" has been successfully started.

$ echo $?
1

$ VBoxManage list runningvms

$
```

I'm going to search around and see what I can find upstream, and report back if there's anything useful.  I haven't tried building an equivalent machine with Vagrant, as the original reporter has, but I'm going to proceed on the assumption the VM isn't configured properly somehow.

**Comment by IreneKnapp** [comment]
I had to put in `virtualisation.virtualbox.host.addNetworkInterface = true;`.  I then needed to do a full reboot of the host, since that didn't work by itself.

**Comment by domenkozar** [comment]
For reference, this error appears if there is no `$DISPLAY`. See https://www.virtualbox.org/ticket/7367

**Comment by IreneKnapp** [comment]
From the upstream bug, it looks as though this issue still occurs, and can be worked around by adding `--type headless` to the VBoxManage invocation. The proposed upstream solution at the moment is just a better error message, so it seems like NixOps should change the invocation.

I'll try to verify tonight that I can still reproduce this, and will reopen if so.

**Comment by domenkozar** [comment]
@IreneKnapp but in this case it doesn't run in headless mode and it doesn't have a display.

**Comment by IreneKnapp** [comment]
I guess I didn't think about that, but why isn't NixOps trying to run the VM in headless mode? That was what I expected it to do - I'm under the impression it's meant primarily for building servers, not desktop machines.
