### ISSUE TITLE
Deployment (OS X / VirtualBox) fails with "failed with exit code 100"

### ISSUE THREAD

**Issue by benmos** [NixOS/nixops#184]
This commit: https://github.com/NixOS/nixops/commit/a2718b65615ec4a71a0f819db5fa675632e62f34 switched from DSA to EC DSA.

This seems to not work on OS X (10.8.5):
```
bash-3.2$ ssh-keygen -t ecdsa -f fredkey -N '' -C "NixOps auto-generated key"
unknown key type ecdsa
bash-3.2$  
```

...when I locally reverted this change I was then able to get NixOps to work.

**Comment by aszlig** [comment]
@benmos: Does this issue still persist?

**Comment by benmos** [comment]
@aszlig: I'm not sure to be honest - this occurred when I was just running through the NixOps tutorials quite some time ago. For actual, real-world usage I switched from running under OS X to running on NixOS inside a VirtualBox image. I've certainly not seen it since - but I'm not sure how much you can read into that.

**Comment by aszlig** [comment]
@benmos: Okay, closing then, please reopen if you encounter the problem again.
