### ISSUE TITLE
Ebs-backed EC2 instances with resized root volumes are not restartable

### ISSUE THREAD

**Issue by zopa** [NixOS/nixops#186]
When the size of the file system for the machine image given by `deployment.ec2.ami` differs from the size specified by `deployment.ec2.ebsInitialRootDiskSize`, nixops will happily resize the root file system. But although the resulting machine appears to run just fine, after stopping and restarting I get errors like:

```
Error 5: Partition table invalid or corrupt
```

in the machine console output. The restarted machine is unreachable via ssh, of course.

Here's a network specification to reproduce the issue (at a cost of ~ 20 cents):

Logical:

```
{
  network.description = "Test case for EBS-backed EC2 root file system resizing";

  server =
    { config, pkgs, ... }:

      { services.postgresql = {
        enable = true;
        dataDir = "/var/db/postgresql";
        package = pkgs.postgresql93;
        port = 5432;
      };

      networking.firewall.allowedTCPPorts = [ 80 ];
    };
}
```

Physical:

```
let

  region      = "us-east-1";
  accessKeyId = "dev";

in
{ server =
    { resources, ... }:
    { deployment = { 
        targetEnv = "ec2";
        ec2 = {
          inherit accessKeyId region;

          # Public NixOs 13.10 EBS ami
          ami = "ami-5bc39832";

          instanceType = "m3.large";
          ebsBoot      = true;
          ebsInitialRootDiskSize = 500;
          keyPair      = resources.ec2KeyPairs.test-key-pair;
          securityGroups = [ "default" ];
        };
      };
    };

  resources.ec2KeyPairs.test-key-pair =
    { inherit region accessKeyId; };

}
```

**Comment by benmos** [comment]
If anyone has any more info about the underlying problem here, I'd be very grateful. e.g. Was this a nixops bug that was fixed or not? What can cause this behaviour?

(I've just encountered this myself and am starting to investigate...)

**Comment by rbvermaa** [comment]
This was not a bug. As far as I know ami-5bc39832 is not a HVM image, but a pvgrub image, so using this with m3.large, is not supposed to work as far as I know. 

In general I would not use deployment.ec2.ami, unless you know what you are doing. It is mainly used for internal purposes (different instance types / regions need different ami's), even though the option can be leveraged to allow custom built images as base for your deployments, e.g. when you do not want to use the officially supported NixOS/nixops images.

@benmos can you create an issue with your exact config, so we can see if we can help you?

**Comment by benmos** [comment]
@rbvermaa Thanks for the fast response! 

_"can you create an issue with your exact config"_ <<< I'm not sure how easy that will be as there is quite a bit of stuff in my deployment. If I do get bogged down though, I'll try and go this route and aim to find a smaller reproducible scenario.

In my case, I'm not using "deployment.ec2.ami", but I have two suspicions about things that I might have done wrongly:
1) I did a manual "reboot" of one of the EC2 VMs whilst logged into it, followed by various attempts at using "nixops reboot", obviously to no avail.
2) (and maybe this is the underlying cause) I may have run a deployment using an out-of-date version of NixOps (specifically the nixops-1.2 which is in <nixpkgs> and I believe has old AMIs listed in it)... (normally I run a more-recent nixops).

I wonder if (2) could be the source of my problem...

**Comment by rbvermaa** [comment]
@benmos a config with just the deployment.* options should be sufficient, I think. I'll try to reproduce the issue then.

**Comment by benmos** [comment]
Ok. Here's the file with all the `deployment.*` bits in it:

```nix

{ envClass,
  envName,
  region,
  stealEIPs ? false,
  accessKeyId # eg "borders-ben" - symbolic name looked up in ~/.ec2-keys
}:
let
  lib = (import <nixpkgs> {}).lib; # for utility fns like 'recursiveUpdate'
  env = envClass + "-" + envName;
  ec2 = { resources, ... }:
    { deployment.targetEnv          = "ec2";
      deployment.ec2.accessKeyId    = accessKeyId;
      deployment.ec2.region         = region;
      # deployment.ec2.zone           = zone;
      deployment.ec2.instanceType   = "m3.medium";
      deployment.ec2.keyPair        = resources.ec2KeyPairs.my-key-pair;
      deployment.ec2.securityGroups = [ "borders-dev-eu" ];
      deployment.owners             = [ "xxx@xxx" "yyy@yyy" ];
      deployment.ec2.instanceProfile = resources.iamRoles.bordersInstance.name;
    };

  # NB don't use underscores in bucket names as they only work in S3 US Region
  s3dataBucket = "borde-rs-${env}-data-backups";
  s3imgsBucket = "borde-rs-${env}-images-backups";

  s3PolicyStrFor = bucket: ''
    {
       "Statement": [
          {
             "Effect": "Allow",
             "Principal": {
                "AWS": "*"
             },
             "Action": "s3:PutObject",
             "Resource":"arn:aws:s3:::${bucket}/*"
          }
       ]
    }
  '';

in
{
  resources.iamRoles.bordersInstance = {
      accessKeyId = accessKeyId;
      name = "bordersinstance";
      policy = ''
        {
          "Statement": [
            {
              "Action": [
                "cloudwatch:GetMetricStatistics",
                "cloudwatch:ListMetrics",
                "cloudwatch:PutMetricData",
                "ec2:DescribeTags"
              ],
              "Effect": "Allow",
              "Resource": "*"
            }
          ]
        }
        '';
  };

  resources.s3Buckets.dataBakS3 = {
      accessKeyId = accessKeyId;
      name        = s3dataBucket;
      region      = region;
      policy      = s3PolicyStrFor s3dataBucket;
  };
  resources.s3Buckets.imageBakS3 = {
      accessKeyId = accessKeyId;
      name        = s3imgsBucket;
      region      = region;
      policy      = s3PolicyStrFor s3imgsBucket;
  };

  # resources.ebsVolumes.deleteme =
  #   { name = "DeleteMe Data";
  #     region = "eu-west-1";
  #     zone = "eu-west-1a";
  #     accessKeyId = accessKeyId;
  #     size = 1; # in GB
  #   };

  automation = xs@{ config, resources, ... }:
    lib.recursiveUpdate (ec2 xs) {
      deployment.ec2.ebsInitialRootDiskSize = 30;
      deployment.ec2.tags                   = { env = env; Name = env + "-automation"; };
      # deployment.route53.hostName           = env + "-automation" + ".borde.rs";
      # deployment.route53.accessKeyId        = accessKeyId;
      # deployment.ec2.associatePublicIpAddress = false; 
      deployment.ec2.elasticIPv4            = if stealEIPs then config.borders.autoServerEIP else "";
      };

  appserver  = xs@{ config, resources, ... }:
    lib.recursiveUpdate (ec2 xs) {
      deployment.ec2.ebsInitialRootDiskSize = 50;
      deployment.ec2.tags                   = { env = env; Name = env + "-app-server"; };
      # deployment.route53.hostName           = env + "-app-server" + ".borde.rs";
      # deployment.route53.accessKeyId        = accessKeyId;

      # deployment.ec2.associatePublicIpAddress = true; # TODO
      deployment.ec2.elasticIPv4          = if stealEIPs then config.borders.appServerEIP else "";

      fileSystems."/data" =
        { autoFormat = true; # "If the device does not currently contain a filesystem (as
			     # determined by blkid), then automatically format it with the
			     # filesystem type specified in fsType. Use with caution."
          device = "/dev/xvdf";
          fsType = "xfs";
	  # ec2.fsType = "xfs";
          ec2.size = 2; # in GB
          ec2.deleteOnTermination = true;
        };

      fileSystems."/images" =
        { autoFormat = true;
          device = "/dev/xvdg";
          fsType = "xfs";
	  # ec2.fsType = "xfs";
          ec2.size = 6; # in GB
          ec2.deleteOnTermination = true;
        };
     };


 # Provision an EC2 key pair.
  resources.ec2KeyPairs.my-key-pair =
    { inherit region accessKeyId; };
}
```

**Comment by rbvermaa** [comment]
I'll try to reproduce your issue later today.

**Comment by benmos** [comment]
Thx!

In case it's relevant, we're using **eu-west-1**.

**Comment by benmos** [comment]
The other thing that I should record is that it turns out that the two VMs in this deployment (which both have the same problems) are actually running on `ami-f703e180` - (i.e. "nixos-13.10.35442.b77a2cd (Aardvark)-x86_64-ebs" - which is from the `<nixpkgs>` **nixops**) whereas I had thought that they were running on a **14.04** image.

**Comment by rbvermaa** [comment]
That is likely because you deployed with nixops 1.2 originally, as 14.04 wasn't released yet back when 1.2 was released.

**Comment by benmos** [comment]
Sounds likely.

Also of possible relevance is that we originally ran these VMs as **m1.small** and then upgraded to **m3.medium** ... and I note that this would change the value of `isEc2Hvm` from _false_ to _true_:

```nix
  isEc2Hvm =
      cfg.instanceType == "cc1.4xlarge"
   || cfg.instanceType == "cc2.8xlarge"
   || cfg.instanceType == "hs1.8xlarge"
   || cfg.instanceType == "cr1.8xlarge"
   || builtins.substring 0 2 cfg.instanceType == "i2"
   || builtins.substring 0 2 cfg.instanceType == "c3"
   || builtins.substring 0 2 cfg.instanceType == "c4"
   || builtins.substring 0 2 cfg.instanceType == "r3"
   || builtins.substring 0 2 cfg.instanceType == "m3";
```

**Comment by rbvermaa** [comment]
Yes, that is likely the problem. Have to think if this can be easily prevented somehow.

**Comment by rbvermaa** [comment]
Btw, take care when destroying your network, if you want to keep the S3 buckets and files (did that accidentally the other day). I will push an s3bucket option to allow keeping the bucket+data for the cases where you want to keep the data.

**Comment by benmos** [comment]
Thanks, will do.

Fortunately this is just our Dev environment.  Less fortunately our production environment will be in the same state (because we also did the **m1.small** --> **m3.medium** upgrade there too ...). 

So I guess our Prod environment has a bit of a ticking time-bomb in it...

If you have any advice for how best to get our Prod environment to a safer state, so that it doesn't risk the same fate as our Dev environment, I'd be very grateful.

**Comment by rbvermaa** [comment]
First of all make sure to backup your networks. This can be easily done using 'nixops backup', which will make EBS snapshots of all the disks that are part of the network. Make sure to sync your filesystemt to disk, and perhaps pause your xfs filesystems before triggering it.

For your current deployment that was based on the m1.small -> m3.medium conversion, I think probably it would suffice to add you all your machines that had this conversion:

    ec2.hvm = pkgs.lib.mkOverride 0 false;

However, if you have the possibility to build up your production from scratch, that would be better imho. Assuming you only store important state in your instances on the /data and /images disks, it should be fairly easy and quick, if you have recent snapshots (EBS snapshots are incremental). Let me know if you need more information about this.

**Comment by benmos** [comment]
That's great - thanks for the advice.

We have reasonably decent safety nets as we have regular EBS backup snapshots and S3 backups but I'd like to make this cleanup as smooth as possible, so I'll follow your suggestions above.

**Comment by rbvermaa** [comment]
Probably unnecessary to say, but make sure you test on a new deployment. Luckily that is very easy with nixops and EC2 :)

**Comment by benmos** [comment]
Will do.

I couldn't see where `ec2.hvm` was defined... but I think I'm going to go for rebuilding the environments from scratch anyway.

**Comment by rbvermaa** [comment]
ec2.hvm is part of the nixos/modules/virtualisation/amazon-image.nix file that is implictly imported by nixops (see 'nixops show-physical' output).
