### ISSUE TITLE
Linode support

### ISSUE THREAD

**Issue by pikajude** [NixOS/nixops#198]
There is a linode python library: https://github.com/tjfontaine/linode-python

**Comment by rushmorem** [comment]
I use Linode and have recently started using nixops so I will be working on this if nobody is already doing so.

**Comment by ArturSoler** [comment]
@rushmorem Any progress on this? I'm also interested. Thanks!

**Comment by rushmorem** [comment]
@ArturSoler I haven't had time to start working on it yet but it's still on my to do list. I hope to work on this sometime this month.

**Comment by rushmorem** [comment]
I have now started working on this. The scripts to mutate a Linode into a NixOS box will be available in https://github.com/WebEnchanter/nixify-linode.

**Comment by calvinchengx** [comment]
+1

Looking forward to this!

**Comment by dfoxfranke** [comment]
Is anybody still actively working on this? `nixos-bootstrapper` looks like a good start but obviously it's not the whole solution. Somebody needs to implement the appropriate `MachineDefinition` subclass.

**Comment by dfoxfranke** [comment]
I think there's a better way than StackScripts to get NixOS bootstrapped onto a Linode. A StackScript needs to run on top of an official Linode image, and after the script has executed the partition is still around wasting space. A better approach is to run the bootstrap script from a rescue image. Unfortunately, Linode rescue systems are only accessible via Lish, and Lish requires a terminal, but automation can use `expect` (or similar) to cope with this.

**Comment by rushmorem** [comment]
@dfoxfranke I'm still actively working on this but right now my hands are full with other commitments. `nixos-bootstrapper` is but a building block. As it is right now, you can run it from the rescue console or you can use a StackScript. I wanted to give people options to do what they like best. Even if you use a StackScript you can install NixOS into it's own partition and delete the distro supplied by Linode afterwards thereby getting your space back.

I actually use `expect` myself to automate my provisioning so it's on the roadmap.

**Comment by rbvermaa** [comment]
You'd only need to use terminal to set root password and enable ssh daemon right?

**Comment by rushmorem** [comment]
@rbvermaa I'm not sure I follow. Nixops still needs a NixOS base, right?

**Comment by dfoxfranke** [comment]
@rbvermaa Correct.

@rushmorem It does, but once ssh is spun up you can do the remaining bootstrapping via the usual `run_command`/`upload_file`/`download_file` interface rather than using `expect` to emulate keystrokes.

**Comment by dfoxfranke** [comment]
@rushmorem Have you started working on the NixOps codebase, and if so do you have a fork somewhere? This looks like a tempting [couple of] weekend's hack but I want to avoid duplicating effort.

**Comment by rushmorem** [comment]
@dfoxfranke I hadn't started working on the NixOps codebase yet, so knock yourself out ;)

**Comment by dfoxfranke** [comment]
I've begun work on this at https://github.com/dfoxfranke/nixops/tree/linode. The first committed change implements support for managing StackScripts. This is completely useless, but made a nice exercise for learning my way around the NixOps codebase and the Linode API.

**Comment by lihop** [comment]
@dfoxfranke Nice work! I'm really looking forward to linode support! :smiley:

**Comment by bfrog** [comment]
I would love to use nixops and nix on linode!

**Comment by GlennS** [comment]
I've been taking a look at this, but have run into a couple of problems depending on which way I approach it.

If I just install a Debian image and try to use nixos-infect (slightly modified to account for the different network devices) to overwrite it, then I bump into this problem with blkid https://github.com/NixOS/nixops/issues/711

If I create a Linode and boot it into rescue mode, then curl doesn't work https://forum.linode.com/viewtopic.php?f=7&t=15039

**Comment by domenkozar** [comment]
https://linode.com/docs/tools-reference/custom-kernels-distros/install-nixos-on-linode

**Comment by danielstaleiny** [comment]
any progress on this ???

**Comment by GlennS** [comment]
Hi daniel,

I'm really sorry, but I haven't done any more work on this. I no longer use NixOps or Linode at work.

Someone has commented on my pull request that they are able to use it and it works for them.

I believe it's just a matter of sorting out the testing to get it over the line.

**Comment by grahamc** [comment]
NixOps supports backends as plugins, so closing this. A plugin could be made :)
