### ISSUE TITLE
Add recovery feature

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixops#2]
If the state file of a Charon deployment is lost, it would be nice if it could be reconstructed automatically given the UUID of the network.

A related feature would be to enumerate all known machine instances in all backends (along with their network UUIDs).

So you could recover like this:

<pre>
$ charon discover-machines
ec2 33bced96-5f26-11e1-b9d7-9630d48abec1 foo
ec2 33bced96-5f26-11e1-b9d7-9630d48abec1 bar

$ charon -s ./state.json recover 33bced96-5f26-11e1-b9d7-9630d48abec1
</pre>

**Comment by jezen** [comment]
Any word on this? Having to maintain a state file which could potentially be lost is keeping people away from using NixOps.

Also I have lost my state file and I am not sure how to rebuild it.

**Comment by grahamc** [comment]
#1264 implements state backends, and those backends could implement backups.
