### ISSUE TITLE
Provide a way to SSH to "none"-type boxes

### ISSUE THREAD

**Issue by pikajude** [NixOS/nixops#200]
Currently as far as I can tell there's no way to SSH to a box that isn't EC2, Hetzner, or VirtualBox. I'm trying to provision my linode but nixops complains `error: do not know private SSH key for machine ‘webserver’`. It would be helpful if the API exposed a way to access "none"-type boxes. (I'm not sure why "none"-type boxes exist if they can't be provisioned.)

**Comment by fmap** [comment]
:+1:

**Comment by fmap** [comment]
(On `HEAD`, explicitly setting `NIX_REMOTE_SYSTEMS` seems to be a workaround.)

**Comment by aszlig** [comment]
Should be fixed by #201.
