### ISSUE TITLE
Add --keep-days option to the clean-backups command

### ISSUE THREAD

**Issue by zelouaer** [NixOS/nixops#216]
When running nixops clean-backups command with --keep option, we can specify the number of backups to keep, not the max age of backups to keep.

From nixops clean-backups -h : 
  --keep KEEP           number of backups to keep around

It would be helpful to have an equivalent option (e.g. --keep-days) that allows us to specify the number of days of backups to keep.

Thanks!

**Comment by zelouaer** [comment]
Any update on this request? It's been sitting here for 2 years. I don't think it's complicated to implement and it really helps. Keeping a certain number of snapshots is not really relevant versus number of days of backups since all customer SLAs use days and not number of snaps. We can take 10 snaps in a day and not take snaps at all the next day. We would have no way of keeping track of those. Thanks!!

**Comment by domenkozar** [comment]
@zelouaer feel free to contact me if you'd sponsor this feature, otherwise you can contribute it yourself or wait for someone to need it and implement it.
