### ISSUE TITLE
Hetzner deploy fail due to function called with out arg

### ISSUE THREAD

**Issue by Davorak** [NixOS/nixops#228]
nixops installed using the most [recent nixpkgs](https://github.com/NixOS/nixpkgs/commit/28e1d2508436767347dcebc51cf22e5d17a48b8d)

`nix-env -iA nixpkgs.nixops -I nixpkgs=<path to nixpkgs repo>

or 

`nix-env -f default.nix -iA nixops`

What look to be the key error lines:

/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs/nixos/modules/installer/tools/tools.nix:4:1 called without required argument `lib', at /nix/store/hwdmh85bdgqcy6ijv22kwx8m2989qjmb-nixops-1.2/share/nix/nixops/hetzner-bootstrap.nix:9:21

http://pastebin.com/4EuQYbYt

Encountered after #227

I also tried building with the most recent nixops repo and nixpkgs repo with:

`nix-env -f release.nix -iA build -I nixpkgs=../nixpkgs/`

With no luck.

**Comment by aszlig** [comment]
I believe this is fixed and there also hasn't been activity here since years.
