### ISSUE TITLE
deployment.keys.*.user/group need to be sent after activation

### ISSUE THREAD

**Issue by rbvermaa** [NixOS/nixops#232]
Otherwise deployments fail on initial deployments.

**Comment by philandstuff** [comment]
I have an issue where if I set deployment.keys.<foo>.user, and a nixos module is responsible for creating this user in a users.extraUsers expression, then the deployment fails because it tries to `chown` the key before creating the user.  Is this the same issue, or should I file a new one?

**Comment by aszlig** [comment]
This should be related to #362.

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nixops/pull/400
