### ISSUE TITLE
Error deploying trivial-gce.nix

### ISSUE THREAD

**Issue by aaronlevin** [NixOS/nixops#235]
I'm trying to create a basic instance using the `trivial-gce.nix` example. I get the following error:

```
[nix-shell:~/xxx]$ nixops create ./trivial-gce.nix -d nixops-test
created deployment ‘9fc9542b-5580-11e4-a4a9-56847afe9799’
9fc9542b-5580-11e4-a4a9-56847afe9799

[nix-shell:~/xxx]$ nixops deploy -d nixops-test
error: unknown backend type ‘gce’
```

Here is the `trivial-gce.nix` file:

```
{
  machine =
    { deployment.targetEnv = "gce";
      deployment.gce = {
        # credentials
        project = "galene-development";
        serviceAccount = "xxxxxxxxx@developer.gserviceaccount.com";
        accessKey = "pkey.pem";

        # instance properties
        region = "europe-west1-b";
        instanceType = "n1-standard-2";
        tags = ["crazy"];
        scheduling.automaticRestart = true;
        scheduling.onHostMaintenance = "MIGRATE";
      } ;

      fileSystems."/data"=
        { autoFormat = true;
          fsType = "ext4";
          gce.size = 10;
          gce.encrypt = true;
          gce.disk_name = "data";
        };
    };
}
```

The environment from which I'm running `nixops` is created by running `nix-shell` with the following nix-expression:

```
# default.nix
{ pkgs ? (import <nixpkgs> {}) }:

let
  inherit (pkgs) stdenv;
in stdenv.mkDerivation rec {
  name = "xxx-build-env";
  version = "0.0.1";
  src = ./.;
  buildInputs = [
    pkgs.nixops
    pkgs.openssl
  ];
}
```

I'm not really sure what's going on. I also tried running the examples (`load-balancer.nix` and `load-balancer-gce.nix`) and received a similar error.

**Comment by Phreedom** [comment]
so was someone using that old gce derivation? then obviously it would be 
failing from time to time...

**Comment by oconnorr** [comment]
Everyone was using that old gce derivation. The bootstrap image used to (now fixed) predate the fetch-keys-fix and every deployment would start from the bootstrap image.  The deployment would try to update the fetch-keys service, but if the fetch-keys service fails on the bootstrap image the nixops cannot even get far enough to upload the updated service.

PS you might be interested in reviewing/applying https://github.com/NixOS/nixpkgs/pull/5515
