### ISSUE TITLE
Nixops on Darwin – cannot find bash/users-groups.json

### ISSUE THREAD

**Issue by lovek323** [NixOS/nixops#240]
I'm trying the example deployment to virtualbox on an OS X system (I'm using the latest `darwin-clang-stdenv` branch for nixpkgs and the 1.2 release for nixops). Everything seems to build fine, but when it gets to copying the paths to the virtual machine, I get some interesting errors.

```
-bash: line 1: /nix/store/005j6bnfbw25as730ar6zc21c2h578f2-bash42-045.drv: No such file or directory
-bash: line 2: /nix/store/g1dlyn1686dd0sd4hzldjlimcgf9hk8y-users-groups.json: No such file or directory
copying 200 missing paths to ‘root@192.168.33.103’...
terminate called after throwing an instance of 'nix::SysError'
```

Any help would be greatly appreciated. :smile:

**Comment by domenkozar** [comment]
@lovek323 is this still an issue nowadays?

**Comment by domenkozar** [comment]
Merging into https://github.com/NixOS/nixops/issues/560
