### ISSUE TITLE
Unknown pwds requested when deploying very simple container.

### ISSUE THREAD

**Issue by jraygauthier** [NixOS/nixops#256]
Using the container proposed in the manual at:
<http://nixos.org/nixops/manual/#idm140737319351408> but
instead of using Vbox, I use `container` as follow:

~~~
{
  network.description = "Web server";

  webserver =
    { config, pkgs, ... }:
    { deployment.targetEnv = "container";
      services.httpd.enable = true;
      services.httpd.adminAddr = "alice@example.org";
      services.httpd.documentRoot = "${pkgs.valgrind}/share/doc/valgrind/html";
      networking.firewall.allowedTCPPorts = [ 80 443 ];
    };
}
~~~

Here's what I get:

> [~]$ nixops deploy -d webserver-cont
> webserver> building initial configuration...
> webserver> creating container...
> Password: 
> Password: 
> Password: 
> root@localhost's password: 
> Permission denied, please try again.
> root@localhost's password: 
> Received disconnect from 127.0.0.1: 2: Too many authentication failures for root
> error: unable to start SSH master connection to ‘root@localhost’

Now, what is the password prompted at `Password` ? I tried my user password, my root password and invalid password and it does not seem to matter. I get asked trice and afterward I get prompted
for the root password of some machine through ssh (most probably the machine I try to deploy).
Again, what is this password supposed to be?

Note also that I use a very recent version of nixops:
025030d841d9b6d070f8f7fbcec8b537a674d972.

I also tried declarative containers in my `configuration.nix` and it work pretty well.

**Comment by skrat** [comment]
I had no password prompts, but was getting `Too many authentication failures for root`. I turned out that my ssh-agent had too many keys loaded. This worked for me

    SSH_AUTH_SOCK='' nixops ssh -d trivial webserver

**Comment by ip1981** [comment]
Might be recent OpenSSH striking back

**Comment by jraygauthier** [comment]
The cause was nixos's default value  `"without-password"` for `services.openssh.permitRootLogin`.

Rebuilding my computer's nixos configuration with `services.openssh.permitRootLogin="yes"`
solved my problem.
