### ISSUE TITLE
Unable to start SSH master connection to Hetzner server

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nixops#258]
I'm trying to deploy to a Hetzner machine but I'm getting the following error (I censored it for security reasons): 

```
HETZNER_ROBOT_USER="xxxxxx" \
HETZNER_ROBOT_PASS="xxxxxx" \
nixops deploy -d my-network --include my-server
my-server.............> creating an exclusive robot admin account for ‘my-server’...done. (#xxxxxxx)
my-server.............> installing machine...
my-server.............> rebooting machine ‘my-server’ (1xx.1xx.1xx.1xx) into rescue system
my-server.............> sending hard reset to robot...done.
my-server.............> waiting for rescue system.................................................................................................................[down][up]
my-server.............> building Nix bootstrap installer...done. (/nix/store/jkkvmxlkyy4wfqwppm4abv0k34fkzy89-hetzner-nixops-installer/bin/hetzner-bootstrap)
my-server.............> checking if tmpfs in rescue system is large enough...error: unable to start SSH master connection to ‘my-server’
```

The definition of `my-server` is not much more than the following:

```nix
my-server = { config, pkgs, ... }: {
  deployment = {
    targetEnv        = "hetzner";
    hetzner.mainIPv4 = "1xx.1xx.1xx.1xx";
  };

  imports = [
    <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ...
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-label/root";
    fsType = "ext4";
  };

  swapDevices = [
    { device = "/dev/disk/by-label/swap1"; }
    { device = "/dev/disk/by-label/swap2"; }
  ];
};
```

Any idea what I'm doing wrong?

**Comment by iElectric** [comment]
cc @aszlig

**Comment by basvandijk** [comment]
I just tried using the latest nixops from git (e29fa84b2a5d6fef1870d117efbfddb877f8068c) and now I'm getting slightly more informative error messages:

```
HETZNER_ROBOT_USER="lumiguidef" \
HETZNER_ROBOT_PASS="PutWaaDa9wzTjStu" \
nixops deploy -d stalling-net -I .. --include central-01
central-01.............> installing machine...
central-01.............> rebooting machine ‘central-01’ (136.243.17.41) into rescue system
central-01.............> sending reboot command...
central-01.............> could not connect to ‘root@136.243.17.41’, retrying in 1 seconds...
central-01.............> could not connect to ‘root@136.243.17.41’, retrying in 2 seconds...
central-01.............> could not connect to ‘root@136.243.17.41’, retrying in 4 seconds...
central-01.............> could not connect to ‘root@136.243.17.41’, retrying in 8 seconds...
error: unable to start SSH master connection to ‘root@136.243.17.41’
```

I'm not sure the problem has to do with root not having the right authorizedKeys but I'm setting them correctly in the definition of `my-server`:

```nix
    extraUsers = {
      "root" = {
         openssh.authorizedKeys.keys =
              config.users.extraUsers."bas.van.dijk".openssh.authorizedKeys.keys;
      };

      "bas.van.dijk" = {
        name = "bas.van.dijk";
        uid = 1001;
        isNormalUser = true;
        extraGroups = [ "wheel" ];
        passwordFile = "${./linux-account-passwords/bas.van.dijk.enc}";
        openssh.authorizedKeys.keys = [ "xxxx" ];
      };
    };
```

**Comment by basvandijk** [comment]
Note that if I manually try to sign in with the password for the rescue system it also fails:

```
ssh root@1xx.1xx.1xx.1xx
root@1xx.1xx.1xx.1xx's password: xxxxxx
Permission denied, please try again.
```

**Comment by aszlig** [comment]
@basvandijk: Change your password please! Look closer into your previous comment!

**Comment by basvandijk** [comment]
@aszlig Note that `xxxxxx` is not my actual password. I censored it for security.

**Comment by aszlig** [comment]
@basvandijk: No, but the one starting with `Put` is... :unamused:

**Comment by basvandijk** [comment]
@aszlig Sorry I see what you mean. Whoops! Thanks for the quick reply!

**Comment by aszlig** [comment]
As for the issue, if you look at the [VM tests](https://hydra.nixos.org/build/18996836/nixlog/17/raw), they have the same problem. Going to fix it ASAP.

**Comment by aszlig** [comment]
ASAP -> when I'm home again (tomorrow) :-/

**Comment by basvandijk** [comment]
Thanks for your help @aszlig. I'm looking forward to a solution. Let me know if you need help.

**Comment by aszlig** [comment]
I've bisected this with nixpkgs and it seems that the recent version of Debian Wheezy somehow causes the trouble. I'm not quite sure *why* that is, but I'm currently trying to figure it out.

**Comment by basvandijk** [comment]
Ok, I also opened a support request at Hetzner because the problem seems to be on their side.

**Comment by basvandijk** [comment]
Hetzner came back to me:

    Dear Mr van Dijk,

    As requested we have checked the server and found a faulty cable for the
    hardreset, hence only the soft reboot should have been working. 
    You can log in to the Rescue System using root password xxxxxxx now. 

    Best Regards

And indeed, now I can manually SSH into the rescue system.

Trying to install NixOS using nixops now...

**Comment by basvandijk** [comment]
nixops can now successfully SSH into the rescue system.

However, I'm getting a new error as described in #259.

**Comment by ip1981** [comment]
Hi guys! I got the same connection error, but cable was ok :-)

My case was caused by too strict `~/.ssh/config` which prevented any password-based login
