### ISSUE TITLE
nix-copy-closure can't connect to Hetzner host in rescue mode

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nixops#259]
I get the following error when trying to deploy NixOS to a Hetzner server:

```
HETZNER_ROBOT_USER="xxxxxx" \
HETZNER_ROBOT_PASS="xxxxxx" \
"./nixops-HEAD" deploy -d my-network -I .. --include my-server
building all machine configurations...
my-server.............> copying closure...
my-server.............> error: the group ‘nixbld’ specified in ‘build-users-group’ does not exist
my-server.............> error: the group ‘nixbld’ specified in ‘build-users-group’ does not exist
my-server.............> unable to connect to ‘root@1xx.1xx.1xx.1xx’; falling back to old closure copying method
my-server.............> error: the group ‘nixbld’ specified in ‘build-users-group’ does not exist
my-server.............> Died at /nix/store/ffig6yaggbh12dh9y5pnf1grf5lqyipz-nix-1.8/lib/perl5/site_perl/5.20.1/x86_64-linux-thread-multi/Nix/CopyClosure.pm line 100.
error: command ‘['nix-copy-closure', '--to', 'root@1xx.1xx.1xx.1xx', u'/nix/store/gyiddbpg4mv8930p0ww4ixsj8sjxnvz9-nixos-15.05pre-git', '--gzip']’ failed on machine ‘my-server’ (exit code 1)
```

`my-server` is simply defined as:

```nix
  my-server = { config, pkgs, ... }: {
    deployment = {
      targetEnv        = "hetzner";
      hetzner.mainIPv4 = "1xx.1xx.1xx.1xx";
    };
```

Note that I'm using `nixpkgs` at revision: https://github.com/NixOS/nixpkgs/commit/5bc68e1a0ee8ff5f6670c62567679dfbf7ea4052 

Note that `nixops-HEAD` is a bash script which runs the latest nixops from git:

```bash
#!/usr/bin/env bash

cmd="nixops"
for var in "$@"
do
  cmd="${cmd} \"$var\""
done

nix-shell nixops-HEAD-env.nix -I .. --command "$cmd"
```

where `nixops-HEAD-env.nix` is defined as:

```nix
# This adds nixops-HEAD to the environment so we can
# benefit from the latest bug-fixes.
#
# It depends on the source of nixops to be in the ./nixops directory.
#
# We currently have nixops checked out in ./nixops as a git submodule.

{ pkgs ? import <nixpkgs> {} }:

let nixopsUnstable = pkgs.callPackage
      <nixpkgs/pkgs/tools/package-management/nixops/unstable.nix> {};

    nixopsHEAD = pkgs.stdenv.lib.overrideDerivation nixopsUnstable (oldAttrs: {
      name = "nixops-HEAD";
      src = ./nixops;
      patches = [];
    });

in
pkgs.myEnvFun {
  name = "nixops-HEAD";
  buildInputs = [
    nixopsHEAD
  ];
}
```

And `./nixops` is at revision: e29fa84b2a5d6fef1870d117efbfddb877f8068c.

**Comment by iElectric** [comment]
From OSX?

**Comment by basvandijk** [comment]
> From OSX?

No, from NixOS.

**Comment by basvandijk** [comment]
> Note that I'm using nixpkgs at revision: NixOS/nixpkgs@5bc68e1

Note that I also get the same error with the latest checkout of nixpkgs (https://github.com/NixOS/nixpkgs/commit/15b6886aedabe4bf788ffa1bb63c0d8eff426ccf).

**Comment by iElectric** [comment]
cc @edolstra

**Comment by basvandijk** [comment]
I changed the title of this issue to more accurately reflect what is going wrong.

The connection error occurs in: https://github.com/NixOS/nixops/blob/master/nixops/backends/__init__.py#L295
```python
    def copy_closure_to(self, path):
        """Copy a closure to this machine."""

        # !!! Implement copying between cloud machines, as in the Perl
        # version.

        ssh = self.get_ssh_for_copy_closure()

        # It's usually faster to let the target machine download
        # substitutes from nixos.org, so try that first.
        if not self.has_really_fast_connection():
            closure = subprocess.check_output(["nix-store", "-qR", path]).splitlines()
            ssh.run_command("nix-store -j 4 -r --ignore-unknown " + ' '.join(closure), check=False)

        # Any remaining paths are copied from the local machine.
        env = dict(os.environ)
        env['NIX_SSHOPTS'] = ' '.join(ssh._get_flags() + ssh.get_master().opts)

        self._logged_exec(
            ["nix-copy-closure", "--to", ssh._get_target(), path]
            + ([] if self.has_really_fast_connection() else ["--gzip"]),
            env=env)
```

Note that the `ssh.run_command("nix-store ...)` succeeds but `nix-copy-closure` fails to connect while using the same ssh options.

Any idea why `nix-copy-closure` can't connect to a Hetzner node in rescue mode while previous ssh commands succeed?

**Comment by rbvermaa** [comment]
@aszlig

**Comment by basvandijk** [comment]
Also besides the connection issue the 
`error: the group ‘nixbld’ specified in ‘build-users-group’ does not exist`
errors are also worrisome...

**Comment by basvandijk** [comment]
@iElectric, @edolstra, @rbvermaa, if it would help, I would be glad to sponsor a Hetzner server for a few months so that we can debug this problem.

Let me know if you guys are interested in this then I will setup an EX40 machine and provide you the credentials/

**Comment by rbvermaa** [comment]
@aszlig Can you let me know if you have time to look into this. If not, I will look at it.

**Comment by edolstra** [comment]
This might be fixed by https://github.com/NixOS/nix/commit/3d97b8d1e77f133eb725665752a6ec909a7584b2.

**Comment by basvandijk** [comment]
@edolstra is it possible to override `<nixpkgs/pkgs/tools/package-management/nix/unstable.nix>` to use the nix-HEAD `src` so I can try this out?

**Comment by edolstra** [comment]
The current unstable.nix already includes that commit.

**Comment by rbvermaa** [comment]
I am going to test it today, if the Robot stops annoying me.

**Comment by rbvermaa** [comment]
@basvandijk Could you try c5c49a18c84e983ba1a0446d2ce294c76ab084c8 ?

**Comment by rbvermaa** [comment]
Actually, never mind, getting another error now. Still investigating...

**Comment by aszlig** [comment]
I've tried to fix the [VM test](https://hydra.nixos.org/job/nixops/master/tests.hetzner_backend) a while ago. One problem I ran into was that during tho introduction of containers, the default way to deploy was using the Nix daemon on the remote side, c06e79afe21d5b5e4cfc97309101130d9e3cb024 should fix that.

Unfortunately I don't remember the other two problems anymore :-/

**Comment by rbvermaa** [comment]
@basvandijk I was able to deploy a new Hetzner machine now successfully using 4fb365585980a1db1aee520657658dddc86d7ded

**Comment by basvandijk** [comment]
I just got around testing this and I can now deploy to Hetzner. Thanks everybody!

I did have one hickup though. When deploying I got the following error:

```
building all machine configurations...
error: 
Failed assertions:
- The ‘fileSystems’ option does not specify your root file system.
```

I was expecting that the default Hetzner configuration would include the correct file systems. After adding:

```
fileSystems."/" = {
  device = "/dev/disk/by-label/root";
  fsType = "ext4";
};
```

The error disappeared and I got the following:

```
building all machine configurations...
error: You must set the option ‘boot.loader.grub.device’ to make the system bootable.
```

Again I had the similar expectation that this would already have the right default. So I set:

```
boot.loader.grub.device = "/dev/md0";
```

Then the initial deployment continued a bit further but then I got:

```
...
zeus.......................> creating nixbld group in rescue system...done.
zeus.......................> checking if tmpfs in rescue system is large enough...yes: 16029 MB
zeus.......................> copying bootstrap files to rescue system...^[[Bdone.
zeus.......................> partitioning disks...done.
zeus.......................> bind-mounting special filesystems.../proc.../dev.../dev/shm.../sys...done.
zeus.......................> creating missing directories...done.
zeus.......................> bind-mounting files in /etc...resolv.conf...passwd...group...done.
zeus.......................> detecting hardware...done.
zeus.......................> waiting for SSH...
building all machine configurations...
error: The unique option `fileSystems./.fsType' is defined multiple times, in `/home/bas.van.dijk/engineering/lumi/deployment/stalling-net.nix' and `/run/user/1001/nixops-tmpm_ERbK/physical.nix'.
```

So I removed the `fileSystems."/"` and `boot.loader.grub.device ` definitions after which the deployment succeeded.

I can't imagine users are supposed to do this each time they do an initial deployment.

**Comment by aszlig** [comment]
@basvandijk: This obviously shouldn't be the case, did you do a bootstrap from scratch (destroy + deploy) or did you just retry with your old state?

**Comment by basvandijk** [comment]
@aszlig Yes I did a bootstrap from scratch (destroy + deploy).

**Comment by ip1981** [comment]
> The ‘fileSystems’ option does not specify your root file system.

This is because this options are set by nixops in state database after hetzner server has been configured
