### ISSUE TITLE
Cannot (re)deploy old deployment (missing "backing file")

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixops#261]
I created a nixops deployment some time ago (~2 months). Now I cannot start/deploy it anymore, because of what looks like garbage collection having removed the "backing file":

```
$ nixops deploy -d trivial
machine> error: Failed to create domain from /tmp/nixops-tmpBdXUKd/machine-domain.xml
machine> error: Cannot access backing file '/nix/store/nmg8c0b84b5mx1f24l9vqkj2fz9rmpyg-libvirtd-ssh-image/disk.qcow2' of storage file '/home/bfo/nixops-libvirt-images/nixops-60d1a626-8635-11e4-bbc6-00012e496794-machine.img' (as uid:0, gid:0): No such file or directory
machine> 
error: command ‘['virsh', '-c', 'qemu:///system', 'create', '/tmp/nixops-tmpBdXUKd/machine-domain.xml']’ failed on machine ‘machine’ (exit code 1)
```

How to rebuild the missing "backing file"? Shouldn't nixops do this automatically?

I looked at the available options for the "deploy" command, in case there was some option to rebuild the "backing file" or something. I tested "nixops deploy -d trivial --repair" (and --allow-recreate), but that didn't fix it.

"nixops start -d trivial" prints the same message (missing backing file).

I'm running nixops-1.3pre1362_2a616f8.

**Comment by domenkozar** [comment]
So here's whats' going on:

- libvirt backend creates `base_image` with `nix-build` and points output link to `/tmp/`
- `"qemu-img", "create", "-f", "qcow2", "-b",  base_image + "/disk.qcow2", self.disk_path` is invoked

### current behaviour

Once you reboot, GC root is gone and base image can be garbage collected. Once you deploy again, `disk.qcow2` can't find it's base image anymore.

### proposed solution

We should really build a basic qemu image for each release and always use just that. If it's GC-ed, substitute it again. No need to build an image each time, best to just deploy to the image (same as VB does).

**Comment by johan-boule** [comment]
Will the proposed solution also work with unstable channels ?
In the meantime, before a solution is found, we can transform the image into standalone one by copying all backing data into the final image file itself, with :
`qemu-img rebase -b '' /home/bfo/nixops-libvirt-images/nixops-60d1a626-8635-11e4-bbc6-00012e496794-machine.img`
After this command, the image file is self-contained and no longer linked to any backing file anymore.

**Comment by Nadrieril** [comment]
IMHO you cannot make any kind of reasonably robust setup if VMs can be broken at any random point because of nix garbage collection, even if recreating the base image is not hard... I would guess nixops could manage the GC roots itself to avoid breakage.
Rebasing would also be a solution, but since the base image is around 700MB, it would cost disk space.

**Comment by bjornfor** [comment]
I've thought a bit about the backing file. I think we should get rid of it.

Sure, a backing file reduces the _initial_ disk footprint when creating 1+ machines. But, unless I'm mistaken (*and please correct me if I'm wrong*), after N upgrades and GC sycles in the VMs, none of the original base image bits are in use anymore! (This assumes we prevent GC'ing the base image, of course.) Every bit of useful disk data will be stored in the "overlay" image (don't know the correct term) at this point. So in the end there is no space savings. Rather the opposite. Now there will be a backing file laying around occupying a few hundred megabytes and serving no purpose.

A data point. The "virtualbox" backend doesn't use a backing file. It simply clones the base image per VM, right from the start.

I'll make a PR.

**Comment by bjornfor** [comment]
@domenkozar: About your proposed solution:
> We should really build a basic qemu image for each NixOS release and always use just that. If it's GC-ed, substitute it again. No need to build an image each time, best to just deploy to the VM (same as VB does).

Sure, having the base image / backing file built by Hydra would be nice, but I don't think it solves this issue. The problem is that Nix doesn't manage the backing file in any way, after the initial build. So once garbage collected, there is (currently) no program flow that causes the file to be instantiated again. If we made such a change, that nixops notices the backing file is gone and re-instantiates it, it would have to be a _bit perfect_ substitution, right? Or else I think there would be major disk corruption for the VM. So that means no upgrades of the backing file. And the backing file would have to be built from a locked down nixpkgs repo with fully deterministic build process. And given that in the end (after N upgrades and GC cycles) there will be no space saving (correct me if I'm wrong), I think we should stop depending on the backing file and simply clone the base image every time.

**Comment by domenkozar** [comment]
Sounds good to me :)
