### ISSUE TITLE
SSH_HOST_DSA_KEY in EC2 user data seems liffy

### ISSUE THREAD

**Issue by copumpkin** [NixOS/nixops#267]
I was looking through nixops and noticed that a host private key gets embedded in user data, which is readable to anyone who has access to that part of the amazon console. Is there a reason it's done this way? It doesn't seem ideal in an organization with a lot of console users of differing power/access.

**Comment by edolstra** [comment]
I'm not aware that the user data can be queried from the console.

Nevertheless this method is far from ideal, but it was the most practical way to have strict host key checking. (IIRC, the traditional way is to have the instance generate a host key, print the host public key to the console, and then use `ec2-get-console-output` on the client.)

An improvement would be to have NixOps generate a new host key on the instance via SSH, using the initial host key only for the initial connection.

**Comment by edolstra** [comment]
Oops, the console does allow access to the user data.
