### ISSUE TITLE
error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)

### ISSUE THREAD

**Issue by aherrmann** [NixOS/nixops#268]
Hi,

I'm trying to deploy to Amazon's EC2 using nixops. I followed the instructions given in the [manual](http://nixos.org/nixops/manual/#sec-deploying-to-ec2) closely. However, the deployment process fails with the following error message:

```
 error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

I have Nix, and NixOps installed on an opensuse machine. I know that SSL can be an issue at times due to mismatching, or missing ca certificates. I encountered similar issues before with curl. In that particular case the issue was resolved by exporting `CURL_CA_BUNDLE` pointing to the nix specific `ca-bundle.crt`. I tried exporting `SSL_CERT_DIR`, and `SSL_CERT_FILE` as follows. Sadly, to no avail.

```
$ export SSL_CERT_DIR=${HOME}/.nix-profile/etc/ca-bundle.crt
$ export SSL_CERT_FILE=${HOME}/.nix-profile/etc/ca-bundle.crt
$ nixops deploy -d mydeployment
error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

The error message appears approximately 2 minutes after entering the command without any other output in between.
The file `${HOME}/.nix-profile/etc/ca-bundle.crt` exists and is working for curl.

Any suggestions on how to fix this? Or any ideas what I might be doing wrong?

**Comment by domenkozar** [comment]
Are you using Python 2.7.9?

**Comment by aherrmann** [comment]
@domenkozar Sorry for the late response, I was out of town for a few days.

Yes, `nixops` depends on Python 2.7.9. (My system's Python version is 2.7.8.) Is this a known issue for Python 2.7.9?

**Comment by domenkozar** [comment]
So Python 2.7.9 turned on SSL certificate validation by default and there are many reasons why that check might fail. Try to figure out what hostname it's trying to reach.

**Comment by domenkozar** [comment]
@aherrmann It would be nice to find out what hostname is nixops trying to contact and if you can curl it

**Comment by aherrmann** [comment]
@domenkozar I tried with strace and a pudb session but couldn't really figure out what's going on. (I don't know how to do multi-thread debugging with pudb.) The only hostname that I could find in the strace was `us-west-2.queue.amazonaws.com`. That's strange, because I've explicitely set `region` to `eu-west-1`. Anyway, I can curl that host (even if I prefix it with `https://`). The response is `<UnknownOperationException/>`.

The ~2min stall that I'm seeing corresponds to a huge series of `select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)` lines in the `strace` output.

The final error message looks like this in the strace:

```
select(0, NULL, NULL, NULL, {0, 50000}) = 0 (Timeout)
close(9)                                = 0
ioctl(2, SNDCTL_TMR_TIMEBASE or SNDRV_TIMER_IOCTL_NEXT_DEVICE or TCGETS, 0x7ffce6168900) = -1 ENOTTY (Inappropriate ioctl for device)
write(2, "error: [SSL: CERTIFICATE_VERIFY_"..., 79error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
) = 79
sendto(3, "<12>nixops[3895]: error: [SSL: C"..., 97, 0, NULL, 0) = 97
sendto(3, "<12>nixops[3895]: \0", 19, 0, NULL, 0) = 19
```

**Comment by domenkozar** [comment]
@aherrmann could you try copiying `which nixops` script somewhere and adding `SSL_CERT_FILE` export in that bash script?

**Comment by aherrmann** [comment]
@domenkozar `nixops` has two layers of wrapper scripts. (A side-effect is that `argv[0]` is set to `.nixops-wrapper`). One for the `PATH` that contains `openssh`, and one for the python environment. I tried adding `SSL_CERT_FILE`, and also [`OPENSSL_X509_CERT_FILE`](https://github.com/NixOS/nixops/blob/master/scripts/nixops#L28) to both layers. Unfortunately, to no avail. It behaves exactly as before.

**Comment by domenkozar** [comment]
Yeah I saw that :/ I'll have to reproduce it myself, sorry for stupid trial/error

**Comment by domenkozar** [comment]
@aherrmann do you still have this issue?

**Comment by aherrmann** [comment]
@domenkozar Sorry for the late response. Yes, the issue remains. The error message has changed slightly. Now it refers to line number 590:

    error: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)

I tried the latest versions on the following channels:
```
https://nixos.org/channels/nixos-15.09 nixos
http://nixos.org/channels/nixpkgs-unstable nixpkgs
```
With all the above mentioned environment variables exported directly from within the wrapper scripts or exported on the command line.

**Comment by mattbillenstein** [comment]
FWIW, I had a similar problem on OSX -- looking at strings output from libcrypto, it looks like it's trying to load /etc/ssl/certs/ca-certificates.crt -- hacky workaround I've applied for now:

```
nix-env -i cacert

if [ "$(uname)" == "Darwin" ]; then
    sudo mkdir -p /etc/ssl/certs
    sudo cp $(find /nix -name 'ca-bundle.crt' | head -1) /etc/ssl/certs/ca-certificates.crt
fi
```

**Comment by domenkozar** [comment]
This one most probably duplicates https://github.com/NixOS/nix/issues/921, this is not an NixOps issue (at least nothing can be fixed here).
