### ISSUE TITLE
GCE deployment fails with error about missing EC2 option

### ISSUE THREAD

**Issue by oconnorr** [NixOS/nixops#273]
I was trying a deployment similar to https://github.com/NixOS/nixops/blob/master/examples/trivial-gce.nix today but I get the following error:

$ nixops deploy --check -d trivial
bootstrap> creating GCE image 'n-365406c0c35511e4912342010af08924-bootstrap'...
machine..> creating GCE disk of auto GiB from image 'n-365406c0c35511e4912342010af08924-bootstrap'...
machine..> creating GCE machine 'n-365406c0c35511e4912342010af08924-machine'...
machine..> got IP: 130.211.181.72
machine..> attaching GCE disk 'n-365406c0c35511e4912342010af08924-machine-root'...
machine..> waiting for SSH...
/etc/ssh/ssh_config line 53: Unsupported option "gssapiauthentication"
/etc/ssh/ssh_config line 54: Unsupported option "gssapidelegatecredentials"
The authenticity of host '130.211.181.72 (130.211.181.72)' can't be established.
ECDSA key fingerprint is c0:64:12:fb:14:8d:fd:8c:9f:d3:f9:93:fb:f9:2a:8a.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '130.211.181.72' (ECDSA) to the list of known hosts.
machine..> /etc/ssh/ssh_config line 53: Unsupported option "gssapiauthentication"
machine..> /etc/ssh/ssh_config line 54: Unsupported option "gssapidelegatecredentials"
machine..> /etc/ssh/ssh_config line 53: Unsupported option "gssapiauthentication"
machine..> /etc/ssh/ssh_config line 54: Unsupported option "gssapidelegatecredentials"
building all machine configurations...
error: The option `ec2' defined in `/nix/store/001lh3kglb0ayy5nyi481qa7h82gmnyc-nixops-1.3pre1444_3c98f98/share/nix/nixops/ec2.nix' does not exist.
(use �--show-trace� to show detailed location information)
error: unable to build all machine configurations

I can attach the trace if requested

$ nixops --version   
NixOps 1.3pre1444_3c98f98

**Comment by rbvermaa** [comment]
You are using latest version of nixops? (master)

If so, you'll need to update the nixos version you are using. The needed changes are in both 14.12 and 15.05

**Comment by oconnorr** [comment]
I added

resources.gceImages.bootstrap = credentials // {
    sourceUri = "gs://nixos-cloud-images/nixos-14.12.471.1f09b77-x86_64-linux.raw.tar.gz";
  };

To my configuration, and I have the same error.

**Comment by rbvermaa** [comment]
I meant earlier the NixOS version you are trying to deploy, e.g. the nixpkgs that is on your NIX_PATH, not the version of NixOS that is running on the bootstrap image.

**Comment by oconnorr** [comment]
Hmm, I was running NixOps from a Debian machine so I have no NixOS in my path

I did update my nixpkgs channel though

    $ nix-channel --update
    downloading Nix expressions from http://nixos.org/releases/nixpkgs/nixpkgs-15.05pre57176.b9cc043/nixexprs.tar.xz

According to --show-trace it is getting nixos from the right place:
...
while evaluating the attribute <E2><80><98>config.system.build.toplevel<E2><80><99> at "/home/oconnorr/.nix-defexpr/channels/nixpkgs/nixos/lib/eval-config.nix":26:5:
...

But I'm still getting the same error.

**Comment by rbvermaa** [comment]
It seems that channel is from Feb 3rd, while the change was done on Feb 16th (824fccd3e90cf75d5e2968fef2392f70e04d9f9c).

**Comment by rbvermaa** [comment]
@edolstra any idea why the nixpkgs channel hasn't been updated, while nixos channel has been since Feb 3rd?

**Comment by oconnorr** [comment]
Okay, cloning the latest repository and running

    NIX_PATH=nixpkgs=/home/oconnorr/nixpkgs nixops

works without error. I'm marking this as closed.  I'm sure the unstable channel will eventually get updated.
