### ISSUE TITLE
packageOverride hangs on fetchgit error

### ISSUE THREAD

**Issue by ArturSoler** [NixOS/nixops#275]
When creating a custom package using `packageOverrides`, and having an execution error in one of the packages, then doing a deploy of the system, it hungs without exposing any 

`packageOverride> ........................................................................................`

It just keeps adding dots indefinetely.

**Comment by aszlig** [comment]
This looks weird. Did you specify `packageOverrides` directly in your network specification rather than under the corresponding machine using `nixpkgs.config`?

**Comment by domenkozar** [comment]
Closing as no response. Please reopen with detailed description if issue persists.
