### ISSUE TITLE
Adapt the Amazon CloudWatch Monitoring Scripts for Linux to NixOS

### ISSUE THREAD

**Issue by mdallali** [NixOS/nixops#276]
AWS have created some scripts that allow us to push some unavailable-to-CloudWatch custom linux metrics.

AWS only shares how this can be done in some Linux ditributions and does not include NixOS.

The documentation about this can be found here : http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/mon-scripts-perl.html 

I have been trying to follow some of the cases described in the link above but ran into some issues installing the needed perl dependencies.

It would be awesome if we can add NixOS to the list of OS that allow us to use this feature.

**Comment by rbvermaa** [comment]
This is not a nixops issue.

**Comment by mdallali** [comment]
My bad. It should go under nixpkgs right?

**Comment by edolstra** [comment]
Yes please.
