### ISSUE TITLE
Error after introducing network argument

### ISSUE THREAD

**Issue by ArturSoler** [NixOS/nixops#278]
In an otherwise working configuration, I added an argument

```nix
{
  base_domain, ...
}:
...
```
and then added a value for it for the only existing domain:

```nixops set-args --arg base_domain "mybasedomain.com" -d webserver-vbox```

However, after doing that, running `nixops info -d webserver-vbox` or `nixops deploy -d webserver-vbox` presents the following error:

```
error: undefined variable ‘mybasedomain’ at "(string)":1:17
error: evaluation of the deployment specification failed
```

**Comment by rbvermaa** [comment]
The error mentions: mybasedomain. It seems you are using somewhere in your expression the variable 'mybasedomain' that is not defined.

**Comment by rbvermaa** [comment]
Try using --argstr in stead, or escape the "'s in the --arg argumen

**Comment by ArturSoler** [comment]
With `--argstr` it worked fine, thanks!
