### ISSUE TITLE
Do you really need docker or container services?

### ISSUE THREAD

**Issue by rowhit** [NixOS/nixops#296]
Hi All,

I am not sure if this is the right place to ask this question please redirect me where it may be more appropriate. I started with intention to create a private cloud for myself with 5 servers. I looked at various options including Juju/MAAS, CloudStack, Docker, Kubernetes et al. I did come across NixOS last year while learning Haskell and really liked the idea. Due to my inexperience I remained with Ubuntu. But now after understanding several aspects of cloud deployment I am in serious doubt as what is the way to go. I really like the philosophy of NixOS which produces a repeatable environment, which is all docker etc containers are trying to provide with huge overheads. However, I like the idea proposed by Kubernetes where you can create High Availability environment with Docker/Rkt containers with CoreOS (using systemd, fleet, etcd. I believe even NixOS can do that with those piece of software installed here) which can be migrated to any computer without you having to worry. You just specify the service with containers and rest is taken care by Kubernetes with services similar to flannel etc. So, my question is if it is possible to get native support for the NixOS container in Kubernetes to avoid the unnecessary overhead introduced by containers.

**Comment by rbvermaa** [comment]
This doesn't really seem to be an issue, but more some thought for a discussion. Perhaps you can post this to the nix-dev mailing list? https://nixos.org/nixos/community.html
