### ISSUE TITLE
Yesod

### ISSUE THREAD

**Issue by sheganinans** [NixOS/nixops#301]
This isn't exactly a problem with nixops itself, but more of a request for guidance. I'm trying to get Yesod working on an AWS instance using nixops and I'm not exactly sure how to get around to doing it and I can't find anyone else who has documented how they did it. I was wondering if anyone had any experience doing such and when I get it working I'd be more than happy enough to contribute code snippets on how I got it done.

My best guess is to have in network.nix disable restarting on deployment and in default.nix check if keter is running, if its not, start it and have it pointed to $out/incoming/, then simply push the deps into $out/incoming/.

**Comment by wavewave** [comment]
In my case, I am using yesod as a systemd service. In `/etc/nixos/configuration.nix` (standalone) or some nix file to describe the deployed network (nixops), you can specify your service like the following.
Note that environment variables can be set there (MYENVVAR1,MYENVVAR2) 
```
 systemd.services.myyesod = {
        description = "myyesod";
	after = [ "network.service" ];
	wantedBy = [ "multi-user.target" ];
	enable = true;
	environment = {
           MYENVVAR1="ABC";
           MYENVVAR2="DEF";
	};
	serviceConfig = {
	  Type = "simple";
          User = "myyesod";
	  WorkingDirectory = "/home/myyesod";
	  ExecStart = ''${myyesod}/bin/myyesod'';
	  ExecStop = "";
	};
      };
    };
```

**Comment by sheganinans** [comment]
Excellent, this seems to solve my problem nicely. I'll give it a try and if it works for me I'll close this issue! Thanks!

**Comment by sheganinans** [comment]
Could you give me an example of the definition of ${myyesod}? I have something like: I know keter is supposed to take a configuration file instead of a bundle, but that is kind of the setup i would like. Maybe I should just drop keter all together?

network.nix:
      systemd.services.yesodapp = {
        description = "yesod staging";
        after = [ "network.service" ];
        wantedBy = [ "multi-user.target" ];
        enable = true;
        environment = {
          PORT="8080";
          MYENVVAR2="DEF";
        };
        serviceConfig = {
          Type = "simple";
          User = "sheganinans";
          WorkingDirectory = "/home/sheganinans";
          ExecStart = ''
              ${keter}/bin/keter ${app}/incoming
          '';
          ExecStop = "";
          Restart = "always";
       };
     };

default.nix (repo points to github.com/NixOS/nixpkgs):

{ pkgs ? import <nixpkgs> {}, repo ? import <repo> {} }:
let

  stdenv = pkgs.stdenv;

  ghcp = repo.haskell-ng.packages;

  ghc710 = ghcp.ghc7101;
  ghcjs  = ghcp.ghcjs;

  hsEnv = ghc710.ghcWithPackages (hs: with hs; ([
    zlib
    yesod
    yesod-bin
    keter
    ]));

in rec {
  app = stdenv.mkDerivation {
    name = "app";
    src = ./.;
    buildInputs = with pkgs; [
      hsEnv

      postgresql
      zlib
      ];
    # This is useful for using this package with --run-env: the PORT environment variable
    PORT = "8888";
    extraCmds = with repo; ''
      export LD_LIBRARY_PATH+=:${zlib}/lib
      '';
    installPhase = ''
      mkdir -p $out/incoming
      cp ehr-server.keter $out/incoming/
    '';
  };
}

**Comment by rbvermaa** [comment]
I am closing this issue, as it is not a nixops issue. Feel free to discuss further here or via mail / mailinglist etc.
