### ISSUE TITLE
Bash completion

### ISSUE THREAD

**Issue by shlevy** [NixOS/nixops#307]
Would be nice to have :smile:

**Comment by domenkozar** [comment]
https://argcomplete.readthedocs.org/en/latest/

**Comment by garbas** [comment]
or just move away from argparse and use [click](http://click.pocoo.org/)

**Comment by domenkozar** [comment]
The nix package should just copy https://argcomplete.readthedocs.io/en/latest/#activating-global-completion to the correct place.

**Comment by coretemp** [comment]
In which commit has this been implemented?

**Comment by AmineChikhaoui** [comment]
This wasn't implemented and I don't understand why @shlevy closed it ?

**Comment by domenkozar** [comment]
He decided to close a lot of issues, whatever, I'll just open another one.

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixops/issues/849
