### ISSUE TITLE
nixops fails when using fetchgit

### ISSUE THREAD

**Issue by globin** [NixOS/nixops#320]
This fails if hydra hasn't been instantiated yet at https://github.com/NixOS/nixops/blob/master/nixops/deployment.py#L304 with 
```
error: cannot import ‘/nix/store/9gb5afcq87kmz2ylpkrd0przgc28alhb-hydra-fc16c53/hydra-module.nix’, since path ‘/nix/store/b1mnfnkgny1fbi2rlp43s8byv29c3vkz-hydra-fc16c53.drv’ is not valid, at /nix/store/jcn0fckjwisxc000xxqmh316bgl2s8hi-nixos-15.06pre65267.6ad8fab/nixos/nixpkgs/lib/modules.nix:96:73
```

```nix
{
  hydra =
    { config, pkgs, ... }:
    let
      hydraCode = (import <nixpkgs> {}).fetchgit {
        url = "https://github.com/NixOS/hydra";
        rev = "fc16c53886";
        sha256 = "0dy20iimgfqpknyzs8rv78sm5yqpsxav2w3cbxf3r219wcwg437g";
      };
    in {
      require = [
        "${hydraCode}/hydra-module.nix"
      ];
      .....
      services = {
        hydra = {
          enable = true;
          dbi = "dbi:Pg:dbname=hydra;host=localhost;user=hydra;";
          package = (import "${hydraCode}/release.nix" {}).build.x86_64-linux;
          hydraURL = "https://hydra.example.com";
          port = 3000;
          minimumDiskFree = 5;
          minimumDiskFreeEvaluator = 2;
          notificationSender = "hydra@example.com";
          logo = null;
          debugServer = false;
        };
        ....
      };
    };
}
```

**Comment by maurer** [comment]
This doesn't fix the underlying problem, but a workaround I used was to split your let declaration for `hydraCode` into a separate .nix file, then run `nix-instantiate hydra.nix` before running.

Contents of my `hydra.nix`
```
(import <nixpkgs> {}).fetchFromGitHub {
  owner  = "NixOS";
  repo   = "hydra";
  rev    = "f8141fdc98f0c0d679c87111df13784fd8909350";                          
  sha256 = "1hmy4wby6lw14yfsp4j6zhjspd9jbs3n6wljjp5qb4s0xp2fa5ak";              
}
```

edit to your main network/machine file:
```
let hydraCode = import ./hydra.nix; in
```
instead of your other stuff.

Every time you change `hydra.nix`, and after each gc (unless you want dangling roots by adding a root), re-run `nix-instantiate hydra.nix`.

Hopefully nixops devs get us a proper fix some day, but this may tide you over.

**Comment by globin** [comment]
Yeah I'm doing something similar where I have all my code which needs instantiating be imported in a bootstrap.nix I nix-instantiate first. But thanks :panda_face:

**Comment by aszlig** [comment]
This is related to NixOps not using read-write-mode by default, so you can use the `--read-write-mode` flag instead, see #291 and #279.

**Comment by aszlig** [comment]
@globin: Does this still persist after 377e4fa6137d959c44dfe2a8c23fa9dad6cc0de2?

**Comment by globin** [comment]
Ah no forgot to close, thanks!
