### ISSUE TITLE
Trivial virtualbox example hangs forever waiting for IP address

### ISSUE THREAD

**Issue by anderspapitto** [NixOS/nixops#329]
Following the example VirtualBox deployment in the NixOps manual causes the deploy stage to hang forever waiting for an IP address. The symptoms are identical to an old report here (http://lists.science.uu.nl/pipermail/nix-dev/2013-December/012301.html), but the fix does not apply - I already have everything virtualization-related enabled in the UEFI firmware settings.

I'm on current NixOS unstable (389c90aa868f16165610b1efe34f344a02105ab6).
My environment.systemPackages includes [ pkgs.nixopsUnstable pkgs.linuxPackages.virtualbox ].
I have services.virtualboxHost.enable = true;

other than that I don't see any other relevant settings. I also cleaned my virtualbox settings with `rm -rf ~/.config/VirtualBox`.

**Comment by alexmingoia** [comment]
Do you have a virtualbox network interface `vboxnet0` with DHCP server running?

**Comment by domenkozar** [comment]
Are you using VirtualBox 5.0? #332

**Comment by domenkozar** [comment]
Should be fixed now using unstable nixops and unstable `releast-15.09` branch
