### ISSUE TITLE
GitHub links to modules broken in manual

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixops#331]
For example, http://hydra.nixos.org/job/nixops/master/tarball/latest/download-by-type/doc/manual#ch-options links to `file:///nix/store/...` rather than `https://github.com/NixOS/nixops`.

This is caused by an outdated test in `nixos/doc/manual/options-to-docbook.xsl`:
```
            <xsl:when test="$revision != 'local' and contains(@value, 'nixops') and contains(@value, '/nix/')">
              <xsl:attribute name="xlink:href">https://github.com/NixOS/nixops/blob/<xsl:value-of select="$revision"/>/nix/<xsl:value-of select="substring-after(@value, '/nix/')"/></xsl:attribute>
            </xsl:when>
```
I.e. this checks for the presence of `nixops` in the path. However, when building from Hydra, the directory is called `git-export` rather than `nixops`.

**Comment by tg-x** [comment]
just noticed this as well, would be good to fix

**Comment by domenkozar** [comment]
Fixed in https://github.com/NixOS/nixpkgs/commit/5260686aa84dea2e2810d88789ab251f09ef2a0e and https://github.com/NixOS/nixops/commit/80d64d8569040f30a0254ee2f428c85e1b9639f7

Successfully built NixOS and NixOps manuals.
