### ISSUE TITLE
Deploying to Hetzner vServer fails

### ISSUE THREAD

**Issue by FRidh** [NixOS/nixops#333]
This is my first attempt at deploying with nixops (using `nixops-1.3pre-cefcd9ba`). Unfortunately it fails:
```
server1> building Nix bootstrap installer... error: attribute ‘system’ missing, at /nix/store/lbizhgj9lvb9hjaa4dflnpnfaihc4g1m-nixos-15.08pre67375.f423ba3/nixos/nixpkgs/nixos/modules/installer/tools/tools.nix:43:14
(use ‘--show-trace’ to show detailed location information)
error: Command '['nix-build', '/nix/store/iak59y4hn1qa3im86hppyfm1bbdyshlv-nixops-1.3pre-cefcd9ba/share/nix/nixops/hetzner-bootstrap.nix', '--no-out-link']' returned non-zero exit status 1
```

**Comment by rbvermaa** [comment]
Could you try to use nixos 14.12 (stable) in stead of unstable? Will look into why unstable is currently is having this evaluation error.

**Comment by rbvermaa** [comment]
I have found the reason for the evaluation error. Will push a fix today. Until then, you can use 14.12 to bootstrap your machine, and upgrade to unstable if you need to after the bootstrap.

**Comment by FRidh** [comment]
Thanks Rob. By the way, do you mean 14.12 as host, target or the 14.12 version of NixOps (1.2)?
I couldn't find anything in the NixOps manual regarding Nix channels. Does NixOps use the channel of the host for the targets by default? 

I did see the -I option, and passing it like I do with nix-shell (that is, point to a repository that was in this case checkout out to the release-14.12 branch) with both `nixops create` and `nixops deploy` result in the same error. Also when using `nixops-1.2`.

**Comment by rbvermaa** [comment]
nixops uses nixpkgs from your NIX_PATH via <nixpkgs>. You can indeed also use the -I option, e.g. -I nixpkgs=/path/to/nixpkgs-14.12

**Comment by rbvermaa** [comment]
4d1a570 should fix your evaluation error.

You can build nixops from a clone:
  $ nix-build -A build.x86_64-linux release.nix
