### ISSUE TITLE
Allow relative paths for networkExprs

### ISSUE THREAD

**Issue by teh** [NixOS/nixops#334]
I've tried editing the sqlite file to use a relative path but that doesn't work:

```
$ nixops info
error: string ‘./service/main.nix’ doesn't represent an absolute path, at /nix/store/wxygxgy2fwmyczmmj77cgk3zw4j4rma6-nixops-1.3/share/nix/nixops/eval-machine-info.nix:19:16
```

I found a workaround by exporting, editing then importing the statefile with the following expression (and adjusting the nix-path accordingly) but it's not super pretty.

```
    "nixExprs": "[\"<main.nix>\"]",
```

**Comment by edolstra** [comment]
Relative to what?

**Comment by teh** [comment]
Relative to the path where nixops runs.

Context: We have a shared (git-crypt-ed) git repository with the nixops configs and state files in them. Those get cloned to different locations on the devs systems (e.g. different home dirs) so invoking nixops doesn't work because the path in the state file doesn't exist on a different system.

**Comment by edolstra** [comment]
But I don't want that. If I do `nixops create ./foo.nix`, I then expect `nixops deploy` to work regardless of my current directory.

**Comment by rbvermaa** [comment]
Perhaps it is an idea to allow path on NIX_PATH to be used?

**Comment by edolstra** [comment]
What does that mean?

**Comment by rbvermaa** [comment]
Example:

    $ nixops create -d mydeploy "<nix/network.nix>" ....

Then on nixops deploy it would resolve it.

**Comment by edolstra** [comment]
IIRC that already works.

**Comment by rbvermaa** [comment]
whoops, never mind then :)

**Comment by teh** [comment]
OK, that makes sense. I'll close and we'll run with the `'<network.nix>'` solution. Thanks!
