### ISSUE TITLE
Use private IP addresses to route GCE traffic if available

### ISSUE THREAD

**Issue by oconnorr** [NixOS/nixops#337]
EC2 instances already do this.  See https://github.com/NixOS/nixops/blob/a932a9ecec15336a55f2aa2c2a20f08264adb837/nixops/backends/ec2.py#L247

We just need to make the GCE code also override address_to.

This could save users money because, according to my reading of the price sheet, connections through network IP addresses in the same zone are free, but the same connection through external IP are charged.

**Comment by aszlig** [comment]
Cc: @Phreedom

**Comment by moretea** [comment]
I'd like to implement this. Can I claim this issue? /cc @Phreedom @aszlig @oconnorr.
I encountered this myself when I tried to setup a mesos cluster on GCE; by default all ports except 22, 80 and 443 are closed on the external IP by the google's firewall. By setting the hostname to the internal IP, we circumvent google's firewall.

**Comment by rbvermaa** [comment]
@moretea that would be great. Do you think you will implement this soon? We are trying to get 1.4 release out soon (this week preferably).

**Comment by Phreedom** [comment]
would be nice to have this 
implemented
