### ISSUE TITLE
libvirtd error: missing executable qemu-kvm

### ISSUE THREAD

**Issue by teozkr** [NixOS/nixops#345]
This seems to have been replaced by the `kvm` command after the QEMU/KVM merge.

**Comment by domenkozar** [comment]
@teozkr are you sure? I have `/nix/store/6594zqn508dmmljgxkiim9f8dbfzr09l-qemu-x86-only-2.4.1/bin/qemu-kvm`

**Comment by teozkr** [comment]
@domenkozar 

I'm using Arch and Ubuntu on my hosts, not NixOS, so I can't speak for that.

I just tried (under Arch), and it seems like first installing `qemu-x86-only` with `nix-env` makes it work (well, makes that part work), while otherwise there is neither a `qemu-kvm` nor a `kvm`.

**Comment by domenkozar** [comment]
@teozkr so what's the name of qemu-x86-only on Arch? I think we really do name that binary ourselves.

**Comment by teozkr** [comment]
@domenkozar Sorry, I'll have a look at it later today. That said, perhaps it ought to be pulled in as a Nix dependency instead?

**Comment by teozkr** [comment]
@domenkozar Yup, seems like it's from https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/virtualization/qemu/default.nix#L57 .

Arch doesn't seem to have an equivalent of qemu-x86-only, but it's just the regular qemu package with an extra build flag from what I can tell, which Arch does have.

**Comment by domenkozar** [comment]
Right, we have to use `qemu-system-x86_64` or `qemu-system-i386`

**Comment by domenkozar** [comment]
Fixed, thanks @teozkr for the report!

**Comment by teozkr** [comment]
Thanks!
