### ISSUE TITLE
libvirtd: lease format changed

### ISSUE THREAD

**Issue by teozkr** [NixOS/nixops#346]
Seems like the leases are no longer stored by dnsmasq in `/var/lib/libvirt/dnsmasq/blah.leases`, but are instead managed by libvirtd itself. They can be pretty-printed by `virsh net-dhcp-leases blah`, but presumably the API has a nicer way to obtain the leases...

**Comment by domenkozar** [comment]
@teozkr this is fixed by https://github.com/NixOS/nixops/pull/374

**Comment by domenkozar** [comment]
@rbvermaa this can be closed now.
