### ISSUE TITLE
Option `deployment.keys` fails to deploy keys

### ISSUE THREAD

**Issue by Nekroze** [NixOS/nixops#357]
Hello,

I am using Nixops 1.3 and deploying to VirtualBox as a test with the Nixos 15.09 channel. I have some SSL keys I want to deployment to include and store on the resulting deployment.

The problem is that the keys on the end machine do not exist. The `/run/keys` dir just contains an empty file called `done`.

Initially, I was trying to give the contents of the keys by using built-in functions to read the text from a file. In case this was causing the issue I attempted to specify a key exactly as in the Nixops Manual which also did not arrive at the resulting server.

This seems like a rather big issue, but no one on IRC responds when I ask about it so hopefully whoever monitors these issues is a bit more interested.

Other than this issue, absolutely love Nixops and the whole Nix ecosystem, love your work!

**Comment by rbvermaa** [comment]
I cannot reproduce your issue. With nixops 1.3 and VirtualBox backend and the following nixops expression, it works for me:

    {
      machine =
        { deployment.targetEnv = "virtualbox";
          deployment.keys.rob.text = "asd";
        };
    }

Can you give some more information/context, or perhaps share some of your nix file you are using?

**Comment by Nekroze** [comment]
Hi @rbvermaa,

Thanks for the response. I have tested your expression and confirmed the keys worked. I am currently rebuilding my config based on that working expression piece by piece until I find out what is causing the keys to not be included in my deployment.

Unfortunately I have not got the time at the moment to clean my config files of any partially sensitive information in order to post them but I will look at doing this if I cannot narrow down the cause.

**Comment by Nekroze** [comment]
I have found the cause and its a bit weird. I am still new to functional languages in many ways so maybe it makes sense to you Nix-heads but I dont get it.

I wanted to use parameters to create, with the same expressions, a live and a test deployment.

This is a minimal config that fails to send keys:

    { testenv ? true }:
    {
      tester = { config, ... }:
      {
        deployment.keys.rob.text = "asd";
      } // (if testenv then {
        deployment.targetEnv = "virtualbox";
        deployment.virtualbox.headless = true;
      } else {
        deployment.targetEnv = "none";
        deployment.targetHost = "192.168.1.2";
      });
    } // (if testenv then {
      network.description = "Test";
    } else {
      network.description = "Live";
      network.enableRollback = true;
    })

However If I change the if statements to if not's and leave the else empty like this than the key sends.

    { testenv ? true }:
    {
      network.description = "Test";
      tester = { config, ... }:
      {
        deployment.keys.rob.text = "asd";
        deployment.targetEnv = "virtualbox";
        deployment.virtualbox.headless = true;
      } // (if ! testenv then {
      } else {});
    } // (if ! testenv then {
      network.description = "Live";
      network.enableRollback = true;
    } else {})

Can anyone confirm my results and or explain them?

**Comment by basvandijk** [comment]
@Nekroze you shouldn't merge NixOS modules that way. 

What you are doing is similar to this:

```nix
nix-repl> ({foo.bar = 1;} // {foo.qux = 2;}).foo
{ qux = 2; }
```

I guess the result you were expecting was:

```nix
{bar = 1; qux = 2;}
```

Why is this happening? Well, the previous expression is equal to:

```nix
nix-repl> ({foo = {bar = 1;};} // {foo = {qux = 2;};}).foo
{ qux = 2; }
```

The [// operator](http://nixos.org/nix/manual/#table-operators) merges the two sets but overwrites any attribute in the left set with the same attribute in the right set.

To do what you want you need to use the [mkMerge](http://nixos.org/nixos/manual/#idm140737316712272) function. As in something like:

```nix
tester = { config, ... }: mkMerge [
  {
    deployment.keys.rob.text = "asd";
  }

  (if testenv then {
  deployment.targetEnv = "virtualbox";
  deployment.virtualbox.headless = true;
  } else {
  deployment.targetEnv = "none";
  deployment.targetHost = "192.168.1.2";
  });
];
```

**Comment by Nekroze** [comment]
@basvandijk I see...

I am still new to functional programming languages so I the flaw in logic was my own I guess, it just seems very unintuitive to have to do it this way.

Thanks for explaining this mate. I will close this off as the issue is me. :)
