### ISSUE TITLE
NixOps - VirtualBox - "kernel driver not accessible"

### ISSUE THREAD

**Issue by markWot** [NixOS/nixops#370]
When I start VirtualBox without Nixops, I can create and use virtual machines without any problems.
But when I try to deploy a vm with nixops (as a not-root-user), I get the error "kernel driver not accessible".

My configuration.nix looks like this:

```
...
virtualisation = {
    virtualbox = {
      host.enable = true;
    };
    libvirtd.enable = true;
  };
...
  users.extraUsers.markus = {
    isNormalUser = true;
    uid = 1000;
    description = "Markus Wotringer";
    extraGroups = [
      "users"
      "wheel"
      "disk"
      "networkManager"
      "audio"
      "video"
      "libvirtd"
      "kvm"
      "vboxusers"
    ];
  };
  users.extraGroups.vboxusers.members = ["markus"];
```

My machine.nix looks like this:

```
{
  network.description = "Jenkins Server";
  jenkins = {config, pkgs, ...}:
  {
    services.jenkins = {
      enable = true;
    }; 
    networking.firewall.allowedTCPPorts = [ config.services.jenkins.port ];
    deployment = {
      targetEnv = "virtualbox";
      virtualbox.memorySize = 1024;
    };
  };
}
```

I do the following shell commands:

```
nixops create machine.nix -d machine
nixops deploy -d machine # <- ERROR
```

The same commands as root yield no errors.

**Comment by aszlig** [comment]
@markWot: Can you please paste the exact error message you get from NixOps?

**Comment by markWot** [comment]
![bildschirmfoto - 08 12 2015 - 07 10 35](https://cloud.githubusercontent.com/assets/3933454/11649067/01bb66c8-9d7b-11e5-94d2-d139184aaabe.png)

**Comment by aszlig** [comment]
@markWot: What do you get by issuing `type VBoxManage`?

**Comment by markWot** [comment]
```
[markus@y510p:~]$ type VBoxManage
VBoxManage ist /home/markus/.nix-profile/bin/VBoxManage
[markus@y510p:~]$ sudo su
[root@y510p:/home/markus]# type VBoxManage
VBoxManage ist /run/current-system/sw/bin/VBoxManage
```

**Comment by aszlig** [comment]
@markWot: You need to remove VirtualBox from your user environment, because if you're running in hardened mode on your host, only the store paths referenced by the suid wrappers can have access to the kernel modules.

**Comment by markWot** [comment]
Yes, it is resolved!!11! 
I had it installed in the user-environment, in the system-environment and also used `virtualisation.virtualbox.host.enable`, after removing all traces of VBox, rebuilding and afterwards just using the latter, it works.

Thank you very much@azlig.
