### ISSUE TITLE
IPs of machines with the backend none aren't tracked

### ISSUE THREAD

**Issue by teozkr** [NixOS/nixops#373]
They're not listed in /etc/hosts, and their IPs are listed as blank in "nixops info".

**Comment by aszlig** [comment]
What do you mean by "not listed in /etc/hosts"? They do not contain host entries for each other?

And yes, we should probably show the IP addresses in `nixops info`.

**Comment by teozkr** [comment]
Exactly. They contain their own IP (and presumably the IPs of any cloud machines, but I haven't tested that), but not each other's. They also don't seem to have any privateIPv4 property, but I can work around that with nix code.

**Comment by domenkozar** [comment]
@teozkr if you provide a bit more detailed information (what's the current state vs. expected), someone might give it a go.

**Comment by kevincox** [comment]
This also prevents setting up encrypted tunnels as the `machine-unencryted` hostname doesn't exist.

**Comment by kevincox** [comment]
For the record my `/etc/hosts` looks like this:

```
127.0.0.1 localhost
::1 localhost

127.0.0.1 s7-encrypted
```

I would expect it to have all the rest of my servers in it as well.
