### ISSUE TITLE
Option to disable /etc/hosts population

### ISSUE THREAD

**Issue by ryanartecona** [NixOS/nixops#380]
If I want to do my own orchestration (say, via consul), I'd rather not have a bunch of stuff in /etc/hosts that both doesn't get used, and may even be out of date if I prefer to deploy to specific machines over deploying to all machines in a deployment.

I'm not sure how best this should be handled. Should it be a new option in nix/options.nix, default to the old behavior for compatibility, with a new conditional [somewhere around here](https://github.com/NixOS/nixops/blob/master/nixops/deployment.py#L395-L399). Anything else?

I'm happy to submit a patch for this if this is the way to go, and if I can get a little guidance.

**Comment by domenkozar** [comment]
Shouldn't you really change https://github.com/NixOS/nixops/blob/master/nixops/deployment.py#L498

**Comment by domenkozar** [comment]
I think you're able to `mkForce` extraHosts in Nix itself without modifying nixops.

**Comment by ryanartecona** [comment]
Oh! You're right!

I completely missed that in reading through deployment.py, but things are making more sense now. Extrapolating, I suppose that means I can `mkOverride` and `mkForce`, etc., all the options that appear in `nixops show-physical`? This may be my inexperience with NixOS modules speaking, but that was completely unintuitive on reading through `nixops -h` and the manual, but is really good to know.

Anyway, thanks @domenkozar!
