### ISSUE TITLE
nix/virtualbox-image-nixops.nix relies on obsolete "jobs" hierarchy

### ISSUE THREAD

**Issue by peti** [NixOS/nixops#381]
The `jobs` hierarchy has been removed from Nixpkgs `master`, causing attempts to update a running VBox instance with Nixops will fail. It appears that `nix/virtualbox-image-nixops.nix` and `nix/ssh-tunnel.nix` still rely on that old code.

**Comment by globin** [comment]
see #379

**Comment by domenkozar** [comment]
Fixed in master.
