### ISSUE TITLE
IP addresses steal

### ISSUE THREAD

**Issue by Ahmeda10** [NixOS/nixops#388]
IP addresses IP1 that were associated to deployment A were removed from its Nix expressions and were associated to deployment B. Then when deploying deployment A with different IP addresses IP2, it "stole" its old IP addresses IP1 from deployment B (and did not associate them to its servers as it was configured to use other addresses: IP2 ).
This bug was confirmed by one of the NixOps developers.

**Comment by rbvermaa** [comment]
Fixed in af75e51
