### ISSUE TITLE
Support ~/.aws/credentials

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixops#396]
NixOps has an ad hoc configuration file `~/.ec2-keys` for AWS credentials. However, there is a standard mechanism for storing AWS credentials: `~/.aws/credentials` (http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html). So it would be nice to use that instead.

**Comment by ip1981** [comment]
NixOps' killer-feature is symbolic names for credentials:
```
AKIA.................. XXXXXXXXXXXXXXXXXX devops
```

**Comment by rbvermaa** [comment]
We can still support that, as .aws/credentials use 'profiles', which you can see as symbolic names as well.

**Comment by aske** [comment]
I've made a PR #526 adding support for standard shared credentials file.
I've kept `~/.ec2-keys` as a first-priority file, so changes won't bring any surprising effects for nixops users, though should we continue supporting `~/.ec2-keys` as a first choice in the long run?

-- 
A bit more time spent with access keys and the underlying code gave me a though about modifying current usage of `deployment.ec2.accessKeyId`.
Right now it is used for two different things at the same time and you need to account for that in the python code, also in some places documentation even omits its usage as a "symbolic name".

Maybe we should add new option like `deployment.ec2.accessKeyAlias`, deprecate usage of `accessKeyId` in this manner (add a warning or smth) and then after a lot of time passes and everyone is fine with it even remove it.
Code dealing with keys can be simplified a bit then, but mostly it's for keeping things logically separate.

I can move this to separate new issue if it will be considered a good idea.
What do you think?

**Comment by ip1981** [comment]
Yes, I think usage of key id should be avoided.
