### ISSUE TITLE
1st example (nixops deploy -d trivial) fails at "attaching disk ‘disk1’..."

### ISSUE THREAD

**Issue by dckc** [NixOS/nixops#403]
## Basic info

To make sure that we are on the same page:

* Kernel: (run `uname -a`)
Linux pav 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
* System: (NixOS: `nixos-version`, Ubuntu/Fedora: `lsb_release -a`, ...)
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty
* Nix version: (run `nix-env --version`)
nix-env (Nix) 1.10
* Nixpkgs version: (run `nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion`)
"16.03pre76763.be0abb3"
* nixops version
```
$ nix-env -qaP | grep nixops
nixpkgs.nixops                                                           nixops-1.3.1

$ nix-repl '<nixpkgs>'
nix-repl> nixops
«derivation /nix/store/jl1xsy702dx5n9h0qlhkxd90766rb2gx-nixops-1.3.1.drv»
```

## Describe your issue here

I can't get through the 1st example in [3.1. Deploying a VirtualBox VM](https://nixos.org/nixops/manual/#idm140737319349440).

### Expected result

valgrind documentation available at http://192.168.56.101

### Actual result

```
[nix-shell:~/Desktop]$ nixops deploy -d trivial
webserver> creating disk ‘disk1’...
webserver> these derivations will be built:
webserver>   /nix/store/3621bxghhqhrih9asnmvwfb1mifj9p6r-virtualbox-nixops-15.09.495.4e18cdd.vdi.xz.drv
webserver>   /nix/store/7diyyri96534bxiy54f41z29zi8vjmxy-virtualbox-nixops-15.09.495.4e18cdd.vdi.drv
webserver> building path(s) ‘/nix/store/c0f6x54x3a2d8mzkhxcrqavx4978i0lc-virtualbox-nixops-15.09.495.4e18cdd.vdi.xz’
webserver> 
webserver> trying http://nixos.org/releases/nixos/virtualbox-nixops-images/virtualbox-nixops-15.09.495.4e18cdd.vdi.xz
webserver>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
webserver>                                  Dload  Upload   Total   Spent    Left  Speed
100  164M  100  164M    0     0  75515      0  0:38:08  0:38:08 --:--:--  124k
webserver> building path(s) ‘/nix/store/i86s9064wd8mad9889qn3ln74g5cjkf3-virtualbox-nixops-15.09.495.4e18cdd.vdi’
webserver> 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
webserver> Clone hard disk created in format 'VDI'. UUID: 0806d6da-5614-4d10-98d2-1c1ccfbf6c44
webserver> attaching disk ‘disk1’...
webserver> VBoxManage: error: Could not launch a process for the machine 'nixops-22111017-d80f-11e5-8fc5-94de80249a2c-webserver' (VERR_FILE_NOT_FOUND)
webserver> VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component Machine, interface IMachine, callee nsISupports
webserver> VBoxManage: error: Context: "LaunchVMProcess(a->session, sessionType.raw(), env.raw(), progress.asOutParam())" at line 592 of file VBoxManageMisc.cpp
error: command ‘['VBoxManage', 'startvm', u'nixops-22111017-d80f-11e5-8fc5-94de80249a2c-webserver']’ failed on machine ‘webserver’ (exit code 1)
```

### Steps to reproduce

1. nix-shell -p nixops
2. create `trivial.nix` and `trivial-vbox.nix` by copy-and-paste from section 3.1 of the manual
3. `nixops create ./trivial.nix ./trivial-vbox.nix -d trivial`
4. `nixops deploy -d trivial`

**Comment by dckc** [comment]
meanwhile, I booted nixos using a [vagrant box](https://nixos.org/wiki/Vagrant_boxes). In particular: [nixos-15.09-x86_64](https://atlas.hashicorp.com/flyingcircus/boxes/nixos-15.09-x86_64).

**Comment by domenkozar** [comment]
Any chance you ran of out free HDD space?

**Comment by dckc** [comment]
Oops... actually, yes, that is possible. I did have to grow my disk to get the vagrant box to work. I hope to check in the next few days.

**Comment by domenkozar** [comment]
Closing as this seems to be resolved.
