### ISSUE TITLE
nixops won't update or recreate an "Outdated" machine

### ISSUE THREAD

**Issue by radix** [NixOS/nixops#406]
This is more of a request for help than a specific bug, because I'm not sure what's going wrong. Basically, I have a deployment with an "Outdated" machine and nixops is not updating it.

Environment: nixops 1.3.1, EC2 backend.

For a while, it was up and running, while being "Outdated", and my attempts to `deploy` it would just do nothing and print "deployment finished succesfully". I made changes to the server definition and still it would not trigger any changes to the server.

In an attempt to just get it to do _anything_, I stopped the machine, and now it's currently in "Missing / Outdated" state. Even now, a `deploy` will do nothing -- still just printing:

```
building all machine configurations...
infra> deployment finished successfully
```

and leaving the machine in "Missing / Outdated" state.

I've tried passing a number of options to `deploy`, like `--allow-recreate --allow-reboot --always-activate`, but they make no difference. There doesn't seem to be anything very useful in the --debug output.

I've inserted a bunch of `builtins.trace` calls in my server definition, and I can see that it _is_ calling my server function (passing the set with `pkgs` and `config`), and at least evaluating the return value. However, no members within my server set are being evaluated.  This indicates to me that there is some conditional that's preventing the machine from even being considered for an update before my server definition is analyzed.

Can someone give me any pointers? I'm even happy with reading through the code to try to understand my problem more, but I'm completely unfamiliar with the nixops code so a pointer to the relevant place would help.

Thanks.

**Comment by domenkozar** [comment]
What exactly did you change in the server specification?

**Comment by radix** [comment]
@domenkozar for example I added an entry to systemd.services, but as I said earlier the members of my server set aren't even being evaluated (according to `builtins.trace`) -- including these services.

And regardless of that, I would guess that when the server is "Outdated" and/or "Missing" the server should be brought up-to-date even if the server spec didn't change, right?

**Comment by radix** [comment]
I doubt I'll be able to help much more with information on this, since I just ended up destroying all the resources and recreating them from scratch. I'll let you know if it happens again.

**Comment by domenkozar** [comment]
OK, closing for now but please do reopen if it appears again!
