### ISSUE TITLE
nixops destroy fails

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nixops#409]
I just got this with a [recent](https://github.com/NixOS/nixops/tree/e5fb3c50c8a259204b675337791edd67be32d9cb) version of nixops:

```
$ nixops destroy -s state.nixops -d mynet --include myresource                                                                                                                                                                                     [master] 
error: __init__() takes exactly 2 arguments (3 given)
```

**Comment by domenkozar** [comment]
What backend?

**Comment by basvandijk** [comment]
I believe it was the `none` backend.

**Comment by domenkozar** [comment]
Can you still reproduce this? Could you run it with `--debug`?

**Comment by domenkozar** [comment]
@basvandijk please provide more details, a http://sscce.org is the only thing that can help me reproduce such issues.

**Comment by basvandijk** [comment]
@domenkozar I traced it down to a a bug in [this line](https://github.com/NixOS/nixops/blob/v1.3.1/nixops/deployment.py#L1029) in nixops-1.3.1.The parenthesis are in the wrong place. RawValue is applied to two arguments and Call to only one. It should be the other way around.

I see that it has been [fixed](https://github.com/NixOS/nixops/commit/617fec8decc95cb7253d767f65061843ab64df54) some time ago in master.

**Comment by domenkozar** [comment]
Thanks!
