### ISSUE TITLE
Using a specific nixpkgs for a machine/deployment

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixops#414]
Hi, I would like to specify a specific nixpkgs in a deployment specification file. From what I can tell, nixops will always use \<nixpkgs\>. Please consider use cases where one would like to manage multiple machines from one machine that need to use different nixpkgs. It is not good to always have to remember to set the right NIX_PATH before calling nixops.

Is this feature already available, or, could it be added?

Thanks.

**Comment by rbvermaa** [comment]
You can add persistent Nix path, using nixops create/modify. E.g.

    $ nixops create -d my-deploy-1 network.nix -I nixpkgs=/path/to/my/nixpkgs1
    $ nixops create -d my-deploy-2 network.nix -I nixpkgs=/path/to/my/nixpkgs2

**Comment by ambrop72** [comment]
Thanks, I didn't find that, I was searching for stuff like "pkgs" in the manual.
