### ISSUE TITLE
Nixops nixpkg installer gives 404

### ISSUE THREAD

**Issue by folex** [NixOS/nixops#421]
http://hydra.nixos.org/release/nixops/nixops-1.3
If I try to download any package from page, I receive 404
e.g.
http://hydra.nixos.org/build/25115666/nix/pkg/hetzner-nixops-installer-x86_64-linux.nixpkg

I was following https://nixos.org/nixops/manual/

**Comment by domenkozar** [comment]
cc @rbvermaa

**Comment by domenkozar** [comment]
I think best is to correct the manual here.

**Comment by domenkozar** [comment]
Fixed documentation.
