### ISSUE TITLE
AWS: Support changing security groups of an instance in VPC

### ISSUE THREAD

**Issue by fakhreddinebb90** [NixOS/nixops#424]
In VPC, it is possible to change the assignment of security groups for a running instance. It would be great to change the security group assignment for a deployment without having to destroy before deploying.

**Comment by spinus** [comment]
+1 for that feature

**Comment by Bsami** [comment]
Yes, it would be great if NixOps could handle that without destroying the
deployment.
+ 1

2016-05-11 23:28 GMT+01:00 Tomasz Czyż <notifications@github.com>:

> +1 for that feature
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/NixOS/nixops/issues/424#issuecomment-218609296>
>



-- 
*Mr Sami*
* BOUHLEL*DevOps & Security Engineer
E-mail: *bs.sami90@gmail.com <bs.sami90@gmail.com>*
PGP Key ID: 0x8DB6B84C
Mobile: *(+216) 21 573 575*
