### ISSUE TITLE
Hetzner improvements wishlist

### ISSUE THREAD

**Issue by danbst** [NixOS/nixops#429]
I've been deploying to hetzner root server last day (with multiple failures) and would like to leave some feedback.

1 When redeploying kickstart partitioning, message `Connection to MY_IP closed by remote host.` injects into output log. This was frightening at first, because initial deploy had no such 

```
hetznerIron> installing machine...
hetznerIron> rebooting machine в??hetznerIronв?T (MY_IP) into rescue system
hetznerIron> sending reboot command... done.
hetznerIron> waiting for rescue system...Connection to MY_IP closed by remote host.
[down]..............................................................[up]
```

2: Default kickstart script doesn't work for new NVMe servers, default disks are not `sda,sdb`, but `nvme0n1,nvme1n1`
3: No example for LVM over RAID, and currently I couldn't find out how to do this
4: nixpart exceptions are frightening too, though not critical. See also https://github.com/aszlig/nixpart/issues/8
5: When nixpart exception occurs, I'd like a prompt "Would you like to enter rescue shell?".
5.1 NixOps does smth to my server, so I cannot access it. I go to Robot interface, reboot (or reboot in rescue) and can login. But after that nixops cannot login. To fix NixOps, I do this:
`nixops destroy -d hetzner`. Now nixops will create new robot account, with new root password.
5.2 NixOps does smth to my server, so I cannot access it. I figured out, I can `nixops export -d hetzner` and grep for password. I think password should be shown after nixpart error (ssh connection string is shown, this is good). But I am constantly running into security violations with `.ssh/known_hosts`, so manual logging into shell is kind of pain every time.
6: Imagine nixpart failed. You fix kickstart config and rerun deploy. Why NixOps reboots instance into rescue shell again? This takes time. There should be an option (or default) to reuse existing session for partitioning operations in rescue shell. I've done redeploy 20 times (always failed), and each time waited for instance reboot to be notified that partitioning failed.
7: BTW, I couldn't get LVM partitions with nixpkgs-15.09. I'm investigating into it currently (trying to build from nixops and nixpkgs master)
8: If instance reboot is nessecary, maybe build system BEFORE reboot? When building system fails (because of upstream problem, for example), it's annoying to wait system boot and see `error: build of "/nix/store/akrjra7z0gi4b42avr52hnzq25jbg6xz-hetzner-nixops-installer.drv" failed`.
9: (Not nixops complain, but maybe somebody knows) I didn't get bootable instance with this partitions and nixpkgs-15.09

```
clearpart --all --initlabel --drives=nvme0n1,nvme1n1

part raid.01 --size=4000 --fstype=swap --ondrive=nvme0n1
part raid.11 --size=4000 --fstype=swap --ondrive=nvme1n1

part raid.02 --size 20000  --fstype=ext4 --ondrive=nvme0n1
part raid.12 --size 20000  --fstype=ext4 --ondrive=nvme1n1

part raid.03 --size=1 --grow   --fstype=ext4   --ondrive=nvme0n1
part raid.13 --size=1 --grow   --fstype=ext4   --ondrive=nvme1n1

raid swap       --fstype=swap --device=swap --level=RAID1 raid.01 raid.11
raid /          --fstype=ext4 --device=root --level=RAID1 raid.02 raid.12
raid /media     --fstype=ext4 --device=media --level=RAID1 raid.03 raid.13
```

Partitions are there, /boot/grub/grub.cfg point to Nixos to `/dev/md/root`, but no logs found anywhere. I don't know how to debug this too.

**Comment by domenkozar** [comment]
cc @aszlig

**Comment by danbst** [comment]
I've successfuly deployed this instance. Turned out, there were missing `--label` attributes for partitions.
```
#doesn't work
raid swap       --fstype=swap --device=swap --level=RAID1 raid.01 raid.11
raid /          --fstype=ext4 --device=root --level=RAID1 raid.02 raid.12
raid /media     --fstype=ext4 --device=media --level=RAID1 raid.03 raid.13

#works
raid swap       --fstype=swap --label=swap --device=swap --level=RAID1 raid.01 raid.11
raid /          --fstype=ext4 --label=root --device=root --level=RAID1 raid.02 raid.12
raid /media     --fstype=ext4 --label=media --device=media --level=RAID1 raid.03 raid.13
```

Also, another frightening output faced me:
```
hetznerIron> updating GRUB 2 menu...
hetznerIron> installing the GRUB 2 boot loader on /dev/nvme0n1...
hetznerIron> Installing for i386-pc platform.
hetznerIron> Installation finished. No error reported.
hetznerIron> installing the GRUB 2 boot loader on /dev/nvme1n1...
hetznerIron> Installing for i386-pc platform.
hetznerIron> Installation finished. No error reported.
hetznerIron> rebooting...
Connection to MY_IP closed by remote host.
hetznerIron> waiting for the machine to finish rebooting...[down]..........................................[up]
/etc/ssh/ssh_config line 51: Unsupported option "gssapiauthentication"
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:xzHoCvu...
Please contact your system administrator.
Add correct host key in /home/ec2-user/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/ec2-user/.ssh/known_hosts:19
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
hetznerIron> /etc/ssh/ssh_config line 51: Unsupported option "gssapiauthentication"
hetznerIron> /etc/ssh/ssh_config line 51: Unsupported option "gssapiauthentication"
hetznerIron> activation finished successfully
hetznerIron> deployment finished successfully
```

**Comment by domenkozar** [comment]
Could you split out this issue into multiple ones? These big issues never get any attention :)

**Comment by danbst** [comment]
1. https://github.com/NixOS/nixops/issues/568
2. https://github.com/NixOS/nixops/issues/569
3. I lied, I could figure out, but it didn't work. Look 7
4. dunno what to do with this
5.1 https://github.com/NixOS/nixops/issues/571
5.2 https://github.com/NixOS/nixops/issues/572
6. https://github.com/NixOS/nixops/pull/433
7. https://github.com/NixOS/nixops/issues/552
8. I don't actually understand myself, at which phase this problem arises
9. https://github.com/NixOS/nixops/issues/570
