### ISSUE TITLE
`multipath-tools` build fails with Hetzner

### ISSUE THREAD

**Issue by williamhogman** [NixOS/nixops#431]
Hi and Thanks to all you guys for contributing to such an awesome project.

Apologies if this is the wrong place, I'm _very_ new to the whole Nix ecosystem and can't quite tell if this is an issue with Nixops per se. That said, my colleagues and I are having some problems getting started with NixOS. It seems like the dependency `multipath-tools`, which I think is required by the hetzner provisioning scripts, is somehow broken.

Running nixops deploy gives us the following error on our Hetzner boxes.
```
/nix/store/8fngdkhqixp4vjypa74vc5h88chyz0ml-gzip-1.7/bin/gzip -9 -c multipath.8 > multipath.8.gz
gzip: -c: option not valid in GZIP environment variable
Try `gzip --help' for more information.
Makefile:17: recipe for target 'multipath' failed
make[1]: *** [multipath] Error 1
make[1]: Leaving directory '/tmp/nix-build-multipath-tools-0.4.9.drv-0/multipath'
Makefile:39: recipe for target 'recurse' failed
make: *** [recurse] Error 2
builder for ‘/nix/store/zfznwyq9qrgqvrk9pb8p5a4z496sy4w2-multipath-tools-0.4.9.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/0xb98090v7z1aayan4bzkfd0l5iq89z2-blivet-0.17-1.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/59halzvvd77skxxsn2wv15yq0bkfvw45-nixpart-0.4.1.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/ydf6ikmw7dfa98kr5psvz8sy942fzai9-hetzner-nixops-installer.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/ydf6ikmw7dfa98kr5psvz8sy942fzai9-hetzner-nixops-installer.drv’ failed
error: Command '['nix-build', '/nix/store/d576p0pv2m47hgw5aighxwjv8rzap2gw-nixops-1.3.1/share/nix/nixops/hetzner-bootstrap.nix', '--no-out-link']' returned non-zero exit status 100
```

**Comment by domenkozar** [comment]
How can we reproduce? How are you building nixops and using what nixpkgs version?

**Comment by williamhogman** [comment]
Basically I ran `nix-env -i nixops` and then just ran everything (create followed by deploy).`nixops --version` gives me `1.3.1` The package that is failing is multipath-tools-0.4.9. I do think I'm using mainline nixpkgs but I'm uncertain on how to verify.

This is the config I used, having redacted the IP.
```
{
  example = {
    deployment.targetEnv = "hetzner";
    deployment.hetzner.partitions = ''
      clearpart --all --initlabel --drives=nvme0n1,nvme1n1
      btrfs /mnt/data1 --grow --ondisk=nvme0n1 --label=data1
      btrfs /mnt/data2 --grow --ondisk=nvme1n1 --label=data2
      btrfs / --grow --ondisk=sda --label=root
    '';
  };
}
```

**Comment by danbst** [comment]
https://github.com/NixOS/nixpkgs/pull/15359

**Comment by williamhogman** [comment]
Thanks a ton :) close?

**Comment by danbst** [comment]
@williamhogman 
> I'm very new to the whole Nix ecosystem and can't quite tell if this is an issue with Nixops per se.

If you don't want to wait channel update or mess with local nixpkgs repo, you can deploy 16.03 channel with
```
NIX_PATH="nixpkgs=https://nixos.org/channels/nixos-16.03-small/nixexprs.tar.xz"  nixops deploy -d ...
```
Deploy to Hetzner works without any patches in 16.03.

**Comment by williamhogman** [comment]
@danbst Thanks a ton :)
