### ISSUE TITLE
How to upgrade Linux kernel with NixOps when deploying to VirtualBox?

### ISSUE THREAD

**Issue by Gabriel439** [NixOS/nixops#444]
I tried to use NixOps to launch a NixOS machine with Linux 4.4 using the `boot.kernelPackages` field.  Here is the smallest example file that reproduces the issue:

```bash
$ cat example.nix
{ main =
    { config, pkgs, ... }:
      { deployment.targetEnv = "virtualbox";
        deployment.virtualbox.memorySize = 1024;
        boot.kernelPackages = pkgs.linuxPackages_4_4;
      };
}
```

When I deploy the above file and log in the kernel version is sitll 3.18

```bash
$ nixops create -d test example.nix
$ nixops deploy -d test
$ nixops ssh -d test main
$ uname -a
Linux main 3.18.21 #1-NixOS SMP Thu Jan 1 00:00:01 UTC 1970 x86_64 GNU/Linux
```

Is this the correct way to upgrade the kernel?

**Comment by domenkozar** [comment]
@Gabriel439 yes, you have to reboot. NixOps won't reboot for you, see https://github.com/NixOS/nixops/issues/367 as a duplicate to this issue.

**Comment by Gabriel439** [comment]
For the benefit of others who visit this issue, @domenkozar's answer means that you need to supply the `--force-reboot` flag to `nixops deploy` at least once in order for it to upgrade the kernel.  So the fix to my above example would be to just run:

```bash
$ nixops create -d test example.nix
$ nixops deploy -d test --force-reboot
$ nixops ssh -d test main
$ uname -a
Linux main 4.4.7 #1-NixOS SMP Tue Apr 12 16:09:26 UTC 2016 x86_64 GNU/Linux
```

... and now the kernel is upgraded!  Thanks, @domenkozar! :)
