### ISSUE TITLE
Add initial disk size option for virtualbox deployments

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/nixops#453]
Either as an explicit option or allowing the user to overwrite `disks.disk1.size`

**Comment by domenkozar** [comment]
`deployment.virtualbox.disks.disk1.size = 1024;` should work. Doesn't it?

**Comment by expipiplus1** [comment]
@domenkozar not for me, it complained about it being defined multiple times.

For anyone stumbling on this, here's a little script to resize `disk1` on a (sole) machine called $MACHINE on deployment $DEPLOY

```
DISK_FILE=$(nixops export -d $DEPLOY | nix-shell -p jq --command "jq -r '..|.\"virtualbox.disks\"?|select(.!=null)' | jq -r .disk1.path")
nixops stop -d $DEPLOY
VBoxManage modifyhd --resize 64000 $DISK_FILE
nixops start -d $DEPLOY
nixops ssh -d $DEPLOY $MACHINE -- fdisk -u /dev/sda
```
Enter options: `d` `n` `p` `<CR>` `<CR>` `<CR>` `w`
```
nixops reboot -d $DEPLOY
nixops ssh -d $DEPLOY $MACHINE --  resize2fs /dev/sda1
nixops ssh -d $DEPLOY %MACHINE -- df -h
echo good job 👍
```

**Comment by domenkozar** [comment]
Then try `deployment.virtualbox.disks.disk1.size = lib.mkForce 1024;

**Comment by lo1tuma** [comment]
@domenkozar I tried to use `lib.mkForce` as you suggested but it fails with the following error:

```
server> creating disk ‘disk1’...
server> 0%...
server> Progress state: VBOX_E_FILE_ERROR
server> VBoxManage: error: Failed to clone medium
server> VBoxManage: error: Could not create the clone medium '/Users/foobar/VirtualBox VMs/nixops-a8aabe8c-3cb8-11e6-aef7-6c4008a6ccaa-server/disk1.vdi'.
server> VBoxManage: error: VDI: cannot create image '/Users/foobar/VirtualBox VMs/nixops-a8aabe8c-3cb8-11e6-aef7-6c4008a6ccaa-server/disk1.vdi' (VERR_ALREADY_EXISTS)
server> VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MediumWrap, interface IMedium
server> VBoxManage: error: Context: "RTEXITCODE handleCloneMedium(HandlerArg*)" at line 896 of file VBoxManageDisk.cpp
error: command ‘['VBoxManage', 'clonehd', '/nix/store/qmvr8w6qgzjqca0rwcm5f17jy894mj5l-virtualbox-nixops-15.09.495.4e18cdd.vdi', '/Users/foobar/VirtualBox VMs/nixops-a8aabe8c-3cb8-11e6-aef7-6c4008a6ccaa-server/disk1.vdi']’ failed on machine ‘server’ (exit code 1)
```

**Comment by spinus** [comment]
manual says
```
deployment.virtualbox.disks.<name>.baseImage
If set, this disk is created as a clone of the specified disk image (and the size attribute is ignored).
```. 
I would close that issue. If you want resize disk1, build your own image, otherwise you could set disk2 and mount it with "filesystems".

**Comment by spinus** [comment]
There is also autoResize filesystem nixos option, but I assume this would not work as the disk size is set by base image anyway (I mention becasue I saw you did try some resize stuff).

**Comment by apeschar** [comment]
Resizing the disk fails because VirtualBox can only resize VDI files, not VMDK files.

A VMDK file is created because the base image is a VMDK file. (At least on my VirtualBox 5.1.20r114628.)

NixOps does `VBoxManage clonehd base.vmdk disk1.vdi`, but the `.vdi` extension in the output file does not have any meaning to VirtualBox. If one specifies `--format VDI`, then the VMDK input file is converted to VDI. When that is done, the `modifyhd --resize` call also works and all is well!

It seems to me that this option should always be passed to the `clonehd` call, so we actually get a VDI file, not a VMDK file, despite the `.vdi` extension with which the file is created.

**Comment by proger** [comment]
What would be the best place to document the `disk1` key? Examples or defaults? https://github.com/NixOS/nixops/blob/master/nix/virtualbox.nix#L54-L60

**Comment by domenkozar** [comment]
@proger best to put it in the description
