### ISSUE TITLE
Print output of nix-copy-closure

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nixops#455]
I use nixops a lot over slow GSM links and I'm therefore interested in the output of `nix-copy-closure` which tell me [how many bytes will be copied](https://github.com/NixOS/nix/blob/c2d27d30cfe000c4adff91e6cbde63c2a5b92b43/perl/lib/Nix/CopyClosure.pm#L38).

However, [it seems](https://github.com/NixOS/nixops/blob/4c2e6eea6a0db7a84a6023fe0036a984d3ebedf1/nixops/backends/__init__.py#L318) that the stderr output of `nix-copy-closure` is not redirected to the logger.

**Comment by roelvandijk** [comment]
I noticed the following interesting behaviour.

I run `nixops deploy` over a GSM link (4MBit). I get the 
> copying closue... 

message in my terminal. After one hour of steady uploading with ~400KB/sec there is a 

> Timeout, server 1.2.3.4 not responding.
> copying 763 missing paths (3708.72 MiB) to ‘root@1.2.3.4’...

So the message about the size of the missing paths is being send to stderr or stdout, only too late to be useful. It could be related to some buffer not being flushed so the message only ends up in the terminal after additional output is generated. In my case the server timeout message.

**Comment by basvandijk** [comment]
I've looked into this again and concluded that the following is happening:

1. When `nixops` calls `nix-copy-closure` it [binds](https://github.com/NixOS/nixops/blob/ab5256aec4d5cb06e3142ce011c95459736642b2/nixops/util.py#L76) the stderr of the `nix-copy-closure` process to its stdout.

2. `nix-copy-closure` [writes](https://github.com/NixOS/nix/blob/c2d27d30cfe000c4adff91e6cbde63c2a5b92b43/perl/lib/Nix/CopyClosure.pm#L38) the message `"copying %d missing paths (%.2f MiB) to ‘$sshHost’...\n"` to stderr before copying the closure. 

3. Apparently because stdout is buffered in python the message is being shown way too late in the terminal.

Potential solutions:

1. Change `nix-copy-closure` so that it [writes](https://github.com/NixOS/nix/blob/c2d27d30cfe000c4adff91e6cbde63c2a5b92b43/perl/lib/Nix/CopyClosure.pm#L38) its message to STDOUT instead of STDERR. This has the additional advantage that the message is then also forwarded to the nixops logger. 

2. [Disable output buffering](http://stackoverflow.com/questions/107705/disable-output-buffering) of stdout of the nixops process. This might not be desirable because of performance reasons.

3. Change the [logged_exec(command, ...)](https://github.com/NixOS/nixops/blob/ab5256aec4d5cb06e3142ce011c95459736642b2/nixops/util.py#L46) function so that the stderr of the command is bound to a PIPE like it does for stdout. Then in [the loop](https://github.com/NixOS/nixops/blob/ab5256aec4d5cb06e3142ce011c95459736642b2/nixops/util.py#L92) that writes the output to the logger we should also write the data in the stderr pipe to the logger.

Solution 1 seems the simplest and most desirable. @edolstra do you see any problems with that approach?

**Comment by elitak** [comment]
I've encountered the same issue. My workaround is to SIGINT, then run `nix-copy-closure --to the-slow-host /nix/store/system-derivation-in-question` to manually get a time estimate.

My hunch is that changing nix-copy-closure's behavior is the wrong solution. nixops should just disable buffering for certain commands, especially this one.

**Comment by domenkozar** [comment]
Released in Nix 1.11.15
