### ISSUE TITLE
RFC: Multiple Deploy Hosts

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixops#464]
I'm wanting to implement the ability for two machines to maintain the deployment. As far as I can tell, this means sharing the configuration repository, locks, and the database.
- Locking: https://github.com/NixOS/nixops/blob/master/nixops/deployment.py#L201-L223
- Statefile: https://github.com/NixOS/nixops/blob/master/nixops/statefile.py#L58

My proposal is to have a way to use a mysql database (or pgsql, doesn't bother me either way) to hold the database, and a way using mysql to lock and prevent other deploys from happening at the same time. More specifically, the Locking feature would be part of StateFile and not its own implementation in the deployment module.

Before I do all this work,
1. is this an interesting feature which would be accepted upstream?
2. can you provide feedback on this lock refactoring to support this?
3. can you provide feedback on the idea in general?
4. anything else I should know?

Thanks!

**Comment by domenkozar** [comment]
I think if we go this direction, first we'd have to port all SQL code to use SQLAlchemy, then it really doesn't matter which SQL backend is used.

**Comment by grahamc** [comment]
Some sort of abstraction between the nixops business code and the database backend, for sure.

The first question though being, I think, most important.

**Comment by domenkozar** [comment]
@grahamc I'm sure the feature would be useful, but the implementation is important. By refactoring nixops and making it better (each refactoring as it's own PR) would move it into the right direction and would get feedback.

**Comment by grahamc** [comment]
I keep missing emails from github :( sorry, I didn't see this until now. I'll get to work. :)
