### ISSUE TITLE
Deploying ec2 VPC instances without security groups fails

### ISSUE THREAD

**Issue by lo1tuma** [NixOS/nixops#468]
I’ve just tried to use nixops from current `master` branch and it surprisingly fails for a deployment which works perfectly find with nixops `1.3.1`.

I want to deploy a VPC instance per nixops but I don’t want to manage the security groups of the VPC per nixops. In my case there is one security group defined per AWS Web-UI.
The deployment fails with the following error:

```
myServer.....> updating security groups from [u'sg-xxxxxx'] to []...
error: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterCombination</Code><Message>No attributes specified.</Message></Error></Errors><RequestID>6f4b96f5-6b42-4b22-addc-cf58846b5999</RequestID></Response>
```

When I revert commit 6e4802ee92043eacfd8794aa919b39fee906dac7 everything works fine again.

**Comment by rbvermaa** [comment]
Do you mean you have a default security group on your VPC?

**Comment by lo1tuma** [comment]
@rbvermaa Exactly. The security group mentioned in the error message above is the default security group of my VPC.

**Comment by rbvermaa** [comment]
OK, according to http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/VPC_SecurityGroups.html#DefaultSecurityGroup the default security group in a VPC has a fixed name, 'default'.

**Comment by rbvermaa** [comment]
@lo1tuma could you try if the following patch fixes the issue for you?

    diff --git a/nix/ec2.nix b/nix/ec2.nix
    index b38939f..8163789 100644
    --- a/nix/ec2.nix
    +++ b/nix/ec2.nix
    @@ -310,7 +310,7 @@ in
         };
     
         deployment.ec2.securityGroupIds = mkOption {
    -      default = [];
    +      default = [ "default" ];
           type = types.listOf types.str;
           description = ''
             Security Group IDs for the instance. Necessary if starting

**Comment by lo1tuma** [comment]
@rbvermaa With your patch applied everything works again 👍 .
