### ISSUE TITLE
Login using ssh-agent does not work.

### ISSUE THREAD

**Issue by spinus** [NixOS/nixops#472]
NixOps 1.3.1.

I'm creating fresh AWS instance (just simple setup) and I set "deployment.ec2.keyPair" to a name (string, I already have this key set up on AWS).

I started ssh-agent (with ``eval `ssh-agent`) and added private key to it (I can ssh to other boxes with that key, also I can ssh to new box, created by nixops with this key), and I cannot run deploy or ssh commands as nixops complains about ssh key.
When I set ``deployment.ec2.privateKey`` to the absolute key path ssh/deploy command is working.

Do I need to setup something more to make ssh-agent working with nixops?

**Comment by rbvermaa** [comment]
I use SSH agent with nixops on certain deployments, and did not have to do anything for it.

**Comment by spinus** [comment]
mhm, I must do something wrong, but not sure what.

setting keyPairs and having the key in ssh-agent should be enough?

```
$ ssh-add -L                                                     
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCbMQ59kylzVoNAJiuDKfYc+vrYLFI9xjpqOjRPdoD0PNf
$ nixops deploy                                                      
building all machine configurations...
m1> copying closure...
Password:
```

**Comment by spinus** [comment]
It started to work for me, probably I had some crazy setup that time, but I can't reproduce it anyway.
