### ISSUE TITLE
Error deploying users-groups.json on OSX

### ISSUE THREAD

**Issue by gilligan** [NixOS/nixops#477]
```
building path(s) ‘/nix/store/w9r01mp2702jn47sw42qrm5wch4fvn31-users-groups.json’
error: a ‘x86_64-linux’ is required to build ‘/nix/store/yricghikxxidysq5440lznx0nzc43jzz-users-groups.json.drv’, but I am a ‘x86_64-darwin’
error: unable to build all machine configurations
```

Before I ran into the problem that seems to be solved by #412 and now this seems similar.
- `nixops`: 1.4 with #412 applied
- `NIX_PATH`: nixpkgs=https://github.com/NixOS/nixpkgs-channels/tarball/f231b2b3f79020025eaabe4e8fae53e81651914c
- `OSX 10.11.5 (15F34)`

**Comment by domenkozar** [comment]
Also seen in https://github.com/NixOS/nixops/issues/238

**Comment by gilligan** [comment]
This is a rather painful blocker for me. I guess there isn't any way that I could to work around this? #412 also did not look trivial so I guess chances are slim ...

**Comment by domenkozar** [comment]
Merging into https://github.com/NixOS/nixops/issues/560
