### ISSUE TITLE
“argument list too long” error when copying closure

### ISSUE THREAD

**Issue by eikek** [NixOS/nixops#478]
Hello,
I already spammed the list with this. I think it is a bug, maybe I'm just doing something wrong.

I want to deploy to a physical machine. I created this nix file

``` nix
{
  network.description = "Test";
  trivial =
    { config, pkgs, ... }:
    {
      imports =
      [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

      boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "usb_storage" "sd_mod" "sr_mod" ];
      boot.kernelModules = [ "kvm-intel" ];
      boot.extraModulePackages = [ ];
      boot.loader.grub.devices = [ "/dev/sda" ];

      fileSystems."/" =
        { device = "/dev/disk/by-uuid/3bafeea6-2e45-4048-b192-436b5a8f4e3b";
          fsType = "ext4";
        };

      fileSystems."/boot" =
        { device = "/dev/disk/by-uuid/f57eea7e-69d2-4629-af51-0fbff1e1a807";
          fsType = "ext2";
        };

      swapDevices =
        [ { device = "/dev/disk/by-uuid/6488f5b6-9412-4c35-9f1d-ae7bc442410e"; } ];

      nix.maxJobs = pkgs.lib.mkDefault 2;

      services.openssh.enable = true;

      environment.systemPackages = with pkgs;
        let
           tex =           # see https://nixos.org/wiki/TexLive_HOWTO
          # I disable this packages, and deploy to physical machine works
          texlive.combine {
            inherit (texlive) scheme-medium collection-latexextra;
          };
          in [tex];

#      deployment.targetEnv = "container"; #works
       deployment.targetEnv = "none";
       deployment.targetHost = "192.168.1.72";
    };
}
```

I then create the "network" with `nixops create ./trivial.nix -d trivial` which if fine. Then I do a `nixops deploy -d trivial` and the result is (after building the system):

```
trivial> copying closure...
error: [Errno 7] Argument list too long
```

If I remove the `collection-latexextra` from the tex package, the error disappears.

I'm currently using nixops 1.3.1 and 1.4 on NixOS 6.09pre87412.e725c92 (Flounder). It doesn't seem to be a problem when using container or virtualbox backend. Any help is much appreciated.

Thank you a lot for nix/o(p)s!

**Comment by domenkozar** [comment]
Could you try another backend, for example `virtualbox`?

**Comment by eikek** [comment]
Yes, I tried container and virtualbox backends, but I couldn't reproduce it there. Only when deploying to my notebook.

**Comment by domenkozar** [comment]
Bug is then probably in `none` backend code.

**Comment by stepcut** [comment]
I got this same bug when attempting to deploy to 'ec2'. The `collection-latexextra` package was also what triggered it for me.

**Comment by aycanirican** [comment]
Same problem here when deploying to 'ec2'.

**Comment by domenkozar** [comment]
Workaround: https://github.com/NixOS/nixpkgs/issues/25057#issuecomment-297018826

**Comment by domenkozar** [comment]
The problem is that https://github.com/NixOS/nixops/blob/master/nixops/backends/__init__.py#L336 created a too long line.

Possible fix would be:

- to split it up in multiple `nix-store` calls
- remove paths that are part of other closure graph

**Comment by aycanirican** [comment]
I was trying to give max-concurrent-copy but it also failed. `deployment.hasFastConnection = true;` worked. Thank you @domenkozar
