### ISSUE TITLE
ebsOptimized has no effect

### ISSUE THREAD

**Issue by gilligan** [NixOS/nixops#488]
```
deployment.ec2.ebsOptimized = true;
```
- **Expected**: the created instance is reported on aws console as `ebs optimized`
- **Actual**: the created instance is _not_ reported as `ebs optimized` on aws console

**Comment by AmineChikhaoui** [comment]
@gilligan I think you should check this http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSOptimized.html . The instance you deployed doesn't have ebs optimization available most probably. Anyway I was able to deploy a c3.xlarge instance with `deployment.ec2.ebsOptimized = true;` and it shows `"EbsOptimized": true` as well in the output of `aws ec2 describe-instances`

**Comment by domenkozar** [comment]
@gilligan please reopen if this issue persists, but it seems that you indeed deployed an instance that can'be ebsoptimized.
