### ISSUE TITLE
Libvirtd: set root key without overriding root's key

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixops#499]
If the NixOS configuration overrides `users.users.root.openssh.authorizedKeys.keys`, NixOps won't be able to ssh into Libvirtd machine anymore since the key will get replaced.

**Comment by rbvermaa** [comment]
@domenkozar What do you mean exactly with 'overridden' ?

**Comment by domenkozar** [comment]
@rbvermaa the key used to ssh into libvirtd is not longer configured by nixops. So NixOps can't login anymore.

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nixops/blob/master/nix/libvirtd.nix#L31

**Comment by Nadrieril** [comment]
I believe https://github.com/NixOS/nixops/pull/596 does fix the problem then.
