### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by aneeshusa** [NixOS/nixops#504]
Does NixOps support Python 3? I couldn't tell from `setup.py` or the issues, but it looks like it's Python 2 only right now. (I'm waiting for #502 so I can try nixops out.)

I think this would be nice to go along with https://github.com/NixOS/nixpkgs/issues/18185.

**Comment by domenkozar** [comment]
It doesn't support it yet.

**Comment by aske** [comment]
I can try migrating NixOps to python3 (looks like we'll need to use boto3 library; need to check libraries used for non-AWS backends before that, though).

**Comment by aske** [comment]
I'll make the PR to explicitly set python 2 version so we can move further with moving to python3 by default a bit later.

Alright, the rough roadmap right now looks like this:

1. [ ] Migrate to boto3
2. [ ] Upgrade/move to other libs for non-AWS backends
3. [ ] Migrate tests to nose2 (or py.test?)
4. [ ] Do the actual 2->3 migration

**Comment by aske** [comment]
Also, cc @edolstra @rbvermaa I guess, in case they have any comments.

**Comment by domenkozar** [comment]
@aske the plan sounds good. I'd keep nose2 for having a small scope for this somewhat big task.

**Comment by domenkozar** [comment]
Boto3 migration guide: http://boto3.readthedocs.io/en/latest/guide/migration.html

**Comment by aske** [comment]
I hope I'll be able to start working on migrating to boto3 this or next weekend (was a bit swamped with work).

**Comment by bachp** [comment]
I don't think nixops needs to support python2 along side python3. I assume it is mostly installed vis nixpkgs which already has python3 and it can easily be switched there.

Please correct me if I'm wrong.

**Comment by edolstra** [comment]
Yeah, I don't think there's any reason to keep supporting Python 2.

**Comment by teto** [comment]
Any news on the python3 front ? is there a PR one can follow/help with ?

**Comment by domenkozar** [comment]
First we need to migrate to boto3 as per checklist from @aske.

**Comment by aske** [comment]
Hm, hackathon at NixCon looks like the perfect opportunity to finally start working on this.

**Comment by domenkozar** [comment]
Small boto3 progress: https://github.com/NixOS/nixops/pull/749

**Comment by davidak** [comment]
[The clock](https://pythonclock.org/) is ticking...

**Comment by takeda** [comment]
So I pulled the trigger and made somewhat large changes in moving everything to boto3 the dependency is still there, but hopefully there's not much left. The changes I did though require testing, so if anyone could find issues and show the command and backtrace, that might help me fix them.

https://github.com/NixOS/nixops/pull/1186

**Comment by takeda** [comment]
I moved my commits into a new nixops-aws repo: https://github.com/NixOS/nixops-aws/pull/1 since my old PR is no longer valid after dividing nixops into modules.

**Comment by asymmetric** [comment]
Should we close this then?

**Comment by davidak** [comment]
>Should we close this then?

This issue is not yet solved, so no!

>Python 2.7 will not be maintained past 2020.

https://pythonclock.org/

So, to make this tool usable and maintainable past next year, we need to migrate it! We have 3 months and 15 days left...

**Comment by takeda** [comment]
@asymmetric this patch doesn't make nixops python 3 complaint, it targets the dependence on boto which is python 2 only (and no longer supported AFAIK). The changes mentioned in that old PR was splitting nixops into modules so I redone my PR to just target nixops-aws.

@davidak with how things are moving I don't think we will make it in 3 months :) but it's not like python2.7 suddenly will stop from working, although new versions of packages will start breaking as maintainers will stop caring about 2.7.

**Comment by grahamc** [comment]
NixOps is now  python3 only.

**Comment by jonringer** [comment]
it would be nice to expose the python3 version in nixpkgs, seeing as I would like to stop fixing python2 packages to ensure `nixopsUnstable` still builds with the python2 package set. https://github.com/NixOS/nixpkgs/pull/95609#issuecomment-674664713

**Comment by dotlambda** [comment]
Are there any plans to make the Python 3 versions of NixOps the default for 21.05?

**Comment by mweinelt** [comment]
Or for 21.11?
