### ISSUE TITLE
nixops-deploy "bash: nix-store: command not found"

### ISSUE THREAD

**Issue by ElessarWebb** [NixOS/nixops#506]
I'm deploying to a virtualmachine; the first call to `nixops deploy` succeeds, starts and sets up the virtualbox. Directly calling `nixops deploy` again results in this error:

```
building all machine configurations...
warning: dumping very large path (> 256 MiB); this may run out of memory
trace: warning: The option `boot.loader.grub.timeout' defined in `/nix/store/5ca0389gadkz9ajqvxzd9c40k3p6nals-nixops-1.4/share/nix/nixops/virtualbox-image-nixops.nix' has been renamed to `boot.loader.timeout'.
valse> copying closure...
valse> bash: nix-store: command not found
valse> unable to connect to ‘root@192.168.56.101’; falling back to old closure copying method
valse> bash: nix-store: command not found
valse> Died at /nix/store/i4mwf2gpvar7dqvlpp5m86llbq3ahbvb-nix-1.11.4/lib/perl5/site_perl/5.22.2/x86_64-linux-thread-multi/Nix/CopyClosure.pm line 100.
error: command ‘['nix-copy-closure', '--to', 'root@192.168.56.101', u'/nix/store/wqj183mbdhcckafkmmbppxqhikj5zcgb-nixos-system-valse-16.09beta250.feef017']’ failed on machine ‘valse’ (exit code 127)
```

nix-store is on my own path, but I assume nixops sets up it's own build environment for the deployment. 

I have run `nix-store --verify --check-contents --repair` to ensure my store is not corrupted somehow. It's all OK.

**Comment by wmertens** [comment]
Looks like there is something wrong with your path, either locally or on the target host

**Comment by ElessarWebb** [comment]
I have this NIX_PATH on my own machine `nixpkgs=/home/arjen/.nix-defexpr/channels/nixpkgs`

Where .nix-channels contains:

```
https://nixos.org/channels/nixos-16.09/ nixpkgs
```

**Comment by ElessarWebb** [comment]
Oh, and interesting to note: I also deploy to another non-virtualbox host. That deployment works fine.

**Comment by edolstra** [comment]
What do
```
nixops ssh machine 'echo $PATH'
```
and
```
nixops ssh machine nix-store --version
```
say?

**Comment by ElessarWebb** [comment]
```
> nixops ssh machine 'echo $PATH'
/root/bin:/var/setuid-wrappers:/root/.nix-profile/bin:/root/.nix-profile/sbin:/root/.nix-profile/lib/kde4/libexec:/nix/var/nix/profiles/default/bin:/nix/var/nix/profiles/default/sbin:/nix/var/nix/profiles/default/lib/kde4/libexec:/run/current-system/sw/bin:/run/current-system/sw/sbin:/run/current-system/sw/lib/kde4/libexec

> nixops ssh machine nix-store --version
bash: nix-store: command not found
```

**Comment by edolstra** [comment]
Does `/run/current-system/sw/bin/nix-store` exist? It should, and that directory *is* in $PATH.

**Comment by ElessarWebb** [comment]
No it doesn't exist

**Comment by edolstra** [comment]
Do you have anything in the config for that machine that could cause this, e.g. `nix.package = null` or `environment.systemPackages = mkForce ...` (which would cause the default packages to disappear).

**Comment by ElessarWebb** [comment]
No, because I'm also deploying to another non virtualbox host and that one works. That one would break as well in that case, right?

**Comment by ElessarWebb** [comment]
Huh, I think I fixed it by removing `services.openssh.enable = true` from the configuration.

**Comment by edolstra** [comment]
Hm, that's the default so it shouldn't matter...

**Comment by ElessarWebb** [comment]
Hmm, no indeed. Adding it back doesn't reproduce. I have no idea what changed. 
I don't think I changed anything myself. Nor did I change the steps that reproduced the issue earlier. So it seems like a fluke. 

If it comes back, I'll reopen.

**Comment by dpc** [comment]
Had the same issue. For me it was because I had ssh config errors during Digital Ocean droplet bootstrapping. Afterwards `nixops` expected things to be there that weren't. I've destroyed the deployment, redid it, and it went smoothly then.
