### ISSUE TITLE
how to build the manual and do a PR?

### ISSUE THREAD

**Issue by qknight** [NixOS/nixops#509]
the link `Installation instructions` on https://github.com/NixOS/nixops is down!

please provide a workflow how to clone, build, review the changes on the manual.

https://nixos.org/nixops/manual/#chap-installation only mentions how to install `nixops` but not the manual of `nixops`.

**Comment by domenkozar** [comment]
http://hydra.nixos.org/build/40706610/download/1/manual/manual.html#chap-hacking
