### ISSUE TITLE
Support Digital Ocean

### ISSUE THREAD

**Issue by bachp** [NixOS/nixops#515]
[Digital Ocean](https://www.digitalocean.com/) has nice servers for a good price.
It would be a good candidate for an additional backend.

The also have a pretty good [API](https://developers.digitalocean.com/documentation/v2/)

**Comment by yotann** [comment]
They don't support NixOS or custom distros. I'm sure it's possible to install Debian and overwrite it with NixOS, like [digitalocean-debian-to-arch](https://github.com/gh2o/digitalocean-debian-to-arch) does for Arch Linux, but it's a bit of a hack.

[Vultr](https://www.vultr.com/) is a very similar service which *does* support custom distros, and they have an API.

**Comment by bachp** [comment]
There is also [nixos-infect](https://github.com/elitak/nixos-infect).

**Comment by domenkozar** [comment]
I'm going to close this as DigialOcean doesn't support "upload an image" API. We can have an issue for nixos-infect or similar if wanted/needed.

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixops/issues/562
