### ISSUE TITLE
Update libcloud

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixops#519]
It looks like nixops is currently using libcloud 0.18.0 but version 1.2.1 is available. Many bugfixes and improvements are awaiting us.

**Comment by domenkozar** [comment]
I've bumped it in b2c94025297d65b874c4597143e60f716ac8f939, but leaving this open as nixops might need changes.

@rbvermaa how do I run GCE tests?

**Comment by 3noch** [comment]
Is libcloud only being used for the GCE backend?

**Comment by domenkozar** [comment]
Yes

**Comment by domenkozar** [comment]
@rbvermaa could we bump libcloud and run GCE tests?

**Comment by rbvermaa** [comment]
Rather not, I am about to release nixops.

**Comment by grahamc** [comment]
Please reopen in https://github.com/AmineChikhaoui/nixops-gce?

**Comment by tewfik-ghariani** [comment]
@grahamc  already pointing to the latest libcloud release 
```
apache-libcloud = "^3.0.0"
```
https://github.com/nix-community/nixops-gce/pull/4/files#diff-522adf759addbd3b193c74ca85243f7dR11
