### ISSUE TITLE
docker service not restarted after update

### ISSUE THREAD

**Issue by gilligan** [NixOS/nixops#523]
I ran an a deployment that updated `docker` from `1.10.3` to `1.12.1`. After the deployment I noticed that I was running into an error:

```
10:43:09 Error response from daemon: client is newer than server (client API version: 1.24, server API version: 1.22)
```

It turned out that the old docker deamon version was still running. All I had to do to fix this was `systemctl restart docker`. Is this actually a problem with nixops or does the problem lie elsewhere?

**Comment by rbvermaa** [comment]
This is likely an issue in nixpkgs/nixos, please file issue there.
