### ISSUE TITLE
Be transparent about selecting a build machine

### ISSUE THREAD

**Issue by ElessarWebb** [NixOS/nixops#524]
There are a couple of open issues on setting up a remote build host and there are some guides floating about on how to do it from different platforms for different purposes.
A part of the "problem" however is that nix-ops is quite opaque about it's choice to build a package somewhere.
It would be nice if it would be more explicit about this selection, e.g.: `building x at y because z`.

Where I imagine that z could be a message about platform compat, build hosts busy, supported features, missing signing keys (!!), etc.

**Comment by rbvermaa** [comment]
This should probably be an issue in the nix issue tracker, as nixops just uses the nix distributed build feature.

**Comment by ElessarWebb** [comment]
okay, I was unsure about where to report it, I will move it there.
