### ISSUE TITLE
Make route53 independent of ec2

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixops#527]
I (naively) expected to be able to use route53 on my other systems. Example:

``` nix
{
  nix-dev = { resources, pkgs, lib, ... }: {
    deployment.targetEnv = "hetzner";
    deployment.route53.accessKeyId = "foo";
    deployment.route53.hostName = "foo.my-zone";
  };
}
```

I expected foo.my-zone to be created in my route53 hosted zone for this hetzner machine.

**Comment by roberth** [comment]
Maybe we can change the title to 'Make route53 independent of ec2'?

**Comment by grahamc** [comment]
Done, @robertth.

**Comment by domenkozar** [comment]
Is anyone looking into this? We (https://github.com/input-output-hk) would like to look into round-robin DNS routing using multi-value.

**Comment by domenkozar** [comment]
Ok then :)

**Comment by domenkozar** [comment]
This was implemented in https://github.com/NixOS/nixops/commit/97c0f9f696f55429ef7f98e106286750cc77e228

But it's not available in the manual yet (recordset, hosted zone, healthcheck).

**Comment by domenkozar** [comment]
Added to the manual in 5ecfde3ece94b5163b5c1ef949bca92826fd1133
