### ISSUE TITLE
Build VirtualBox image for NixOS 16.09

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixops#535]
I tried...and failed. I'm running macOS and I don't have the wherewithal and nix foo to do it. Is this already done somewhere? If not, would someone be willing to publish it? One already exists for GCE (which is how I got into this mess in the first place) but I can't find one for VirtualBox.

**Comment by 3noch** [comment]
`srhb` on IRC kindly built the image for me and let me download it. If someone with upload privs would like to upload it for others, let one of us know.

**Comment by rbvermaa** [comment]
Will upload new image today.

**Comment by 3noch** [comment]
Thanks!
