### ISSUE TITLE
Warning on deprecated boot.loader.grub.timeout

### ISSUE THREAD

**Issue by basvandijk** [NixOS/nixops#542]
With the nixops that comes with NixOS-16.09 I get the following warning:

```
$ nixops deploy  ...
building all machine configurations...
trace: warning: The option `boot.loader.grub.timeout' defined in `/nix/store/anlwqs8819sf6vjm12518rsk3sw65zww-nixops-1.4/share/nix/nixops/hetzner.nix' has been renamed to `boot.loader.timeout'.
```

It would be great if this could be fixed for NixOS >= 16.09.

**Comment by danbst** [comment]
Related PR
https://github.com/NixOS/nixops/pull/446

**Comment by danbst** [comment]
And related commit
https://github.com/NixOS/nixops/commit/73388c3041f4292ee6f5ac302dda91e27eedb31e

**Comment by domenkozar** [comment]
This is fixed in master.
