### ISSUE TITLE
Ask for confirmation once per operation

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixops#549]
Currently, if you destroy 100 nodes, it will ask for each of them separately if the resource should be deleted.

Destroy should be a batch operation, asking for confirmation once otherwise, confirmation is useless in practice.

**Comment by rbvermaa** [comment]
@domenkozar you can use --confirm for this?

**Comment by domenkozar** [comment]
@rbvermaa yes, but that makes this feature useless. I do want to be asked for confirmation, but once, not 100 times.

**Comment by rbvermaa** [comment]
I do not agree that this feature is useless like this. To me, it doesn't make any sense to have it ask to confirm, and then you say yes to all. What does the first confirmation have to do with any other. Then you can just as well use --confirm, as that is basically what you want to do, apparently.

Also, what do you mean with 'batch operation'?

**Comment by domenkozar** [comment]
@rbvermaa I want nixops to say:

```
We're going to destroy following nodes:

node1, node2, node3, node4, ...

Do you want to continue? [Y/n]
```

**Comment by rbvermaa** [comment]
That would require a complete rewrite of nixops, similar to the deployment plans mentioned in issue #316. So I do not think this will be implemented any time soon, unfortunately.

**Comment by domenkozar** [comment]
Yeah I imagined, since you'd have to know all resources upfront.

**Comment by rbvermaa** [comment]
Shalll we close this as duplicate of the deployment plan issue?

**Comment by domenkozar** [comment]
Sure
