### ISSUE TITLE
Avoid the target downloading from cache but copy everything.

### ISSUE THREAD

**Issue by ambrop72** [NixOS/nixops#551]
I don't like how when I deploy to a local machine, even though the nixops host has the whole system built locally (which is for example ensured by using `deploy --build-only`), when I deploy, the target system downloads many things from the public cache. I would like an option in nixops to stop the target system downloading anything from the cache but copy anything missing from the nixops host.

**Comment by domenkozar** [comment]
`def has_really_fast_connection(self):` is responsible for that atm.

**Comment by danbst** [comment]
related https://github.com/NixOS/nixops/issues/513

**Comment by domenkozar** [comment]
@danbst https://github.com/NixOS/nixops/issues/566
