### ISSUE TITLE
LVM partitioning on hetzner is not working

### ISSUE THREAD

**Issue by binarin** [NixOS/nixops#552]
Everything fails when `nixpart` tries to call something like `pvscan ... /dev/md0`. The problem is that LVM available in the rescue image now (2.02.111-2.2+deb8u1) doesn't allow such invocations without `--cache` argument. But this `--cache` was explicitly patched out in 2014 like this https://github.com/NixOS/nixpkgs/blob/78178d5854901e1b17a14bce3fe43515984b7b91/pkgs/tools/filesystems/nixpart/0.4/blivet.nix#L31

After I manually unpatch lvm.py that nixops copied to hetzner host,  I'm able to run `nixpart -p -` with the following config successfully:

        clearpart --all --initlabel --drives=sda,sdb
        part swap1 --recommended --label=swap1 --fstype=swap --ondisk=sda
        part swap2 --recommended --label=swap2 --fstype=swap --ondisk=sdb
        part raid.0a --size=1024 --ondisk=sda
        part raid.0b --size=1024 --ondisk=sdb
        part raid.1a --grow --ondisk=sda
        part raid.1b --grow --ondisk=sdb
        raid /boot --level=1 --device=boot --fstype=ext2 --label=boot raid.0a raid.0b
        raid pv.0 --level=1 --device=md0 raid.1a raid.1b
        volgroup sysvg pv.0
        logvol / --vgname=sysvg --size=65536 --fstype=ext4 --name=root

I'm willing to fix it, but not sure where to start. Maybe this `--cache` patching should be just removed? Or maybe it depends on what hetzner DC is used and there are some older versions of LVM2 that require this patch?

**Comment by binarin** [comment]
@aszlig Maybe you can shed some light on why this `--cache` patch was needed?

**Comment by aszlig** [comment]
@binarin: I've patched it out because the old version didn't recognize `--cache`, so it can be removed.
