### ISSUE TITLE
Release 1.5.0

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixops#553]
TODO

- [x] Change `modules.sqlite` to `pysqlite` in nixpkgs
- [x] https://github.com/NixOS/nixops/pull/446
- [ ] changelog

**Comment by teh** [comment]
I upgrade to 1.5 and it breaks on my existing AWS installs with: 

```
$ nixops deploy --include admin
error: [Errno 2] No such file or directory: '/home/tom/.aws/credentials'
```

I have all my credentials in the environment, so not sure why it's checking that file.

**Comment by rbvermaa** [comment]
Probably due to this: 18a8644f129fa485a43c2241b41280614af04477 . I'll try and fix it later today.

**Comment by rbvermaa** [comment]
@teh Can you share some more information about your network, e.g. what kind of resource is 'admin'? As I am not able to reproduce the issue.

**Comment by rbvermaa** [comment]
@teh should be fixed in: fcbc94c6d13a1899e2cc1daa198a605802da3e88

**Comment by teh** [comment]
@rbvermaa thanks, fixed!

**Comment by bachp** [comment]
What's the status of the 1.5 release? 
As the last release is already quite some time ago I suggest to release soon and push the open issues to a later release.

**Comment by domenkozar** [comment]
@rbvermaa thoughts? I have a bunch of fixes to be made, but if we release 1.5.0 that won't stop me :)

**Comment by bachp** [comment]
I was trying to update `nixopsUnstable` in nixpkgs so people can use that. But I feel the build process is a bit complicated and I wasn't able to build it from source because of the man page.

**Comment by rbvermaa** [comment]
@bachp @domenkozar I'll try to release 1.5 this week.

**Comment by rbvermaa** [comment]
Release will take at least a few days longer, as the Azure packages need to be fixed (as they are not compatible with requests2 2.11.0+), before I can run the tests. The other tests succeeded.

**Comment by teh** [comment]
I see the 1.5 tag has happened, can this be closed?

If yes: maybe we can publish the release on the homepge news feed?

**Comment by domenkozar** [comment]
@edolstra

**Comment by rbvermaa** [comment]
Will add news item once I release 1.5.1 in the next 2 days.
