### ISSUE TITLE
Is it possible to recover the state of a deployment without a state file or with an old version?

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixops#573]
In the same vein as https://github.com/NixOS/nixops/issues/565, is it possible to recover the state of an existing deployment to some degree without a state file? Or, if you had an old state file (i.e. not the most recent changes to the server), would you be able to do some level of recovery with it?

**Comment by domenkozar** [comment]
Depends. Can you be more specific? Do you have an actual use case or in general?

**Comment by 3noch** [comment]
Well I'm just trying to foresee any possible catastrophes and be ready for them. I haven't had problems yet but I'm being careful. Being careful is my least favorite type of safety.

**Comment by grahamc** [comment]
#1264 implements state backends, and those backends could implement backups.
