### ISSUE TITLE
DigitalOcean deploy seems to deadlock at times

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixops#579]
I'm excited about the new DigitalOcean backend! I've deployed a simple WordPress site and made a few deployments. However, after my most recent changes, the deploy seems to deadlock and it always ends up here:

(Obfuscated for paranoia's sake.)
```
wordpress-main> copying closure...
Warning: Permanently added '104.131.*.**' (ED******) to the list of known hosts.
```

I am able to use `nixops ssh` to log in to the server, but deploying doesn't seem to work anymore.

If I deploy with `--check` the `Warning: Permanently added...` line is at the top instead.

**Comment by 3noch** [comment]
False alarm. It's just that DO has *really* slow upload speeds (at least for the `512mb` sized droplet).

**Comment by dhess** [comment]
Did you ever get to the bottom of this? I'm having the same problem with DigitalOcean deployments. It appears to affect only the last couple of copy-closures. The copies are excruciatingly slow -- probably on the order of a few KBytes per second. Everything else is nice and fast.

It's quite repeatable for me and it affects both 512mb and 1gb droplets. (I haven't tried with a larger droplet yet.)

**Comment by 3noch** [comment]
@dhess No, I've deployed to GCE without this issue so I presumed it was just an upload bottleneck on DO's side.
