### ISSUE TITLE
VirtualBox backend should not assume same IP

### ISSUE THREAD

**Issue by 3noch** [NixOS/nixops#583]
I *often* run into an issue where NixOps deploys a VirtualBox machine and saves its IP to my `~/.ssh/known_hosts` file. Later on, after I've rebooted the VM, NixOps can't detect that the IP of the VM has changed and just hangs. If I remove the entry in `~/.ssh/known_hosts` it seems NixOps is able to figure things out and work correctly. This problem is even worse when I deploy machines from various projects, but some deployment steals the IP from a previous deployment. In this case NixOps actually tries to connect to a running VM but it has the wrong keys.

Can we teach the VirtualBox backend not to assume the IP is the same? Also it would be nice if it could automatically remove or update `~/.ssh/known_hosts` in these cases.

**Comment by domenkozar** [comment]
Duplicates https://github.com/NixOS/nixops/issues/286
