### ISSUE TITLE
Libvirt images are world-writable

### ISSUE THREAD

**Issue by Nadrieril** [NixOS/nixops#584]
See https://github.com/NixOS/nixops/blob/master/nixops/backends/libvirtd.py#L104
This is a really problematic security issue, the libvirt backend should not be used as it is.

**Comment by Nadrieril** [comment]
@bosu why would we need the user to have write (or even read) access to the image ? As far as I understand the user only needs to be able to remove the image on destroy, which they can already do since they have write access to the image directory

**Comment by bosu** [comment]
@Nadrieril, this is probably an oversight on my part. Thanks for fixing it!

**Comment by Nadrieril** [comment]
Fixed in https://github.com/NixOS/nixops/commit/1266cdcba5b62263121c2620311a330ceff503d6
