### ISSUE TITLE
schema version mismatch

### ISSUE THREAD

**Issue by P-E-Meunier** [NixOS/nixops#589]
I'm just facing a pretty big bug in nixops, where immediately after deploying a fresh machine to hetzner (from nixos-unstable on my laptop), I can access the machine, but no matter what nix- command I type, I get the following error:

```
current Nix store schema is version 10, but I only support 7
```

Even `nixops deploy -d machine` a second time yields that error.

**Comment by domenkozar** [comment]
You upgraded to nix unstable and went back to stable. Not a nixops issue.

**Comment by P-E-Meunier** [comment]
I guess it's impossible to install unstable on the remote, isn't it?
If so, I've not understood how to use channels from the manual.

**Comment by domenkozar** [comment]
You can, but this happens when you install stable Nix after unstable Nix.
