### ISSUE TITLE
Using Hetzner with an Admin user (per-server sub-account)

### ISSUE THREAD

**Issue by nh2** [NixOS/nixops#592]
When using the Hetzner backend, nixops always tries to do `creating an exclusive robot admin account for ...`.

I already have an exclusive sub-account for my machine, and I'd like nixops to use that straight away, and not create one itself, so that I don't have to give nixops access to my entire Hetzner Webservice API credentials (which in fact also didn't work for me, as the `hetzner` Python package that it uses then complains that [`The user {0} is a dedicated web service user`](https://github.com/RedMoonStudios/hetzner/blob/280f8d3105937d46da21d534f82315f83db3ed84/hetzner/robot.py#L86), but that would be a separate issue, let me know if I should file it).

The trouble is that I can't set the user/password for the sub-account with environment variables; the current code runs:

```python
        if not self.robot_admin_user or not self.robot_admin_pass:
            self.log_start("creating an exclusive robot admin account for "
                           "‘{0}’... ".format(self.name))
```

and `self.robot_admin_pass`/`self.robot_admin_user` don't come from the `HETZNER_ROBOT_USER`/`HETZNER_ROBOT_PASS` environment variables (only `robot_user` and `robot_pass` do, and setting only those doesn't work).

It would be great if I could tell nixops via environment variables the user/password to use an already created per-machine sub-account.

**Comment by nh2** [comment]
As a workaround, I've added the lines

```python
        self.robot_admin_pass = os.environ.get('HETZNER_ROBOT_ADMIN_PASS', None) or self.robot_admin_pass
        self.robot_admin_user = os.environ.get('HETZNER_ROBOT_ADMIN_USER', None) or self.robot_admin_user
```

before this line https://github.com/NixOS/nixops/blob/e73c4eefe02142bcc5ca3fe99abf854094e704db/nixops/backends/hetzner.py#L582

and then set all 4 of

```
HETZNER_ROBOT_USER
HETZNER_ROBOT_PASS
HETZNER_ROBOT_ADMIN_USER
HETZNER_ROBOT_ADMIN_PASS
```

to the credentials of the sub-account.

**Comment by nh2** [comment]
Would you accept a PR that adds the 2 lines I suggested?

Or should I not add the `_ADMIN_` variables and instead have one that tells it to use the existing env vars as the admin ones? Or maybe even do that by default? This may make sense, because I _think_ if you use `hetzner.robotUser` in your `.nix` file, it will use that as `robot_admin_user` -- or at least [this line](https://github.com/NixOS/nixops/blob/e73c4eefe02142bcc5ca3fe99abf854094e704db/nixops/backends/hetzner.py#L73) suggests that to me.

**Comment by danbst** [comment]
Would an option `deployment.hetzner.createSubAccount :: Boolean` be sufficient if implemented? Then you just set 
```
  deployment.hetzner.createSubAccount = false;
```
and supply HETZNER_ROBOT_USER/HETZNER_ROBOT_PASS

**Comment by nh2** [comment]
@danbst that would make sense to me.

**Comment by nh2** [comment]
> give nixops access to my entire Hetzner Webservice API credentials (which in fact also didn't work for me, as the hetzner Python package that it uses then complains that `The user {0} is a dedicated web service user`

Just for the record, a reason that I can't use nixops with the Hetzner main account is that I have 2-factor-auth enabled.

**Comment by nh2** [comment]
> Would an option deployment.hetzner.createSubAccount :: Boolean be sufficient if implemented?

I've created a PR that implements this: #688

Finally I can create Hetzner machines with 2FA and without pain!
