### ISSUE TITLE
Security: Don't make nixos state file world-readable

### ISSUE THREAD

**Issue by nh2** [NixOS/nixops#594]
When using `NIXOPS_STATE=localstate.nixops nixops ...` I noticed that the file permissions are set to `-rw-r--r--`.

That's no good! This file contains an SSH private key in plain text.

I think Nixops should set the permissions to `-rw-------` before writing anything to this file.

**Comment by Nadrieril** [comment]
Actually, since $HOME/.nixops is created with permissions `drwx------`, only the owner can read anything.
You can test it yourself with e.g. `sudo -u nixbld1 ls -l $HOME/nixops/deployments.nixops` (or replace `nixbld1` by some other user in your system).
So there is no security problem.

**Comment by domenkozar** [comment]
Closing :)

**Comment by nh2** [comment]
> Actually, since $HOME/.nixops is created with permissions

Hang on, how is this relevant?

I mentioned that I'm using `NIXOPS_STATE=localstate.nixops`; the entire purpose of that feature is to make the state file *not* be in `$HOME/.nixops`.

**Comment by Nadrieril** [comment]
Oh right sorry, my mistake

**Comment by nh2** [comment]
@rbvermaa Thanks for the fix!

I've pull-requested a small improvement on top of it that ensures that at no time the permissions of new DBs are world-readable in #604.

**Comment by rbvermaa** [comment]
@nh2 I did not want to change permissions of existing files. Could you change your PR to produce a warning in stead?

**Comment by rbvermaa** [comment]
Thinking about it, it will be tricky to determine if permissions are harmful, as it depends on the location of the state file.

**Comment by nh2** [comment]
> I did not want to change permissions of existing files.

@rbvermaa I might be missing something, does my PR do that? It's bracketed in `if not db_exists`.

**Comment by rbvermaa** [comment]
@nh2 wow, I need coffee.. Sorry for the noise.
