### ISSUE TITLE
nixops destroy fails 

### ISSUE THREAD

**Issue by moxiegirl** [NixOS/nixops#599]
I've got some duplicate deployments that I'm trying to remove.  So, I do a list.

```
$ nixops list
+--------------------------------------+--------+------------------------+------------+------------+
| UUID                                 | Name   | Description            | # Machines |    Type    |
+--------------------------------------+--------+------------------------+------------+------------+
| 02f88fa6-e987-11e6-b279-f45c898a30b5 | e2e    | Unnamed NixOps network |          0 |            |
| d3129fab-9719-11e6-a79f-f45c898a30b5 | e2e    | End-to-End             |          1 | virtualbox |
| 94f3efae-94b1-11e6-a85b-f45c898a30b5 | minime | Unnamed NixOps network |          0 |            |
+--------------------------------------+--------+------------------------+------------+------------+
```

Issue a destroy...

```
$ nixops destroy -d  02f88fa6-e987-11e6-b279-f45c898a30b5
```

But the deployment is not destroyed and shows up in the next listing.

**Comment by AmineChikhaoui** [comment]
`nixops destroy` only destroys the resources associated with a deployment, you'll have to run `nixops delete` in order to actually remove it from the statefile.

**Comment by hhefesto** [comment]
OS: Fedora 29
nixops version: NixOps 1.6.1

After trying to do a trivial Virtualbox deployment (and failing), I am unable to destroy the deployment. It hangs on "waiting for exclusive deployment lock...":
```
$ nixops destroy -d trivial
waiting for exclusive deployment lock...
```

Additional, maybe useful, information:

I also rebooted, but the problem persists.

These are the steps I took to do the trivial deployment on Virtualbox and my failing to destroy:
- Copied trivial.nix and trivial-vbox.nix  (https://nixos.org/nixops/manual/#idm140737318601504) without the headless deployment option to an empty directory
- on Virtualbox, under file -> preferences -> Network I added a new NAT named "vboxnet0" with CIDR 10.0.2.0/24 and DHCP support
- I created and deployed
- Some error showed saying something about "vboxnet0" and networks (don't remember exactly and can't re-reproduce), and letting me re-make "vboxnet0", which I did
- Wanted to start over, so I deleted the virtual machine from Virtualbox's graphic interface
- Then tried to destroy and delete, and came up with this destroy problem
- Tried creating and deploying with the same name (-d trivial) and different name (-d trivial2) and failed both times
  - And the new tries don't reproduce the first one (I can destroy & delete those just fine):
```
$ nixops list
+--------------------------------------+----------+------------------------+------------+------------+
| UUID                                 | Name     | Description            | # Machines |    Type    |
+--------------------------------------+----------+------------------------+------------+------------+
| 85970d17-5ea3-11e9-aaff-525400a4b3a9 | trivial  | Web server             |          1 | virtualbox |
| 992bfe5c-5eb2-11e9-8599-525400a4b3a9 | trivial3 | Unnamed NixOps network |          0 |            |
+--------------------------------------+----------+------------------------+------------+------------+

```
I don't understand why ```nixops create ./trivial.nix ./trivial-vbox.nix -d trivial3``` doesn't output a deployment with the same description, nor the same "# Machines" nor a virtualbox Type as just shown with ```nixops list```, but that should maybe/likely be in another issue.

I found https://github.com/NixOS/nixops/blob/master/nixops/deployment.py (I think the "waiting for exclusive deployment lock..." error is defined there)
