### ISSUE TITLE
Feature Request: Support remote state storage and locking

### ISSUE THREAD

**Issue by peterhoeg** [NixOS/nixops#600]
[terragrunt](/gruntwork-io/terragrunt) wraps terraform by storing locking info in AWS DynamoDB and the state file in AWS S3. That allows multiple people to safely work on shared infrastructure from their own machines.

It would be incredibly neat if nixops could do the same.

**Comment by domenkozar** [comment]
WIP PR at https://github.com/NixOS/nixops/pull/624

**Comment by peterhoeg** [comment]
For reference, #1264

**Comment by grahamc** [comment]
#1264 implements state backends, and those backends could implement locking, encryption, or remote storage.
