### ISSUE TITLE
IPv6-only target hosts always appear to be down

### ISSUE THREAD

**Issue by wizeman** [NixOS/nixops#601]
I have targets with IPv6-only addresses (all using the `none` backend) which nixops thinks are always down.

PR #355 fixes the issue for me. However, as @edolstra indicated there, it may not work on systems which have IPv6 completely disabled.

For the record, I am using nixops 1.4.

**Comment by domenkozar** [comment]
Could be solved with https://github.com/NixOS/nixops/pull/486

**Comment by wizeman** [comment]
@domenkozar: #486 doesn't fix this for me. With that PR applied, `nixops deploy` works, but `nixops check` still reports all hosts as being down. I've added a comment on that PR.

**Comment by domenkozar** [comment]
Fixed in https://github.com/NixOS/nixops/pull/735
