### ISSUE TITLE
Using relative paths inside the nixops state file

### ISSUE THREAD

**Issue by nh2** [NixOS/nixops#615]
I'm using `NIXOPS_STATE=localstate.nixops nixops` and noticed that in my `localstate.nixops` the paths are absolute, e.g. `/home/niklas/my/nixops/mymachine.nix`, instead of simply `mymachine.nix`.

Is there a way to change this? I'd like to be able to move the directory around (in particular, be able to share it with others) that contains both `localstate.nixops` and `mymachine.nix`.

Is there support / an option for this already?

**Comment by nh2** [comment]
I guess it's related to this:

```python
    depl.nix_path = [nixops.util.abs_nix_path(x) for x in sum(args.nix_path or [], [])]
```

```
def abs_nix_path(x):
    xs = x.split('=', 1)
    if len(xs) == 1: return _maybe_abspath(x)
    return xs[0] + '=' + _maybe_abspath(xs[1])
```

What does that `=`-splitting logic do? I'd try to send a PR for this but am not quite sure what I have to ensure to not break.

**Comment by aycanirican** [comment]
You may want to add current directory to NIX_PATH (NIX_PATH=$NIX_PATH:.)and refer your deployment files as '<machines.nix>'

--
aycan

**Comment by nh2** [comment]
> You may want to add current directory to NIX_PATH (NIX_PATH=$NIX_PATH:.)and refer your deployment files as '<machines.nix>'

This sounds like a solution, I'll try this and report back.

**Comment by nh2** [comment]
@aycanirican's suggstion works, thank you.
