### ISSUE TITLE
Nixops, nixos-container keys deployment

### ISSUE THREAD

**Issue by spinus** [NixOS/nixops#631]
I have a nixos host, I deploy it with NixOS as "none" target (with just ssh).
I have defined container inside nixos host like that:
```
{
  host1 = {...}: {
    boot.enableContainers=true;
    containers = {
       cont1 = {...}: {
           autoStart=true; .....
           config = {...}: {
              deployment.keys.key1 = {......};
           };
       };
    };
  };
}
```
NixOS and NixOps are not saying that there is anything wrong with deployment keys (it's recognized as valid nix expression), but the keys are not deployed into the container (they are also not deployed to the host machines).

Do you think this is a bug? 
What would be the correct behaviour:
- keys must be deployed into the container
- deployment.keys or deployment section in general, is not valid inside a container
?

**Comment by johbo** [comment]
I think this way the containers are not managed by nixops. My assumption is that it would work if you declare the containers as machines in your network with the targetEnv set to `"container"`.

This example file shows something like it: https://github.com/NixOS/nixops/blob/master/examples/trivial-container-in-vbox.nix

Could not try, but maybe this way would work:

```
host = {
  deployment.targetEnv = "none";
  ...
};

cont1 = { resources, ... }:  {
  deployment.targetEnv = "container";
  deployment.container.host = resources.machines.host;
};
```

**Comment by spinus** [comment]
On the other hand they are not managed that way, but on the other hand there is no error or any message, the file is just validated and that's why I would expect some outcome. I think if that workflow is not supported, "deployment" section should not be properly validated if it's inside the container. What do you think?

**Comment by johbo** [comment]
Yes, I think the best would be that things explode, then it's clear this is not supported.

I've tried it out of curiosity on my box and got the following error back:

```
[nix-shell:~/wbt/tryton/nix]$ nixops deploy -d test --build-only
resource ‘host’ is obsolete
building all machine configurations...
error: The option `containers.cont1.deployment' defined in `<unknown-file>' does not exist.
(use ‘--show-trace’ to show detailed location information)
error: unable to build all machine configurations
```

Here is my test network:

```
{

  network.description = "Test";

  nixvm1 = { config, pkgs, ... }: {
    deployment.targetEnv = "none";
    nixpkgs.system = "x86_64-linux";
    boot.loader.grub.device = "/dev/sda";
    fileSystems."/" = {
      label = "nixos";
      fsType = "ext4";
    };
    deployment.keys.key-host.text = "something";
    containers = {
      cont1 = {
        autoStart = true;
        config = { ... }: {
          deployment.keys.key-cont.text = "something";
        };
      };
    };
  };

}
```

**Comment by spinus** [comment]
@johbo you are right, it blows up. I did something strange in my config and hence I didn't get the error (the rule was not evaluated properly and I thought it was silenced). Thanks for double checking!
