### ISSUE TITLE
Restructure the ResourceState class to make it dictionary based (store the state as a key value dict)

### ISSUE THREAD

**Issue by AmineChikhaoui** [NixOS/nixops#648]
Currently the Resource state attributes are handled by setting them as python **property** using `nixops.util.attr_property` then their _set_attr/_get_attr methods are overridden to make them able to read from the state file or write to it automatically.
On the other hand the resource definition was migrated to a dictionary based structure in [this commit](https://github.com/NixOS/nixops/commit/b0770ee2d946ebce8624778ef630718629f63494) to avoid the extra xml parsing.
As I'm thinking about implementing something to store the diff between the state/defn (end goal is to have something that gives the plan like what terraform does), I thought we can add an attribute to the ResourceState class e.g _state which will be using for example StateDict class that either inherit from **dict** or implement the dictionary interface. In the implementation of such StateDict class we can make \__getitem\__/\__setitem\__  our access point to the state file i.e statements like the following will handle the state file like what we had previously with minimal changes
```
with  self.depl._db:
  self._state['region'] = defn.config['region'] # the self._state['key']=val statement will write to the state file
```
and `self._state['region']` will read from the state file and return the value.
Of course we need to handle stuff like default values and make the class behave exactly like a regular dictionary otherwise it can cause confusion and unexpected behavior. But first, I wanted to have some opinions about such changes before starting any actual implementation.
I think if we have such structure, doing a diff will be much cleaner by comparing the keys of 2 similar dictionaries. So any thoughts ?
attn @edolstra @aszlig

**Comment by edolstra** [comment]
What do you mean with "storing the diff"? I assume you just *compute* the diff between the state and the definition at runtime and then execute some actions depending on the diff.

How should we handle state elements that do not have a corresponding definition element? For example, EC2 instances have an instance ID in their state but not their definition.

Do you have some ideas on how the diff output will be used? I'm thinking that diff engine, if it detects that some attribute `foo` has changed, could call a method `realize_foo_change` on the resource (e.g. `realize_instance_type_change` would stop the instance, change the instance type and then start it again). If the required method doesn't exist, it would print a warning or error (e.g. "resource X does not support changing the 'region' attribute"). Currently this is all done in an ad hoc / incomplete way in the `create` method, so this would a big improvement.

**Comment by AmineChikhaoui** [comment]
@edolstra yeah sorry it wasn't clear by "storing" just during the runtime and not something persistent.
Also the initial goal is to be able to print something like a plan; what's going to be created/modified/destroyed but correct it should be extendable to things like what you mentioned i.e some kind of diff engine which is a great idea.
And correct there are some attributes that are computed ids, arns etc.. so I think we can show that it will be computed or only show the difference with attributes that are in the definition.
So I really like the diff engine idea but let's start by having an initial data structure for the diff then I think we can incrementally add more features to it.
Also not sure what's your opinion about the dict based state in general ?

**Comment by edolstra** [comment]
Yeah the dictionary-based approach sounds good to me in general.

BTW, the `self.state` field could also be part of the dictionary. That way, lifecycle transitions (like `UP` -> `STOPPED`) could be handled generically as well as just another type of diff between states.
