### ISSUE TITLE
Documentation options polluted with _module attributes

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixops#659]
For example https://nixos.org/nixops/manual/#idm140737313974320 has `_module.check` and `_module.args` attributes that are noise. We should look into removing them.

For reference:

- code generating options for nixops manual https://github.com/NixOS/nixops/blob/master/doc/manual/default.nix#L7
- code generating options for nixos manual https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/misc/nixos-manual.nix#L25

cc @edolstra @nbp

**Comment by nbp** [comment]
These options are defined as `internal` options [1].  When the list of option is generated, `internal` options should be filtered out, as done for NixOS.

[1] https://github.com/NixOS/nixpkgs/blob/master/lib/modules.nix#L43

**Comment by domenkozar** [comment]
@nbp I figured and done as per https://github.com/NixOS/nixops/commit/cacab09fe89159ce2b2cc2b348e2a334dc6f46f7
