### ISSUE TITLE
DataDog monitor destruction response isn't properly analysed

### ISSUE THREAD

**Issue by deepfire** [NixOS/nixops#694]
As can be seen at https://github.com/NixOS/nixops/blob/master/nixops/resources/datadog-monitor.py#L127, the response to a monitor removal request isn't analysed, and I quote:

```
    self.connect(self.app_key,self.api_key)
    if self.monitor_exist(self.monitor_id) == False:
        self.warn("datadog monitor with id {0} already deleted".format(self.monitor_id))
    else:
        self.log("deleting datadog monitor ‘{0}’...".format(self.monitor_name))
        self._dd_api.Monitor.delete(self.monitor_id)
```

This can sometimes lead to a combination of:
```
cardano_node_process.......> deleting datadog monitor ‘cardano-node process is down’...
```
..and the fact DataDog monitor being still alive and well, as can be seen through the Web UI.

**Comment by AmineChikhaoui** [comment]
hm thanks @deepfire , will look into it

**Comment by deepfire** [comment]
According to https://datadogpy.readthedocs.io/en/latest/#datadog.api.Monitor:

```
 delete(id, **params)

    Delete an API resource object
    Parameters:	id (id) – resource object to delete
    Returns:	Dictionary representing the API’s JSON response
```

**Comment by AmineChikhaoui** [comment]
@deepfire yeah I originally though that datadog api will raise an exception in case of errors but should be easy to handle that but I'm curious what can go wrong in delete monitor api call, was there changes to the monitor from outside nixops and if so what kind of changes ?
