### ISSUE TITLE
Missing git tag for nixops v1.5.1

### ISSUE THREAD

**Issue by bjornfor** [NixOS/nixops#701]
It seems nixops 1.5.1 has been released (it's in nixpkgs), but there is no release tag in git:

```
$ git fetch --tags
$ git tag
pre-systemd
v1.0
v1.0.1
v1.1
v1.1.1
v1.2
v1.3
v1.3.1
v1.4
v1.5
```

Side note: please use _annotated_ git tags in public repos. They add valuable information, and make ```git describe``` work. It's really simple: ```git tag -am "Version X.Y" vX.Y [optional_commit_id]```.

EDIT: Fix "git tag" example.

**Comment by domenkozar** [comment]
cc @rbvermaa

**Comment by domenkozar** [comment]
there is one now:

```
$ git tag
pre-systemd
v1.0
v1.0.1
v1.1
v1.1.1
v1.2
v1.3
v1.3.1
v1.4
v1.5
v1.5.1
```
