### ISSUE TITLE
nixops silently fails when user doesn't already have known_hosts

### ISSUE THREAD

**Issue by nh2** [NixOS/nixops#703]
nixops assumes you already have `known_hosts`, and fails silently if you don't: https://github.com/NixOS/nixops/blob/d1907cb1a4defa1d01cd7c2d18e09c9276e716e5/nixops/known_hosts.py#L14

```
def _rewrite(ip_address, add, public_host_key):
    with lock:
        path = os.path.expanduser("~/.ssh/known_hosts")
        if not os.path.isfile(path): return
...
```

Because of this `return`, `_rewrite` doesn't do anything if `~/.ssh/known_hosts` doesn't exist, and as a result all functions in the module silently don't do anything.

That makes [the `nixops.known_hosts.update()` in `_wait_for_ip()`](https://github.com/NixOS/nixops/blob/d1907cb1a4defa1d01cd7c2d18e09c9276e716e5/nixops/backends/ec2.py#L353) do nothing, but nixops continues without error.

Finally, when nixops gets to [`replacing temporary host key...`](https://github.com/NixOS/nixops/blob/d1907cb1a4defa1d01cd7c2d18e09c9276e716e5/nixops/backends/ec2.py#L996), there's still no `known_hosts`, and thus nixops hangs forever with:

```
mymachine..> replacing temporary host key...
The authenticity of host '1.2.3.4 (1.2.3.4)' can't be established.
ED25519 key fingerprint is SHA256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.
Are you sure you want to continue connecting (yes/no)?
```

A workaround is to `touch ~/.ssh/known_hosts`.

But nixops shouldn't assume that the file exists, and continue silently if it doesn't.

**Comment by domenkozar** [comment]
It's a legacy from 14d3b215843be4014409837e15abfe49b8137110

It's probably best to touch it if it doesn't exist.

**Comment by domenkozar** [comment]
Thanks for catching this!
