### ISSUE TITLE
install-grub.pl blkid problem

### ISSUE THREAD

**Issue by GlennS** [NixOS/nixops#711]
I'm having an issue when running `switch-to-configuration boot` as part of _nixos-infect_.

The error is on line 185 of _Install-grub.pl_ https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/system/boot/loader/grub/install-grub.pl#L185

What I think is happening is is:

1. _install-grub.pl_ tries to find a device by reading _/proc/self/mountinfo_
2. _/proc/cmdline_ contains the statement `root=/dev/sda`
3. Because of (2), _/proc/self/mountinfo_ contains an entry for **/dev/root** instead of **/dev/sda**
4. Technically, **/dev/root** is probably just a symlink for **/dev/sda**, but...
5. _blkid_ doesn't know to follow symlinks, and so just returns nothing when it is asked for **/dev/root**

It's quite likely that I've misunderstood this issue, since I don't understand much about Perl, and this is my first encounter with **/dev/root**, so I'm looking for enlightenment as much as a fix.

**Comment by domenkozar** [comment]
This should be filed into nixpkgs repo issue tracker.
