### ISSUE TITLE
Feature request: allow users to specify SSH key pair for first connection rather than generating one

### ISSUE THREAD

**Issue by stefano-m** [NixOS/nixops#716]
Hello,

after a cursory look at the code, reading the docs, and some questions asked on IRC, it seems to me that nixops generates always an SSH key pair to connect to the remote machines as root.

The public key appears on the remote machine's `/etc/ssh/authorized_keys.d/root`, e.g.

- `none` backend:

```
cat /etc/ssh/authorized_keys.d/root
ssh-ed25519 <public key> NixOps client key for <machine name>
```

- `libvirt` backend

```
cat /etc/ssh/authorized_keys.d/root
ssh-ed25519 <public key> NixOps auto-generated key
```

One can then add further keys doing something like:

```nix
machine = {
    users.users = {
      root.openssh.authorizedKeys.keyFiles = [
          /some/path/to/.ssh/id_rsa.pub
        ];
   };
}
```
Would it be possible to optionally specify that one does *not* want to generate a default key pair (and that the public key should be removed from machines where it's present)? That would also remove the need to store private SSH keys in the state file.

I thought that perhaps that was the job of [resources.sshKeyPairs](https://nixos.org/nixops/manual/#idm140737316466992), but could not manage to work out how to use it.

Many thanks.

**Comment by ThreeFx** [comment]
This was merged recently as #1247 if I'm not mistaken.

cc @grahamc
