### ISSUE TITLE
"unable to activate new configuration" on GCE

### ISSUE THREAD

**Issue by michas2** [NixOS/nixops#724]
I tried the example on https://nixos.org/nixops/manual/#sec-deploying-to-gce .
I took a google project, set up a service account and downloaded the key.
I took the load balancer example as it is given in the manual and only put in the proper credentials.

The create works fine, and also the deploy seems to work fine, but at the very end it finishes with "unable to activate new configuration".

The last line of output look like this:

```
backend1.> the following new units were started: configure-forwarding-rules.service, google-accounts-daemon.service, google-clock-skew-daemon.service, google-ip-forwarding-daemon.service, google-shutdown-scripts.service, httpd.service, keys.tar
get
backend1.> warning: the following units failed: google-instance-setup.service
backend1.> 
backend1.> ● google-instance-setup.service - Google Compute Engine Instance Setup
backend1.>    Loaded: loaded (/nix/store/0arsvivrx181mwjanxl1m68xb6f8yxif-unit-google-instance-setup.service/google-instance-setup.service; enabled; vendor preset: enabled)
backend1.>    Active: failed (Result: exit-code) since Thu 2017-09-14 12:18:07 UTC; 371ms ago
backend1.>   Process: 3492 ExecStart=/nix/store/dxi14rg77icbc7wkrjvf3rfvvscxdf2m-google-compute-engine-20170523/bin/google_instance_setup --debug (code=exited, status=1/FAILURE)
backend1.>  Main PID: 3492 (code=exited, status=1/FAILURE)
backend1.> 
backend1.> Sep 14 12:18:07 backend1 google_instance_setup[3492]:     return Popen(*popenargs, **kwargs).wait()
backend1.> Sep 14 12:18:07 backend1 google_instance_setup[3492]:   File "/nix/store/2nsq3cpqy514n5raqdzpfh6lprpqlmjk-python-2.7.13/lib/python2.7/subprocess.py", line 390, in __init__
backend1.> Sep 14 12:18:07 backend1 google_instance_setup[3492]:     errread, errwrite)
backend1.> Sep 14 12:18:07 backend1 google_instance_setup[3492]:   File "/nix/store/2nsq3cpqy514n5raqdzpfh6lprpqlmjk-python-2.7.13/lib/python2.7/subprocess.py", line 1024, in _execute_child
backend1.> Sep 14 12:18:07 backend1 google_instance_setup[3492]:     raise child_exception
backend1.> Sep 14 12:18:07 backend1 google_instance_setup[3492]: OSError: [Errno 2] No such file or directory
backend1.> Sep 14 12:18:07 backend1 systemd[1]: google-instance-setup.service: Main process exited, code=exited, status=1/FAILURE
backend1.> Sep 14 12:18:07 backend1 systemd[1]: Failed to start Google Compute Engine Instance Setup.
backend1.> Sep 14 12:18:07 backend1 systemd[1]: google-instance-setup.service: Unit entered failed state.
backend1.> Sep 14 12:18:07 backend1 systemd[1]: google-instance-setup.service: Failed with result 'exit-code'.
backend1.> error: Traceback (most recent call last):
  File "/nix/store/2nyvcxap09nafj2kcg2w8xlh1jkpjbi7-nixops-1.5.1/lib/python2.7/site-packages/nixops/deployment.py", line 705, in worker
    raise Exception("unable to activate new configuration")
Exception: unable to activate new configuration
```

I deployed from a nix installaton on a Debian 8 box, in case this is relevant.

Any idea what is going on or how I could debug this further?

**Comment by rbvermaa** [comment]
@michas2 What nixpkgs did you use to deploy this?

**Comment by michas2** [comment]
I simply too a debian box, used `curl https://nixos.org/nix/install | sh` to install nix and then `nix-env -i nixops` to install nixops. For the deployment I used `load-balancer.nix` and `load-balancer-ec2.nix` from the manual.

**Comment by michas2** [comment]
Is this a problem on my (debian) side or one on the other (google) side?
I understood that there is some file missing on the remote nix store, right?

**Comment by rbvermaa** [comment]
If I remember correctly, installing nix like that will give you the nixpkgs-unstable channel. Could you please try with nixos-17.03 channel, which is the latest stable release of nixos? There might be an issue with the unstable problem, I can probably try to check that only tomorrow, earliest.

**Comment by michas2** [comment]
Yes, you are right. It gave me the unstable channel.

```
$ nix-channel --list
nixpkgs https://nixos.org/channels/nixpkgs-unstable
```

**Comment by michas2** [comment]
I now tried to use a stable version with `nix-env -f https://github.com/NixOS/nixpkgs-channels/archive/nixos-17.03.tar.gz -ri nix nixops`.
Unfortunately the deployment ends up with exactly the same error.

**Comment by michas2** [comment]
I think I understand what is going on. `google-instance-setup.service` tries to create a key:
```
   104      command = ['ssh-keygen', '-t', key_type, '-f', temp_key, '-N', '', '-q']
   105      try:
   106        self.logger.info('Generating SSH key %s.', key_dest)
   107        subprocess.check_call(command)
```
unfortunately it has no dependency on ssh. Therefore there is no ssh-keygen installed and even if I would install it additionally, it would not be available as the PATH in `/etc/systemd/system/google-instance-setup.service` only includes explicit dependencies.

**Comment by rbvermaa** [comment]
google-instance-setup.service was introduced after 17.03, so it looks like you are still using nixpkgs-unstable for your deployments. I have pushed NixOS/nixpkgs@0783efb41cd4db584102b331bff561e8e7274268 to make openssh available to this service.

However, please use nixos-17.03 channel or release-17.03 branch of nixpkgs for your deployments. Either via switching channels, setting your NIX_PATH, or by passing in -I nixpkgs=ttps://github.com/NixOS/nixpkgs-channels/archive/nixos-17.03.tar.gz  or -I nixpkgs=/path/to/nixpkgs-17.03/clone/ to your deployment.

**Comment by michas2** [comment]
Thanks a lot!
Now it works both with the old (17.03) and the new (patched) version. :)
