### ISSUE TITLE
vmware vsphere support

### ISSUE THREAD

**Issue by techtangents** [NixOS/nixops#727]
It would be great if nixops could make vmware vsphere vms.

**Comment by qubitrenegade** [comment]
Seconded!

I just found /r/NixOS a couple days ago and started looking into NixOS.

I think the whole philosophy of Nix, NixOS, and NixOps really fits with the direction we're trying to go (reproducible, immutable, infrastructure that isn't inundated with random containers from various vendors all of which need their own security audits...), but as a VMware shop, not having vSphere support pretty much makes this a non-starter for us.

I guess we could continue using Terraform to deploy VMs, and then let NixOps take over once the instance has been provisioned... but that seems like it would defeat the whole philosophy behind Nix...

**Comment by grahamc** [comment]
NixOps backends can be provided as plugins now :)

**Comment by evanjs** [comment]
It might be helpful if any attempts at such a plugin are linked back here. 

Or whatever’s best for keeping interested users updates 🤷‍♂️
