### ISSUE TITLE
Allow nixops to use another user than root for SSHing

### ISSUE THREAD

**Issue by lejonet** [NixOS/nixops#730]
It would seem like nixops is hardcoded to use root as the user account it uses for SSH connections to the machines.
Regardless if deployment.targetHost references a ssh-config host or is in the form of "example@1.2.3.4" nixops prepends "root@" to it and tries to connect.

It would be nice to have the option of specifying both what user it should connect as, and what mechanism it should use to gain the elevated privileges, when it needs them, on the target machine (sudo, su, doas, future implementations).

**Comment by lejonet** [comment]
The code in use by the SSH and SSHMaster classes seems to already support supplying an user other than root, both the run_command()and _get_target() methods have an argument to supply an user other than root but it defaults to User=None which triggers _get_target() to supply root as user. Even the __init__ method of SSHMaster has an user argument.

However, this isn't used at all in the 3 invocations of run_command() I can find in nixops/deployments.py (line 672, 682 and 927) but the SSH class supplies the argument when instantiating SSHMaster in self._ssh_master at line 195 in nixops/ssh_util.py.

So all-in-all it seems like the "only" thing that needs to be done is make it possible to set a config value for the user, and make it trickle down to the SSH/SSHMaster objects and the same with the elevation mechanism, tho there some code to amend the command to be executed when it is set needs to be coded.

**Comment by jbgi** [comment]
As Azure no more allows to provisionning of vm with `root` as admin user, this a blocking point for us to try out nixops on azure.

**Comment by teto** [comment]
I can't login directly as root on some servers here for security reasons so I concur on this.

**Comment by mvgijssel** [comment]
+1 on this, would love not to expose the root user over SSH

**Comment by devhell** [comment]
+1 from me too. Not only that, but the [documentation](https://nixos.org/nixops/manual/#sec-deploying-to-physical-nixos) seems to be a bit misleading, as it gives the impression that this is the most straight-forward way of managing a fleet of already existing NixOS machines, which is clearly not the case if one has not enabled root SSH access on those machines (e.g., because one has specified a different username for maintenance tasks).

**Comment by adisbladis** [comment]
See https://github.com/NixOS/nixops/pull/1270. Ideally the privilege escalation mechanism should be pluggable, but I'm OK with just hard-coding sudo for now.
