### ISSUE TITLE
Create a new release 1.6?

### ISSUE THREAD

**Issue by andir** [NixOS/nixops#738]
Would you consider creating a new release? I am especially interested in having a released version (in nixos/unstable) that contains the IPv6 fix (#735) I provided.

There don't seem to be any milestones, blocking issues (for 1.6) or any other planned tasks (that I could find) open that would speak against releasing (a minor?) release.

The changes since the last release seem to be mostly focused on bug fixes as well: https://github.com/NixOS/nixops/compare/v1.5.1...master

**Comment by bjornfor** [comment]
+1.

**Comment by betaboon** [comment]
+1. especially for this one: d7411ed1af6063085f43db41b994524edcee85a8

**Comment by betaboon** [comment]
@rbvermaa what do you think ?

**Comment by rbvermaa** [comment]
Sorry, I missed the notification. I can create a new release next week.

**Comment by betaboon** [comment]
very nice, thank you :)

**Comment by dhess** [comment]
@rbvermaa Can you please have a look at #741 first? I'm pretty certain this will break all DigitalOcean deployments.

**Comment by domenkozar** [comment]
https://github.com/NixOS/nixops/commit/379b1f933b930aafc8d386d8bfec97ce0e775628
