### ISSUE TITLE
DigitalOcean droplet creation broken

### ISSUE THREAD

**Issue by dhess** [NixOS/nixops#741]
bc9c1fd5d56698e3b6309cff14fb346ad1acb252 broke DigitalOcean initial deployments, which are inaccessible for a few minutes while the base install is "infected" by NixOS. I believe that `ConnectionError` is a Python 3-only exception.

```
do-host..........> creating droplet ...[in-progress] [in-progress] [in-progress] [in-progress] [in-progress] [in-progress] [completed] 162.243.155.87
do-host..........> waiting for SSH.........error: global name 'ConnectionError' is not defined
```

**Comment by betaboon** [comment]
i just ran into the same 'ConnectionError' when working with the virtualbox deploy-environment:

```
$ nixops start --include vbox
vbox....> starting...
vbox....> Waiting for VM "nixops-7c75396e-b5a2-11e7-9b55-0a0027000000-vbox" to power on...
vbox....> VM "nixops-7c75396e-b5a2-11e7-9b55-0a0027000000-vbox" has been successfully started.
vbox....> waiting for IP address... 192.168.56.101
vbox....> waiting for SSH......error: global name 'ConnectionError' is not defined
```

**Comment by AmineChikhaoui** [comment]
ConnectionError seems to be a python3 specific exception so it should probably be removed from except statements until nixops is moved to python 3. OSError should be sufficient.

**Comment by dhess** [comment]
I tried patching this by using just `OSError` and leaving the rest of the commit intact, but ran into a different problem, so that simple change doesn't seem sufficient. I ended up reverting the commit entirely in my NixOps fork.

**Comment by domenkozar** [comment]
Sorry for the mess, pushed a fix.
