### ISSUE TITLE
fetch-ssh-keys.service fails on GCE

### ISSUE THREAD

**Issue by P-E-Meunier** [NixOS/nixops#756]
On GCE, Nix tries to start a service called `fetch-ssh-keys`, but it seems to be using obsolete calls to the GCE API.

I feel like this is something I could fix myself (and submit a PR), but the documentation doesn't mention anything about where this is defined.

Is the standard way a find/grep on nixpkgs? on the nixops source?

**Comment by P-E-Meunier** [comment]
The last part of the URL seems to be called `ssh-keys` now, not `sshKeys` (which is what the service calls).

**Comment by AmineChikhaoui** [comment]
@P-E-Meunier you can find the definition in nixpkgs:nixos/modules/virtualisation/google-compute-image.nix, I think I saw this issue as well, would be nice if you fix it.

**Comment by P-E-Meunier** [comment]
Will fix in exchange for documentation (in the manual or on the wiki) on how these images are supposed to work, how they're generated and uploaded.

I am willing to test and to write it up in the manual. I like this project, I want to use it, but I have absolutely no clue how this works right now (I've learned mostly from looking at nix and python code, and this was done manually by someone, apparently).

**Comment by P-E-Meunier** [comment]
Here is an extra problem with that service: even if they're fetched, authorized keys get written to `/root/.ssh/authorized_keys`, which is probably the only option, but is ignored by nix (as far as I can tell) if you also set your authorized keys in the nix file.

**Comment by pvgoran** [comment]
As far as I understand, Nixos writes authorized keys into `/etc/ssh/authorized_keys.d/user`, rather than into `~user/.ssh/authorized_keys`. So maybe this is not a problem after all?
