### ISSUE TITLE
nixops obeys PYTHONPATH

### ISSUE THREAD

**Issue by cleverca22** [NixOS/nixops#779]
if you add nixops into the `buildInputs` of an env for use under `nix-shell`, then the entire python closure of nixops gets added to `PYTHONPATH` automatically, and that has priority over nixops's own dependencies

this results in future builds of nixops via `nix-build -A nixops` using the old version of the source, rather then the new version

the root problem, is that the `propagated-native-build-inputs` of nixops inserts python into the nix-shell, which adds the python setup hook, which inserts every other dep into `PYTHONPATH` and the `bin/nixops` wrapper obeys that

**Comment by domenkozar** [comment]
Fixed in https://github.com/NixOS/nixops/compare/issue-779?expand=1
