### ISSUE TITLE
EC2 c5 instances

### ISSUE THREAD

**Issue by Baughn** [NixOS/nixops#780]
Amazon recently [introduced](https://aws.amazon.com/about-aws/whats-new/2017/11/introducing-amazon-ec2-c5-instances-the-next-generation-of-compute-optimized-instances/) the C5 class of compute-optimized instances, running on Skylake.

These are slightly cheaper per-compute, but they also use a different hypervisor, which breaks nixops. Here's a sample output: http://sprunge.us/JEBi

Nixops only appears to get this far when using spot prices. For on-demand instances, for whatever reason, I instead get an error stating that there's no public IP (yet).... although `nixops info` clearly shows that IP.

**Comment by edolstra** [comment]
This was fixed by https://github.com/NixOS/nixpkgs/commit/0c5a587eeba5302ff87e494baefd2f14f4e19bee, but the AMIs haven't been updated. In the meantime you can create instance with an older instance type, stop it, and then change the instance type to c5.*.
