### ISSUE TITLE
Incorrect logic for checking for ssh port availability on nixops deploy

### ISSUE THREAD

**Issue by kuznero** [NixOS/nixops#784]
`nixops deploy` does not take `~/.ssh/config` or `/etc/ssh/ssh_config` into account. But `nixops ssh` does.

*UPDATE* Incorrect logic for checking for ssh port availability on nixops deploy (has nothing to do with adhering to ssh configs, please read the thread)

**Comment by edolstra** [comment]
Please provide more detail.

**Comment by kuznero** [comment]
Generally I am trying to learn how to work with `nixops` behind a corporate proxy. `ssh` can be treated with `~/.ssh/config` file like this:

```
Host *
  ProxyCommand nc -X connect -x 127.0.0.1:3128 %h %p
```

This helps me `ssh` through the proxy (currently I have `cntlm` installed locally that passes through requests to real corporate proxy). This is equivalent to running raw `ssh user@host -o "ProxyCommand nc -X connect -x 127.0.0.1:3128 %h %p"`.

So, `nixops deploy` as one of last steps is trying to `ssh` into provisioned servers (I am testing it with AWS EC2 at the moment). And it does not work. But when I try `nixops ssh server` it works. I also tried playing with adding and remove `~/.ssh/config` file and it seems that it is needed, but it is only `nixops ssh ...` that takes it into account, but not `nixops deploy`.

**Comment by kuznero** [comment]
And even when my machine is configured system-wide with:

```nix
  programs.ssh.extraConfig = ''
Host *
  ProxyCommand nc -X connect -x 127.0.0.1:3128 %h %p
  '';
```

`nixops deploy` still does not take it into account, but `nixops ssh server` does. That is currently a showstopper for using `nixops` behind corporate proxy. At least this is one of the scenarios.

**Comment by kuznero** [comment]
Running `SSH_ARGS="ProxyCommand=nc -X connect -x 127.0.0.1:3128 %h %p" nixops deploy -d box` does not work either.

**Comment by kuznero** [comment]
`waiting for SSH...` is what hangs. So, I guess it does not necessarily indicates that `nixops deploy` does not take ssh configs into account, it might just be waiting for the port openings. But that still hangs for some reason.

**Comment by kuznero** [comment]
I just managed to comment out parts of the `wait_for_ssh` function in `nixops/backends/__init__.py` such that it does not try to wait for ssh port opening without using ssh as a tool:

```python
    def wait_for_ssh(self, check=False):
        """Wait until the SSH port is open on this machine."""
        # if self.ssh_pinged and (not check or self._ssh_pinged_this_time): return
        # self.log_start("waiting for SSH...")
        # nixops.util.wait_for_tcp_port(self.get_ssh_name(), self.ssh_port, callback=lambda: self.log_continue("."))
        # self.log_end("")
        # if self.state != self.RESCUE:
        #     self.state = self.UP
        self.state = self.UP
        self.ssh_pinged = True
        self._ssh_pinged_this_time = True
```

And it just works. I realize though that it is an important step to check of ssh port availability, but in case I am behind proxy and using `ProxyCommand` it is not the right port that is getting checked. I suspect that the check if it needs to be kept at all has to be improved to account for such situations. Are there any suggestions for how to do it, @edolstra, @domenkozar ?

**Comment by thpham** [comment]
Hello @kuznero, I have a similar situation and I would like to know if there is improvements ?

**Comment by tazjin** [comment]
This is a bit of an issue for us because we're intending to deploy via SSH bastion hosts. I'm not sure that the port check should happen at all for machines that weren't provisioned by Nix (i.e. configured directly with `deployment.targetHost`)

**Comment by shmish111** [comment]
Similar situation, I want to use bastion machines
