### ISSUE TITLE
AWS: update iam roles on ec2 instance

### ISSUE THREAD

**Issue by cleverca22** [NixOS/nixops#785]
refer to [1]

currently, boto (both 2 and 3) lack API's for DescribeIamInstanceProfileAssociations/AssociateIamInstanceProfile/DisassociateIamInstanceProfile

so there is no way to modify the iam roles attached to an instance after deploy

once boto has been updated, the code in nixops to use it can be written

[1] https://github.com/NixOS/nixops/pull/786/commits/a52d957e82d89640a4c77b382280c3bf62852f4c

**Comment by copumpkin** [comment]
How do you mean?

http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.Client.disassociate_iam_instance_profile
http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.Client.associate_iam_instance_profile
http://boto3.readthedocs.io/en/latest/reference/services/ec2.html#EC2.Client.describe_iam_instance_profile_associations

**Comment by cleverca22** [comment]
ah, i couldn't find anything close in the source at https://github.com/boto/boto3 and i didnt dig thru the docs hard enough
but also, i think nixops ec2 is using boto2?, so that still has to be ported over as well

**Comment by rbvermaa** [comment]
This should be fixed with cbb2ecc
