### ISSUE TITLE
How can I see the NixOS configuration that results from 'nixops deploy'?

### ISSUE THREAD

**Issue by chris-martin** [NixOS/nixops#794]
I can use `nixops deploy --build-only` to get the build *result*, but how do I see what the Nix expression was that got built?

Or, an alternative question: How can I see the full NixOS configuration that's currently running on my server?

For context: I have a server that I created using NixOps; I'd like to stop using NixOps and start deploying by other means, but first I need to figure out what NixOps *did* so that I can recreate it.

**Comment by aij** [comment]
Your question seems confusing/confused, because the nix expression is the *input* to nixops, not it's output. 

I don't think nixops saves a copy of all the inputs it's been given anywhere, but you can use your favorite version control system.

If you want to print part of the configuration, perhaps `nixops show-option` is what you're looking for.

**Comment by edolstra** [comment]
There is `nixops show-physical` that prints the machine configurations generated by NixOps. Together with the input configurations, this constitutes the configuration that gets evaluated/built.

The actual evaluation is done by calling `nix/eval-machine-info.nix` with appropriate arguments. In particular, the `networkExprs` argument will be the concatenation of the user inputs and the generated configuration (i.e. `nixops show-physical`).

**Comment by chris-martin** [comment]
@aij 

> because the nix expression is the *input* to nixops

The input to nixops is *part of* the nix expression is, and then nixops combines that with additional stuff like `imports = [ <nixpkgs/nixos/modules/virtualisation/amazon-image.nix> ];`, right?

@edolstra

> `nixops show-physical`

I see, thank you, that seems to be what I'm after.

**Comment by DavidEGrayson** [comment]
> How can I see the full NixOS configuration that's currently running on my server?

Go to your server and look at `/run/current-system`.  It is a symbolic link to the NixOS configuration built by Nixops.  Note that this is just a bunch of files, directories and links.  It is not a Nix expression, but it represents the output that Nixops / NixOS generated from your Nix expression.

You can also see all the installed configurations in `/nix/var/nix/profiles/`.

You can also run `nixops dump-nix-paths` on your NixOps machine to get access to the configurations it has built.
