### ISSUE TITLE
Request: alternative method for encryptedLinksTo

### ISSUE THREAD

**Issue by andrewchambers** [NixOS/nixops#797]
Currently it seems the encryptedLinksTo feature uses tcp over tcp which is known to have poor performance, see http://sites.inka.de/bigred/devel/tcp-tcp.html for an explanation.

While this is useful if udp is not available, an alternative vpn without this issue would be a nice extra option.

**Comment by cleverca22** [comment]
one option would be toxvpn, it uses UDP and hole punching to just automatically find both ends, no need to setup any port forwarding, just need to retrieve the public key from every node, and authorize it on every other node

**Comment by grahamc** [comment]
encryptedLinksTo were dropped, see #1293 and #1294.
