### ISSUE TITLE
encrypedLinksTo feature should provide local address in participating machines' configuration

### ISSUE THREAD

**Issue by pvgoran** [NixOS/nixops#813]
I don't see an obvious/straightforward way for a machine connected via `encryptedLinksTo` to find out what its local address in the encrypted network is. This is quite an essential feature for configuring services that need to be only accessible from the encrypted network, by having them listening only on the right IPs.

I can see two ways to achieve it:

1. Change the logic of generating `/etc/hosts` to use the encrypted IP in `<machine>-encrypted` record, if the machine is participating in any tunnel. Right now, `<machine>-encrypted` is always `127.0.0.1`. This is not the best way, as it doesn't actually provide an IP; some services may work if instructed to listen on a hostname (instead of IP), while some other services can insist on having an IP.

2. Add the configuration option `networking.encryptedIPv4` that would be auto-filled by nixops if the machine is participating in any tunnel. Maybe even set `networking.privateIPv4` to the same value as well, if it's not already set (by a backend or otherwise).

Or maybe I'm missing something, and this is already available?

**Comment by grahamc** [comment]
encryptedLinksTo were dropped, see #1293 and #1294.
