### ISSUE TITLE
ssh key management not working

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixops#858]
When connecting to newly created local libvirtd running virtual machines, I get the following message. 

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:TgziYhSQ3fdu7QN34nOIqYZsA7X6qGWh/AYgQ/xx4Cc.
Please contact your system administrator.
```

Either someone hacked into my internal virtual network or there seems to be something wrong with the way NixOps manages its ssh keys. It's the first time I have seen this issue with NixOps.  

```
 - system: `"x86_64-linux"`
-  nixops version: `1.5.1`
 - host os: `Linux 4.13.4, NixOS, 17.09.git.39cd40f (Hummingbird)`
 - multi-user?: `yes`
 - sandbox: `no`
 - version: `nix-env (Nix) 1.11.15`
 - channels(root): `"nixos-17.09.2182.7f6f0c49f0"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos/nixpkgs`
```

**Comment by teto** [comment]
I do have this from times to times, also after many cycles of destroy/deploy, my .ssh/known_hosts kinda gets filled and I have some trouble connecting to the VMs because of that I suspect (`nixops ssh` stays stuck - maybe trying all the keys).

**Comment by DavHau** [comment]
I'm experiencing the same issue with the google cloud plugin. Whenever i `destroy` a deployment and re-deploy, google likes to reuse ip addresses of the earlier destroyed instances. This leads to a key mismatch in `~/.ssh/known_hosts`.

What could nixops do to prevent this issue in general?
