### ISSUE TITLE
GCP instances are auto generating ssh host keys on 17.09 which breaks known_hosts machinery

### ISSUE THREAD

**Issue by AmineChikhaoui** [NixOS/nixops#859]
Since NixOS 17.09 @zimbatm worked on adding few google systemd services to manage accounts/instance setup https://github.com/NixOS/nixpkgs/commit/c93d68b6ed77. Unfortunately, it seems the `systemd.services.google-instance-setup` is breaking the known_hosts machinery in NixOps which takes care of generating the host keys and updating the known_hosts, as the service will regenerate the host keys as soon as the boot is done and thus makes the known_hosts file out of sync: https://github.com/GoogleCloudPlatform/compute-image-packages/blob/master/google_compute_engine/instance_setup/instance_setup.py#L183.

**Comment by AmineChikhaoui** [comment]
@zimbatm what do you think is the best way to handle this, might be better to make the service optional maybe ? Or we could just do `systemd.services.google-instance-setup.enable = false;` in nixops I guess depending on nixpkgs version.

**Comment by zimbatm** [comment]
Ideally both could work together. One way of doing that I think would be for nixops to extend the list of 
https://github.com/NixOS/nixpkgs/blob/aaa4cd02d96bf2d1110be08a68eb68a9187e94cb/nixos/modules/services/networking/ssh/sshd.nix#L321-L322
with it's own file. And then upload his list to that location.
This also has the benefit of being quite backward-compatible since the option was there for a while already.

**Comment by AmineChikhaoui** [comment]
@zimbatm actually I wasn't talking about users authorized keys but rather ssh hosts keys.

**Comment by zimbatm** [comment]
Oops sorry. It doesn't make sense to me why anyone would mess with the `known_hosts` file.
Do you have an example of what is generated by the google-instance-setup service and nixops?

**Comment by AmineChikhaoui** [comment]
@zimbatm oh wait seems in EC2 backend, there is also a regeneration of the host key file by restarting sshd: https://github.com/NixOS/nixops/blob/master/nixops/backends/ec2.py#L1018 and then the generated key is copied back to the statefile/known_hosts so maybe we can do the same in GCE instances.

**Comment by rbvermaa** [comment]
I added some config to prevent the replacement of the host key: 7efdef0b66b733f5fb8129d6856a587591198cdb
