### ISSUE TITLE
NixOps tries to connect to non-existing machines

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixops#891]
First it tries to create some security groups and other resources (like IAM roles), which all work fine, but then *without* having created any EC2 machines, it outputs:
```
ssh: Could not resolve hostname ec2machine: Name or service not known
```

It should first connect to AWS APIs to check whether it has actually created the machine that it is trying to connect to, and when ssh fails, it should output clearly the shell command that it tried and why it believes that it should work in the first place. If the program had been designed to do that, it would simply output an assertion error and I as a user wouldn't have to convince you that there is a bug in the program.

On a scale of badness, I have no words for this program behavior.

When it finishes, I get: unable to start SSH master connection to ec2machine.

This is with version b1ea71d70a673ef0 of nixops, but with master it was the same.

**Comment by rbvermaa** [comment]
Do you have more information or some expression that reproduces this issue? The error suggests that it is connecting via the machine name, which suggests that you are not using the ec2 backend, but the (default) 'none' backend (which can be used to deploy to arbitrary nixos hosts, that are not provisioned in nixops).

**Comment by coretemp** [comment]
@rbvermaa This was caused by a usage of `//` in the wrong position (i.e. something like

```
{deployment.targetEnv = "ec2";} // {deployment.foobar = 1;} 
```
), which resulted in `deployment.targetEnv` being silently set to `none`, which resulted in this issue. 

In the debug mode, you could do a program analysis and then suggest to the user to not do that and instead do X. If life is too short for that, you can close this. 

It was an extremely frustrating experience.

**Comment by rbvermaa** [comment]
@coretemp although I understand that it can be frustrating to debug, I consider this a nix issue, please file an issue there.
