### ISSUE TITLE
Add documentation about resources.elasticFileSystems

### ISSUE THREAD

**Issue by BjornMelgaard** [NixOS/nixops#913]
Can someone add `resources.elasticFileSystems` to https://nixos.org/nixops/manual/

**Comment by BjornMelgaard** [comment]
@AmineChikhaoui yohoo

**Comment by AmineChikhaoui** [comment]
@BjornMelgaard note that it will show up in the official manual once a new nixops release is ready which should be soon if I'm not wrong :)
