### ISSUE TITLE
Deleting and Destroying a deployment with a missing nix expression is broken after 1.6

### ISSUE THREAD

**Issue by Chakerbh** [NixOS/nixops#917]
When you delete the nix expression of a deployment you can no longer destroy it nor delete it. I tracked down the change that caused this and it's aa96a1ab2b16c6b33c30e4f51242586e3e24d6b1. 
The steps to reproduce this is very easy, create a new deployment with a naive nix expression. after that delete the expression and voilà you can no longer delete the deployment.

**Comment by AmineChikhaoui** [comment]
cc @rbvermaa
