### ISSUE TITLE
NixOps does not support a changed instance type

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixops#928]
Using nixops master (NixOps 1.6pre0_abcdef):

`nixops deploy -d deployment --allow-reboot --show-trace`:
```
a...> changing instance type from ‘t2.nano’ to ‘t2.medium’...
a...> disassociating instance profile arn:aws:iam::<snip>:instance-profile/fooRole
error: Multiple exceptions (2): 
  * a: An error occurred (InvalidAssociationID.NotFound) when calling the DescribeIamInstanceProfileAssociations operation: An invalid association-id of 'iip-assoc-<snipA>' was given
  * b: An error occurred (InvalidAssociationID.NotFound) when calling the DescribeIamInstanceProfileAssociations operation: An invalid association-id of 'iip-assoc-<snipB>' was given
```

**Comment by AmineChikhaoui** [comment]
@coretemp I think this was fixed in https://github.com/NixOS/nixops/commit/743183fa4fab40e1eedeab57d4d149d6db842fc9, can you confirm that ?

**Comment by coretemp** [comment]
@AmineChikhaoui Thank you. I just upgraded to the new master as you said. I will confirm when I change instance type again, but that could take some time.

**Comment by coretemp** [comment]
This has worked at least a few times now. Closing. Thanks @AmineChikhaoui.
