### ISSUE TITLE
Libvirt: Use remote hypervisor?

### ISSUE THREAD

**Issue by mkaito** [NixOS/nixops#934]
As far as I can tell from reading the manual, the libvirt backend *only* supports creating VMs on the local machine, and only if it runs NixOS.

Would it be possible to have it use an existing remote hypervisor?

My use case: I would like to deploy some NixOS VMs to an existing physical server that runs libvirt on Ubuntu.

**Comment by bjornfor** [comment]
See https://github.com/NixOS/nixops/pull/824.
