### ISSUE TITLE
amazon - attach existing disk is not working using ec2.blockDeviceMapping 

### ISSUE THREAD

**Issue by srghma** [NixOS/nixops#935]
I've created an instance with something like 
```
    blockDeviceMapping = {
      "/dev/xvdg".disk = "vol-XXXXXXXX";
    };
```

I see indefinitely

```
backend...> attaching volume ‘vol-02d5f0432956f8328’ as ‘/dev/xvdg’... [attaching] [attached]
```

I've stopped the instance, ssh'ed, and see

```
$ lsblk
nvme0n1       259:0    0  200G  0 disk
└─nvme0n1p1   259:1    0  200G  0 part /
nvme1n1       259:2    0  200G  0 disk
├─nvme1n1p128 259:4    0    1M  0 part
└─nvme1n1p1   259:3    0  200G  0 part

```

Maybe its because of this new names?

P.S. also I cannot ssh to instance - waiting indefinitely

```
$ nixops --version
NixOps 1.6

```

 - system: `"x86_64-linux"`
 - host os: `Linux 4.14.34, NixOS, 18.03.132021.c0c5571ec1a (Impala)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.0`
 - channels(bjorn): `"nixos-17.09-17.09.3202.9a8344a7a72"`
 - channels(root): `"nixos-18.03, nixpkgs-unstable-18.09pre137305.d91caac6c3e"`
 - nixpkgs: `/nix/store/rjqkz2i3v1kwnhcaxxyq9pc68il8cb3a-nixos-18.03.tar.gz`

**Comment by AmineChikhaoui** [comment]
seems duplicate to https://github.com/NixOS/nixops/issues/846

**Comment by AmineChikhaoui** [comment]
closing this as duplicate to #846 . Will try to review and merge the PR that fixes this in the next days.
