### ISSUE TITLE
Add labelling for GCP disks and snapshots

### ISSUE THREAD

**Issue by amemni** [NixOS/nixops#949]
GCP labels are very useful for grouping together resources from the same development stage, easily searching for and seperatly treating resources intended for production from the ones of development .. Among use cases are Usage reports, Billing export ..

NixOps 1.6.1 applies labels to instances only in GCP, which was added by this change [#866](https://github.com/NixOS/nixops/pull/866). NixOps 1.6.1 supports tagging of instances, disks and snapshots in EC2 (whih should be the equivalent of labelling in GCP). 

As a proposal, I've created the following [pull request](https://github.com/NixOS/nixops/pull/933/commits) to do the same for disks and snapshots. Thanks.

**Comment by Chakerbh** [comment]
@AmineChikhaoui This should be closed, since the PR was merged.
