### ISSUE TITLE
Status in two states at the same time?

### ISSUE THREAD

**Issue by coretemp** [NixOS/nixops#989]
I specified an IAM role via
```
resources.iamRoles = {<snip>};
```

However, this resulted in:

```
+----------------------------+----------------------+--------------------------------+--------------------------------------------------+---------------+
| Name                       |        Status        | Type                           | Resource Id                                      | IP address    |

fooRole-prod       | Missing / Up-to-date | iam-role
```

The manual does not contain a combination of `Missing / Up-to-date`, which suggests that this is a bug. Are you aware of the eventual consistency that applies to IAM?  

I will now be forced to move this feature to Terraform.

**Comment by coretemp** [comment]
I made a mistake in the policy, which is a situation nixops doesn't cope with (that's a bug).

**Comment by AmineChikhaoui** [comment]
I think we can get rid of Up-to-date/Outdated states in non machine resources as that's not relevant.
