### ISSUE TITLE
new nixops release?

### ISSUE THREAD

**Issue by gilligan** [NixOS/nixops#999]
What about doing another release sometime soon? The vbox image was updated recently and also the route53 resource has been added. Those two would already warrant a new release in my opinion. 

What do you think?

**Comment by AmineChikhaoui** [comment]
Sounds like a good idea, I would like to merge https://github.com/NixOS/nixops/pull/965 before though.

**Comment by davidak** [comment]
There was a release on [Sep 14, 2018](https://nixos.org/nixops/manual/#ssec-relnotes-1.6.1).
